"use client";

import { useEffect, useMemo, useState } from "react";
import { Icon, IconOrb, Mascot } from "../../ui";

type PollResult={option:string;count:number;percent:number};
type Planner={polls:Array<{id:string;creator_member_id?:string|null;question:string;options:string[];anonymous:boolean;closes_at?:string|null;closed?:boolean;results?:PollResult[];totalVotes?:number}>;events:Array<{id:string;creator_member_id?:string|null;title:string;starts_at:string;location_text?:string|null}>};
type Mission={id:string;title:string;kind:string;progress:number;target:number;reward:number};
type Member={id:string;bale_user_id:number;display_name?:string|null;first_name?:string|null};
async function action(name:string,payload:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("برای استفاده از امکانات زنده، Mini App را از داخل ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action:name,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||"action_failed");return d.data}
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0);
const when=(value:string)=>new Date(value).toLocaleString("fa-IR",{weekday:"long",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"});

export default function PlannerPage(){
  const [planner,setPlanner]=useState<Planner>({polls:[],events:[]});const [missions,setMissions]=useState<Mission[]>([]);const [members,setMembers]=useState<Member[]>([]);const [ownMemberId,setOwnMemberId]=useState("");const [msg,setMsg]=useState("");const [eventTitle,setEventTitle]=useState("");const [eventTime,setEventTime]=useState("");const [eventLocation,setEventLocation]=useState("");const [pollQ,setPollQ]=useState("");const [pollOptions,setPollOptions]=useState("");const [target,setTarget]=useState("");const [amount,setAmount]=useState("10");
  async function refresh(){try{const [p,m]=await Promise.all([action("planner.read"),action("missions.read")]);setPlanner(p);setMissions(m);const session=sessionStorage.getItem("familybot.session");if(session){const r=await fetch("/api/family/dashboard",{headers:{authorization:`Bearer ${session}`},cache:"no-store"});const d=await r.json();if(d.ok){setOwnMemberId(d.dashboard?.profile?.id||"");setMembers((d.dashboard?.members||d.dashboard?.leaderboard||[]).map((x:any)=>({id:x.id,bale_user_id:x.bale_user_id,display_name:x.display_name,first_name:x.first_name})))}}}catch(e){setMsg(e instanceof Error?e.message:"دریافت اطلاعات ممکن نشد")}}
  useEffect(()=>{refresh()},[]);
  const upcoming=useMemo(()=>planner.events.filter(e=>new Date(e.starts_at).getTime()>=Date.now()).slice(0,8),[planner.events]);
  async function createEvent(){try{await action("event.create",{title:eventTitle,startsAt:eventTime,location:eventLocation});setEventTitle("");setEventTime("");setEventLocation("");setMsg("رویداد ثبت شد ✨");refresh()}catch(e){setMsg(e instanceof Error?e.message:"ثبت رویداد انجام نشد")}}
  async function cancelEvent(eventId:string){try{await action("event.cancel",{eventId});setMsg("رویداد لغو شد.");refresh()}catch(e){const t=e instanceof Error?e.message:"لغو رویداد انجام نشد";setMsg(t==="event_not_owned"?"فقط سازنده این رویداد می‌تونه لغوش کنه.":t)}}
  async function createPoll(){try{await action("poll.create",{question:pollQ,options:pollOptions.split(/[،,]/).map(x=>x.trim()).filter(Boolean)});setPollQ("");setPollOptions("");setMsg("نظرسنجی ساخته شد ✨");refresh()}catch(e){setMsg(e instanceof Error?e.message:"ساخت نظرسنجی انجام نشد")}}
  async function vote(pollId:string,index:number){try{await action("poll.vote",{pollId,optionIndex:index});setMsg("رأی شما ثبت شد 💜");refresh()}catch(e){const t=e instanceof Error?e.message:"ثبت رأی انجام نشد";setMsg(t==="poll_closed"?"این رأی‌گیری بسته شده.":t)}}
  async function closePoll(pollId:string){try{await action("poll.close",{pollId});setMsg("رأی‌گیری بسته شد و نتیجه نهایی شد.");refresh()}catch(e){const t=e instanceof Error?e.message:"بستن رأی‌گیری انجام نشد";setMsg(t==="poll_not_owned"?"فقط سازنده این رأی‌گیری می‌تونه اون رو ببنده.":t)}}
  async function transfer(){try{await action("coins.transfer",{targetMemberId:target,amount:Number(amount)});setMsg("Family Coin منتقل شد ✨");refresh()}catch(e){setMsg(e instanceof Error?e.message:"انتقال انجام نشد")}}
  async function claim(missionId:string){try{const d=await action("mission.claim",{missionId});setMsg(d.alreadyClaimed?"پاداش این مأموریت قبلاً دریافت شده.":`🎉 ${d.reward} Family Coin دریافت شد.`);refresh()}catch(e){const text=e instanceof Error?e.message:"دریافت پاداش انجام نشد";setMsg(text==="mission_not_complete"?"اول مأموریت رو کامل کن 💜":text)}}
  return <main className="appShell"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/">←</a><div className="wordmark"><b>برنامه‌ریز خانواده</b><span>تقویم، نظرسنجی و مأموریت‌ها</span></div><IconOrb name="calendar" tone="blue"/></header>{msg&&<div className="adminNotice">{msg}</div>}<section className="homeHero premiumPanel" style={{minHeight:220}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="calendar" size={15}/> Family Planner</span><h1>همه‌چیز هماهنگ، یکجا</h1><p>رویداد بساز، رأی بگیر، مأموریت‌ها رو انجام بده و Family Coin هدیه بده.</p></div><Mascot small mood="thinking"/></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow">تقویم زنده</span><h2>برنامه‌های پیش‌رو</h2></div><span className="levelPill">{fa(upcoming.length)} برنامه</span></div><div style={{display:"grid",gap:8,marginTop:12}}>{upcoming.map(e=><article className="dashboardCard" key={e.id} style={{gridTemplateColumns:"54px 1fr auto",alignItems:"center"}}><IconOrb name="calendar" tone="blue"/><div><h2>{e.title}</h2><p>{when(e.starts_at)}{e.location_text?` · ${e.location_text}`:""}</p></div>{e.creator_member_id===ownMemberId&&<button onClick={()=>cancelEvent(e.id)} className="levelPill" style={{border:0,cursor:"pointer"}}>لغو</button>}</article>)}</div></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>رویداد جدید</h2><div style={{display:"grid",gap:9}}><input className="adminInput" value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="مثلاً دورهمی جمعه"/><input className="adminInput" type="datetime-local" value={eventTime} onChange={e=>setEventTime(e.target.value)}/><input className="adminInput" value={eventLocation} onChange={e=>setEventLocation(e.target.value)} placeholder="مکان، اختیاری"/><button className="adminSave" onClick={createEvent}>ثبت در تقویم</button></div></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>نظرسنجی جدید</h2><div style={{display:"grid",gap:9}}><input className="adminInput" value={pollQ} onChange={e=>setPollQ(e.target.value)} placeholder="سؤال نظرسنجی"/><input className="adminInput" value={pollOptions} onChange={e=>setPollOptions(e.target.value)} placeholder="گزینه‌ها را با ویرگول جدا کن"/><button className="adminSave" onClick={createPoll}>ساخت نظرسنجی</button></div></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>رأی‌گیری‌های اخیر</h2>{planner.polls.map(p=><article className="dashboardCard" key={p.id} style={{display:"block",opacity:p.closed?.86:1}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><div><h2 style={{marginBottom:4}}>{p.question}</h2><small style={{color:p.closed?"#ffb2cd":"#8f85a9"}}>{p.closed?"بسته شده":`${p.totalVotes||0} رأی`}</small></div>{p.creator_member_id===ownMemberId&&!p.closed&&<button onClick={()=>closePoll(p.id)} className="levelPill" style={{border:0,cursor:"pointer"}}>بستن رأی</button>}</div><div style={{display:"grid",gap:9,marginTop:10}}>{(p.options||[]).map((o,i)=>{const r=p.results?.[i];return <button disabled={p.closed} key={i} onClick={()=>vote(p.id,i)} style={{border:0,background:"rgba(255,255,255,.045)",borderRadius:14,padding:10,color:"white",textAlign:"right",cursor:p.closed?"default":"pointer",opacity:p.closed?.9:1}}><span style={{display:"flex",justifyContent:"space-between",gap:8,fontSize:12}}><b>{o}</b><small>{r?.count||0} · {r?.percent||0}%</small></span><span className="houseProgress" style={{display:"block",marginTop:7}}><i><em style={{width:`${r?.percent||0}%`}}/></i></span></button>})}</div></article>)}</section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>مأموریت‌های من</h2><div style={{display:"grid",gap:8}}>{missions.map(m=>{const done=m.progress>=m.target;return <article className="dashboardCard" key={m.id}><IconOrb name={m.kind==="daily"?"spark":"trophy"} tone={m.kind==="daily"?"violet":"gold"}/><div style={{width:"100%"}}><h2>{m.title}</h2><p>{m.progress} / {m.target} · پاداش {m.reward} 🪙</p><div className="houseProgress"><i><em style={{width:`${Math.min(100,m.progress/m.target*100)}%`}}/></i></div>{done&&<button className="primaryCta" style={{border:0,marginTop:9}} onClick={()=>claim(m.id)}>دریافت پاداش</button>}</div></article>})}</div></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14,marginBottom:90}}><h2>هدیه Family Coin</h2><div style={{display:"grid",gap:9}}><select className="adminInput" value={target} onChange={e=>setTarget(e.target.value)}><option value="">انتخاب عضو</option>{members.filter(m=>m.id!==ownMemberId).map(m=><option key={m.id} value={m.id}>{m.display_name||m.first_name||m.bale_user_id}</option>)}</select><input className="adminInput" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="مقدار سکه"/><button className="adminSave" onClick={transfer}>ارسال هدیه</button></div></section><nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav></main>
}
