import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";
import {MATERIALS,nextHouseLevel,type MaterialId} from "@/lib/progressionCatalog";

function auth(req:NextRequest){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")?verifyFamilySession(h.slice(7)):null}
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("db_not_configured");return createClient(url,key,{db:{schema:"familybot"},auth:{persistSession:false,autoRefreshToken:false}})}
async function member(s:ReturnType<typeof db>,familyId:string,userId:number){const r=await s.from("members").select("id,coins,xp,is_founder,role").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data}
async function read(familyId:string,userId:number){const s=db(),m=await member(s,familyId,userId);const[fam,inv,members]=await Promise.all([s.from("families").select("house_level,xp").eq("id",familyId).single(),s.from("house_material_inventory").select("material_id,quantity").eq("family_id",familyId),s.from("members").select("xp").eq("family_id",familyId)]);for(const r of[fam,inv,members])if(r.error)throw r.error;const memberXp=(members.data||[]).reduce((sum,row)=>sum+Number(row.xp||0),0),familyXp=Math.max(Number(fam.data?.xp||0),memberXp),level=Math.max(1,Math.min(10,Number(fam.data?.house_level||1)));return{level,xp:familyXp,coins:Number(m.coins||0),founder:Boolean(m.is_founder||m.role==="founder"),inventory:Object.fromEntries((inv.data||[]).map(x=>[x.material_id,Number(x.quantity||0)])),next:nextHouseLevel(level)}}
export async function GET(req:NextRequest){const ses=auth(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{return NextResponse.json({ok:true,data:await read(ses.familyId,ses.userId)},{headers:{"cache-control":"no-store"}})}catch(e){console.error("house read",e);return NextResponse.json({ok:false,error:"house_read_failed"},{status:500})}}
export async function POST(req:NextRequest){const ses=auth(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const body=await req.json(),type=String(body.type||""),s=db(),m=await member(s,ses.familyId,ses.userId);if(type==="buy_material"){const id=String(body.materialId||"") as MaterialId,material=MATERIALS[id],qty=Math.max(1,Math.min(100000,Math.floor(Number(body.quantity||1))));if(!material)return NextResponse.json({ok:false,error:"unknown_material"},{status:400});const r=await s.rpc("house_buy_material_atomic",{p_family_id:ses.familyId,p_member_id:m.id,p_material_id:id,p_quantity:qty,p_unit_price:material.unitPrice});if(r.error)throw r.error;return NextResponse.json({ok:true,data:{result:r.data,...await read(ses.familyId,ses.userId)}})}if(type==="upgrade"){const current=await read(ses.familyId,ses.userId),target=nextHouseLevel(current.level);if(!target)return NextResponse.json({ok:false,error:"max_level"},{status:409});const r=await s.rpc("house_upgrade_atomic",{p_family_id:ses.familyId,p_member_id:m.id,p_expected_level:current.level,p_required_xp:target.xpRequired,p_upgrade_coins:target.upgradeCoins,p_requirements:target.materials});if(r.error)throw r.error;return NextResponse.json({ok:true,data:{result:r.data,...await read(ses.familyId,ses.userId)}})}return NextResponse.json({ok:false,error:"unknown_action"},{status:400})}catch(e:any){console.error("house action",e);const raw=String(e?.message||"");const error=raw.includes("insufficient_xp")?"insufficient_xp":raw.includes("insufficient_coins")?"insufficient_coins":raw.includes("insufficient_material")?"insufficient_material":raw.includes("level_changed")?"level_changed":"house_action_failed";return NextResponse.json({ok:false,error},{status:409})}}
