import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { verifyFamilySession } from "@/lib/familySession";
import { readMiniAppDashboard } from "@/lib/miniAppData";
import { createFamilyTask } from "@/lib/familyMutations";
import { createFamilyEvent, createFamilyPoll, transferFamilyCoins } from "@/lib/familyFeatures";
import { findFamilyMemberByName, normalizeFaNumber } from "@/lib/memberLookup";

const Body=z.object({message:z.string().min(1).max(4000),history:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().max(4000)})).max(20).default([])});
const SYSTEM=`تو Family AI هستی؛ دستیار گرم، دقیق و قابل اعتماد خانواده. فارسی روان و دوستانه حرف بزن. داده خصوصی را حدس نزن. اگر Family Context در اختیار داری فقط از همان داده استفاده کن. هیچ‌وقت ادعا نکن چیزی ثبت یا تغییر کرده مگر سرور نتیجه موفق اکشن را برگردانده باشد. پاسخ‌ها کوتاه و کاربردی باشند مگر کاربر توضیح بیشتر بخواهد.`;
function sessionFrom(req:NextRequest){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")?verifyFamilySession(a.slice(7)):null}
function fa(n:number){return new Intl.NumberFormat("fa-IR").format(n)}
function familyContext(d:any){return JSON.stringify({family:{name:d.family?.name,members:d.family?.membersCount},profile:d.profile?{name:d.profile.display_name||d.profile.first_name,coins:d.profile.coins,level:d.profile.level,rank:d.profile.rank}:null,members:(d.members||[]).slice(0,30).map((m:any)=>({name:m.display_name||m.first_name,relation:m.relation_label})),birthdays:(d.birthdays||[]).slice(0,8).map((b:any)=>({name:b.display_name||b.first_name,days:b.days,next:b.next})),tasks:(d.tasks||[]).slice(0,10).map((t:any)=>({title:t.title,status:t.status,due:t.due_at})),events:(d.events||[]).slice(0,10).map((e:any)=>({title:e.title,type:e.event_type,starts:e.starts_at}))})}
function parseClock(text:string){const m=normalizeFaNumber(text).match(/(?:ساعت\s*)?(\d{1,2})(?::(\d{2}))?/);if(!m)return{h:18,min:0};return{h:Math.max(0,Math.min(23,Number(m[1]))),min:Math.max(0,Math.min(59,Number(m[2]||0)))}}
function relativeDate(text:string){const now=new Date();const {h,min}=parseClock(text);let add=0;if(/پس.?فردا/.test(text))add=2;else if(/فردا/.test(text))add=1;else if(/امروز/.test(text))add=0;else if(/جمعه/.test(text)){const day=now.getDay();add=(5-day+7)%7||7}else return null;const d=new Date(now);d.setDate(d.getDate()+add);d.setHours(h,min,0,0);return d.toISOString()}
async function explicitAction(message:string,session:NonNullable<ReturnType<typeof sessionFrom>>){const task=message.match(/(?:یک\s+)?کار(?:\s+جدید)?[:：]?\s*(.+?)\s*(?:بساز|ثبت\s*کن)$/i);if(task){const title=task[1].trim();await createFamilyTask(session.familyId,session.userId,{title,rewardCoins:0});return`✅ کار «${title}» برای خانواده ثبت شد.`}const event=message.match(/(?:رویداد|برنامه|دورهمی)[:：]?\s*(.+?)\s+(امروز|فردا|پس.?فردا|جمعه)(.*?)(?:بساز|ثبت\s*کن)$/i);if(event){const startsAt=relativeDate(`${event[2]} ${event[3]}`);if(!startsAt)return"برای ثبت رویداد، زمان رو هم واضح بگو؛ مثلاً «دورهمی جمعه ساعت ۲۰ ثبت کن».";const title=event[1].trim();await createFamilyEvent(session.familyId,session.userId,{title,startsAt,eventType:"event"});return`📅 رویداد «${title}» با موفقیت در تقویم خانواده ثبت شد.`}const poll=message.match(/(?:نظرسنجی|رأی.?گیری)[:：]?\s*(.+?)\s+گزینه(?:‌| )?ها[:：]?\s*(.+?)\s*(?:بساز|ثبت\s*کن)$/i);if(poll){const question=poll[1].trim(),options=poll[2].split(/[،,|]/).map(x=>x.trim()).filter(Boolean);if(options.length<2)return"برای نظرسنجی حداقل دو گزینه بده؛ مثلاً «نظرسنجی شام کجا باشه گزینه‌ها: خونه، رستوران بساز».";await createFamilyPoll(session.familyId,session.userId,{question,options});return`📊 نظرسنجی «${question}» با ${fa(options.length)} گزینه ساخته شد.`}const normalized=normalizeFaNumber(message);const transferA=normalized.match(/(?:به\s+)(.+?)\s+(\d+)\s*سکه\s*(?:بده|منتقل\s*کن)$/i);const transferB=normalized.match(/(\d+)\s*سکه\s+(?:به\s+)(.+?)\s*(?:بده|منتقل\s*کن)$/i);if(transferA||transferB){const name=(transferA?.[1]||transferB?.[2]||"").trim();const amount=Number(transferA?.[2]||transferB?.[1]||0);try{const target=await findFamilyMemberByName(session.familyId,name);const result=await transferFamilyCoins(session.familyId,session.userId,{targetMemberId:target.id,amount});return`🪙 ${fa(result.amount)} Family Coin به ${result.target.name} منتقل شد.`}catch(error){const m=error instanceof Error?error.message:"transfer_failed";if(m==="member_not_found")return`عضوی با نام «${name}» پیدا نکردم. اسم نمایشی عضو رو دقیق‌تر بگو.`;if(m==="member_name_ambiguous")return`چند عضو با نام «${name}» پیدا کردم؛ اسم کامل‌تر رو بگو.`;if(m==="insufficient_coins")return"سکه کافی برای این انتقال نداری 🪙";throw error}}return null}
export async function POST(req:NextRequest){try{const session=sessionFrom(req);if(!session)return NextResponse.json({error:"unauthorized"},{status:401,headers:{"cache-control":"no-store"}});const body=Body.parse(await req.json());const dashboard=await readMiniAppDashboard(session.familyId,session.userId).catch(()=>null);const actionReply=await explicitAction(body.message,session);if(actionReply)return NextResponse.json({reply:actionReply,action:true},{headers:{"cache-control":"no-store"}});if(dashboard&&/تولد/.test(body.message)&&/(نزدیک|کیه|کی هست|چه موقع|چه روز)/.test(body.message)){const rows=(dashboard.birthdays||[]).slice(0,5);const reply=rows.length?rows.map((b:any,i:number)=>`${i+1}. ${b.display_name||b.first_name||"عضو خانواده"} — ${b.days===0?"امروز":`${fa(b.days)} روز دیگه`}`).join("\n"):"فعلاً تاریخ تولدی برای اعضای خانواده ثبت نشده.";return NextResponse.json({reply:`🎂 تولدهای نزدیک:\n${reply}`,grounded:true},{headers:{"cache-control":"no-store"}})}const base=(process.env.AI_BASE_URL||"https://api.groq.com/openai/v1").replace(/\/$/,"");const key=process.env.GROQ_API_KEY||process.env.AI_API_KEY;const model=process.env.AI_MODEL||"llama-3.3-70b-versatile";if(!key)return NextResponse.json({reply:"من به داده‌های Family Bot وصل هستم 💜 فعلاً کلید مدل زبانی روی سرور تنظیم نشده، ولی اکشن‌های امن Family Core فعالن.",demo:true},{headers:{"cache-control":"no-store"}});const context=dashboard?`\nFamily Context (private, authoritative): ${familyContext(dashboard)}`:"\nFamily Context در این درخواست در دسترس نیست؛ درباره اطلاعات خصوصی خانواده حدس نزن.";const response=await fetch(`${base}/chat/completions`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:.55,messages:[{role:"system",content:SYSTEM+context},...body.history,{role:"user",content:body.message}]})});if(!response.ok)throw new Error(`AI provider returned ${response.status}`);const data=await response.json();const reply=data?.choices?.[0]?.message?.content;if(!reply)throw new Error("AI provider returned an empty response");return NextResponse.json({reply,grounded:Boolean(dashboard)},{headers:{"cache-control":"no-store"}});}catch(error){const message=error instanceof Error?error.message:"Unknown error";return NextResponse.json({error:message},{status:400,headers:{"cache-control":"no-store"}})}}