"use client";

import {useEffect,useState} from "react";
import {Icon} from "../ui";
import {adminHeaders} from "./adminClientSession";

type Member={bale_user_id:number;display_name?:string|null;first_name?:string|null;last_name?:string|null;relation_label?:string|null;active_warnings:number};
export default function AdminModerationPanel({session}:{session:string}){const[members,setMembers]=useState<Member[]>([]);const[target,setTarget]=useState("");const[reason,setReason]=useState("");const[minutes,setMinutes]=useState(10);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
async function refresh(){const r=await fetch("/api/admin/members",{headers:adminHeaders(session),cache:"no-store"});const d=await r.json();if(d.ok)setMembers(d.rows||[]);else setMsg("دریافت اعضا ممکن نشد.")}
useEffect(()=>{void refresh()},[session]);
async function run(action:"warn"|"unwarn"|"mute"|"ban"|"unban"){if(!target){setMsg("اول یک عضو رو انتخاب کن.");return}setBusy(true);setMsg("");try{const r=await fetch("/api/admin/moderate",{method:"POST",headers:{"content-type":"application/json",...adminHeaders(session)},body:JSON.stringify({action,targetUserId:Number(target),reason,minutes})});const d=await r.json();if(!d.ok)throw new Error(d.error||"moderation_failed");setMsg(action==="warn"?`اخطار ثبت شد${typeof d.warningCount==="number"?` · ${d.warningCount} اخطار فعال`:""}`:"عملیات مدیریتی انجام شد ✅");await refresh()}catch(e){const m=e instanceof Error?e.message:"moderation_failed";setMsg(m==="self_moderation_not_allowed"?"نمی‌تونی روی اکانت خودت عملیات مدیریتی انجام بدی.":"عملیات انجام نشد.")}finally{setBusy(false)}}
return <section className="adminPanel premiumPanel" style={{marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow"><Icon name="shield" size={14}/> مدیریت اعضا</span><h2>عملیات دکمه‌ای</h2></div></div><div style={{display:"grid",gap:9}}><select className="adminInput" value={target} onChange={e=>setTarget(e.target.value)}><option value="">انتخاب عضو</option>{members.map(m=><option key={m.bale_user_id} value={m.bale_user_id}>{m.display_name||m.first_name||m.bale_user_id} · اخطار {m.active_warnings}</option>)}</select><input className="adminInput" value={reason} onChange={e=>setReason(e.target.value)} placeholder="دلیل (اختیاری)"/><label style={{display:"grid",gap:5}}>مدت Mute: <b>{minutes.toLocaleString("fa-IR")} دقیقه</b><input type="range" min="1" max="120" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><button className="adminSave" disabled={busy} onClick={()=>run("warn")}>⚠️ اخطار</button><button className="adminSave" disabled={busy} onClick={()=>run("unwarn")}>🧹 پاک‌کردن اخطار</button><button className="adminSave" disabled={busy} onClick={()=>run("mute")}>🔇 Mute</button><button className="adminSave" disabled={busy} onClick={()=>run("ban")}>⛔ Ban</button><button className="adminSave" disabled={busy} onClick={()=>run("unban")}>✅ Unban</button></div>{msg&&<div className="adminNotice">{msg}</div>}</div></section>}
