import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {createHash} from "crypto";
import {verifyFamilySession} from "@/lib/familySession";
import {DEZFULI_POEMS,DEZFULI_PROVERBS,DEZFULI_WORDS} from "@/lib/dezfuliCulture";

type Kind="joke"|"fact"|"riddle"|"motivation"|"hafez"|"dezfuli-word"|"dezfuli-proverb"|"dezfuli-poem";
const fallback={joke:["چرا کامپیوتر رفت دکتر؟ چون ویروس گرفته بود 😄","به مودم گفتم آروم‌تر کار کن؛ گفت من فقط وقتی وصل باشم حرف می‌زنم!","گوشی به شارژر گفت: بدون تو واقعاً انرژی ندارم!","برنامه‌نویس گفت پنج دقیقه استراحت می‌کنم؛ سیستم نوشت: Update 1 of 97 😄"],fact:["اختاپوس سه قلب دارد.","زنبورها می‌توانند جهت منبع غذا را با نوعی رقص به هم‌نوعانشان نشان دهند.","اثر انگشت انسان‌ها الگوهای بسیار متفاوتی دارد.","نور خورشید حدود هشت دقیقه و بیست ثانیه در راه رسیدن به زمین است."],motivation:["یک کار کوچکِ امروز، از ده تصمیم بزرگِ فردا باارزش‌تره.","امروز فقط یک قدم جلوتر برو.","پیشرفت یعنی ادامه دادن، حتی وقتی سرعتت کم شده.","کار سخت را به قدم‌های کوچک تقسیم کن و فقط قدم بعدی را انجام بده."],hafez:[{text:"رسید مژده که ایام غم نخواهد ماند",interpretation:"شرایط ثابت نمی‌ماند؛ با صبر و امید از این مرحله عبور کن."},{text:"دوش وقت سحر از غصه نجاتم دادند",interpretation:"نشانه‌ای از سبک شدن دل و پیدا شدن راهی روشن پس از سختی است."}]};
const riddles=[{q:"آن چیست که هرچه از آن بیشتر برداری، بزرگ‌تر می‌شود؟",a:"چاله"},{q:"چه چیزی مال توست ولی دیگران بیشتر از تو از آن استفاده می‌کنند؟",a:"نامت"},{q:"چه چیزی پر از سوراخ است ولی آب را نگه می‌دارد؟",a:"اسفنج"},{q:"چه چیزی پا دارد اما راه نمی‌رود؟",a:"میز"}];
function session(req:NextRequest){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")?verifyFamilySession(a.slice(7)):null}
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("db_not_configured");return createClient(url,key,{db:{schema:"familybot"},auth:{persistSession:false,autoRefreshToken:false}})}
function pick<T>(a:readonly T[]){return a[Math.floor(Math.random()*a.length)]}
function cleanJson(raw:string){const text=raw.replace(/```(?:json)?/gi,"").replace(/```/g,"").trim(),a=text.indexOf("{"),b=text.lastIndexOf("}");if(a<0||b<a)throw new Error("invalid_ai_json");return JSON.parse(text.slice(a,b+1))}
function hash(v:string){return createHash("sha256").update(v.replace(/\s+/g," ").trim()).digest("hex")}
const sourceContext={words:DEZFULI_WORDS.map(x=>({id:x.id,word:x.word,meaning:x.meaning,options:x.options,example:x.example,source:x.source})),proverbs:DEZFULI_PROVERBS,poems:DEZFULI_POEMS};
async function model(key:string,kind:Kind,recent:string[]){const base=(process.env.AI_BASE_URL||"https://api.groq.com/openai/v1").replace(/\/$/,""),preferred=process.env.AI_MODEL||"llama-3.3-70b-versatile",models=[preferred,"llama-3.3-70b-versatile","openai/gpt-oss-20b"].filter((x,i,a)=>a.indexOf(x)===i),source=kind.startsWith("dezfuli-")?`\nتنها منبع مجاز برای محتوای دزفولی این داده‌های تاییدشده است؛ واژه، شعر یا ضرب‌المثل جدید از خودت نساز:\n${JSON.stringify(sourceContext)}`:"",schema=kind==="riddle"?'{"text":"چیستان","answer":"پاسخ","source":"AI"}':kind==="dezfuli-word"?'{"wordId":"id دقیق از منبع","text":"سوال تازه درباره همان واژه","answer":"معنی دقیق","options":["سه گزینه از همان منبع"],"source":"نام منبع"}':kind==="dezfuli-proverb"||kind==="dezfuli-poem"?'{"text":"متن عین منبع","answer":"توضیح/معنی روان و تازه","source":"نام منبع"}':'{"text":"محتوا","source":"AI"}',instruction=kind==="joke"?"یک جوک کوتاه، تازه، سالم و خانوادگی فارسی بساز.":kind==="fact"?"یک دانستنی کوتاه، قابل اتکا و غیرپزشکی/غیرحقوقی فارسی بده. اگر در صحتش مطمئن نیستی موضوع دیگری انتخاب کن.":kind==="motivation"?"یک جمله انگیزشی کوتاه، طبیعی و غیرکلیشه‌ای فارسی بساز.":kind==="riddle"?"یک چیستان فارسی کوتاه با پاسخ مشخص بساز.":kind==="dezfuli-word"?"از میان واژه‌های منبع یک مورد انتخاب کن و سوالی تازه بساز. wordId و معنی و گزینه‌ها باید دقیقاً با منبع سازگار باشند.":kind==="dezfuli-proverb"?"یکی از ضرب‌المثل‌های منبع را عیناً انتخاب کن و معنی را روان و کوتاه توضیح بده.":kind==="dezfuli-poem"?"یکی از قطعه‌های دزفولی منبع را عیناً انتخاب کن و معنی را روان و کوتاه توضیح بده.":"";
 const prompt=`${instruction}\nخروجی فقط JSON معتبر مطابق ${schema} باشد. هیچ متن دیگری ننویس.${source}\nاین خروجی‌های اخیر را تکرار نکن:\n${recent.slice(0,24).join("\n---\n")||"(هیچ)"}`;let last="";for(const m of models){try{const r=await fetch(`${base}/chat/completions`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model:m,temperature:.9,max_tokens:600,response_format:{type:"json_object"},messages:[{role:"system",content:"برای بخش سرگرمی Family Bot محتوای کوتاه و مناسب خانواده تولید می‌کنی. دقت منبع از تنوع مهم‌تر است."},{role:"user",content:prompt}]}),signal:AbortSignal.timeout(18000)}),raw=await r.text();if(!r.ok)throw new Error(`provider_${r.status}`);return cleanJson(raw?String(JSON.parse(raw)?.choices?.[0]?.message?.content||""):"")}catch(e){last=e instanceof Error?e.message:"model_failed";if(last==="provider_401"||last==="provider_403")break}}throw new Error(last||"model_failed")}
function fallbackItem(kind:Kind,recent:string[]){const fresh=<T,>(items:readonly T[],text:(x:T)=>string)=>{const rows=items.filter(x=>!recent.some(r=>r.includes(text(x))));return pick(rows.length?rows:items)};if(kind==="riddle"){const r=fresh(riddles,x=>x.q);return{text:r.q,answer:r.a,source:"بانک محلی Family Bot"}}if(kind==="hafez"){const h=fresh(fallback.hafez,x=>x.text);return{text:h.text,answer:h.interpretation,source:"گزیده حافظ"}}if(kind==="dezfuli-word"){const w=fresh(DEZFULI_WORDS,x=>x.word);return{wordId:w.id,text:`معنی «${w.word}» چیه؟`,answer:w.meaning,options:[...w.options],source:w.source}}if(kind==="dezfuli-proverb"){const p=fresh(DEZFULI_PROVERBS,x=>x.text);return{text:p.text,answer:p.meaning,source:p.source}}if(kind==="dezfuli-poem"){const p=fresh(DEZFULI_POEMS,x=>x.text);return{text:p.text,answer:p.meaning,source:p.source}}if(kind==="joke"||kind==="fact"||kind==="motivation"){const text=fresh(fallback[kind],x=>x);return{text,source:"بانک محلی Family Bot"}}return{text:"فعلاً محتوایی برای این بخش پیدا نشد.",source:"Family Bot"}}
export async function POST(req:NextRequest){const ses=session(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const b=await req.json().catch(()=>({})),kind=String(b.type||"") as Kind,allowed=new Set<Kind>(["joke","fact","riddle","motivation","hafez","dezfuli-word","dezfuli-proverb","dezfuli-poem"]);if(!allowed.has(kind))return NextResponse.json({ok:false,error:"unknown_fun_type"},{status:400});const s=db(),member=await s.from("members").select("id").eq("family_id",ses.familyId).eq("bale_user_id",ses.userId).single();if(member.error)throw member.error;const old=await s.from("fun_content_history").select("content_text").eq("family_id",ses.familyId).eq("member_id",member.data.id).eq("content_type",kind).order("created_at",{ascending:false}).limit(24),recent=(old.data||[]).map(x=>String(x.content_text||""));let item:any;if(kind==="hafez")item=fallbackItem(kind,recent);else{const key=process.env.GROQ_API_KEY||process.env.AI_API_KEY;if(key){try{item=await model(key,kind,recent)}catch(e){console.error("fun AI fallback",kind,e);item=fallbackItem(kind,recent)}}else item=fallbackItem(kind,recent)}if(kind==="dezfuli-word"){const source=DEZFULI_WORDS.find(x=>x.id===String(item.wordId||""));if(!source)item=fallbackItem(kind,recent);else item={...item,wordId:source.id,answer:source.meaning,options:[...source.options],source:source.source}}const text=String(item.text||"").trim(),answer=String(item.answer||item.interpretation||"").trim(),content=`${text}\n${answer}`.trim(),contentHash=hash(content);await s.from("fun_content_history").upsert({family_id:ses.familyId,member_id:member.data.id,content_type:kind,content_hash:contentHash,content_text:content,source_label:String(item.source||"").slice(0,200)},{onConflict:"member_id,content_type,content_hash",ignoreDuplicates:true});return NextResponse.json({ok:true,data:{type:kind,text,answer,interpretation:answer,wordId:item.wordId||null,options:Array.isArray(item.options)?item.options:undefined,source:item.source||null,generated:!String(item.source||"").includes("بانک محلی")}})}catch(e){console.error("fun route",e);return NextResponse.json({ok:false,error:"fun_failed"},{status:500})}}
