import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";
import {stageFor} from "@/lib/sagoolCatalog";
type SagoolAction="feed"|"water"|"play"|"sleep"|"clean"|"train";
const DELTAS:Record<SagoolAction,Partial<Record<"hunger"|"thirst"|"energy"|"cleanliness"|"happiness"|"bond",number>>>= {feed:{hunger:24,happiness:3},water:{thirst:28},play:{happiness:22,energy:-10,bond:6},sleep:{energy:30},clean:{cleanliness:30,happiness:4},train:{happiness:7,bond:9}};
function session(req:NextRequest){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")?verifyFamilySession(a.slice(7)):null}
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("db_not_configured");return createClient(u,k,{db:{schema:"familybot"},auth:{persistSession:false,autoRefreshToken:false}})}
async function read(familyId:string,userId:number){const s=db();const m=await s.from("members").select("id").eq("family_id",familyId).eq("bale_user_id",userId).single();if(m.error)throw m.error;let pet=await s.from("sagool_pets").select("*").eq("family_id",familyId).eq("member_id",m.data.id).maybeSingle();if(pet.error)throw pet.error;if(!pet.data){const made=await s.from("sagool_pets").insert({family_id:familyId,member_id:m.data.id}).select("*").single();if(made.error)throw made.error;pet={...pet,data:made.data}}const p=pet.data as Record<string,unknown>;const level=Math.max(1,Math.floor(Number(p.xp||0)/100)+1);return{...p,level,stage:stageFor(level).stage}}
export async function GET(req:NextRequest){const s=session(req);if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{return NextResponse.json({ok:true,data:await read(s.familyId,s.userId)})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"sagool_read_failed"},{status:500})}}
export async function POST(req:NextRequest){const ses=session(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const body=await req.json() as {action?:string};if(!body.action||!(body.action in DELTAS))return NextResponse.json({ok:false,error:"unknown_action"},{status:400});const action=body.action as SagoolAction,s=db();const m=await s.from("members").select("id").eq("family_id",ses.familyId).eq("bale_user_id",ses.userId).single();if(m.error)throw m.error;await read(ses.familyId,ses.userId);const cur=await s.from("sagool_pets").select("*").eq("family_id",ses.familyId).eq("member_id",m.data.id).single();if(cur.error)throw cur.error;const current=cur.data as Record<string,unknown>,patch:Record<string,unknown>={last_care_at:new Date().toISOString(),xp:Number(current.xp||0)+(action==="train"?18:10)};for(const [key,value] of Object.entries(DELTAS[action]))patch[key]=Math.max(0,Math.min(100,Number(current[key]||0)+Number(value||0)));const up=await s.from("sagool_pets").update(patch).eq("id",cur.data.id);if(up.error)throw up.error;const state=await read(ses.familyId,ses.userId);return NextResponse.json({ok:true,data:{state,message:action==="feed"?"سگول با اشتها غذا خورد!":action==="play"?"چه بازی خوبی! سگول کلی ذوق کرد ✨":"سگول حالش بهتر شد 💜"}})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"sagool_action_failed"},{status:500})}}
