import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";

function auth(req:NextRequest){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")?verifyFamilySession(h.slice(7)):null}
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("db_not_configured");return createClient(url,key,{db:{schema:"familybot"},auth:{persistSession:false,autoRefreshToken:false}})}
const dayKey=(v:Date|string=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit"}).format(typeof v==="string"?new Date(v):v);
function weekStart(key:string){const d=new Date(`${key}T00:00:00Z`),offset=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-offset);return d.toISOString().slice(0,10)}
function state(p:any){return{stage:p.stage,level:Number(p.level||1),xp:Number(p.xp||0),hunger:Number(p.hunger||0),thirst:Number(p.thirst||0),energy:Number(p.energy||0),hygiene:Number(p.hygiene||0),happiness:Number(p.happiness||0),affection:Number(p.affection||0),health:Number(p.health||100),lastTickAt:p.last_tick_at||null}}
async function member(s:ReturnType<typeof db>,familyId:string,userId:number){const r=await s.from("members").select("id,is_founder,role").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data}
async function readAll(familyId:string,userId:number,{tick=false}:{tick?:boolean}={}){const s=db(),m=await member(s,familyId,userId);if(tick){const tr=await s.rpc("sagool_tick_atomic",{p_family_id:familyId,p_member_id:m.id});if(tr.error)throw tr.error}let p=await s.from("sagool_pets").select("*").eq("family_id",familyId).eq("member_id",m.id).maybeSingle();if(p.error)throw p.error;if(!p.data){const made=await s.from("sagool_pets").insert({family_id:familyId,member_id:m.id}).select("*").single();if(made.error)throw made.error;p=made}
 const today=dayKey(),week=weekStart(today),since=new Date(Date.now()-8*86400000).toISOString();
 const[missions,actions,claims,inventory]=await Promise.all([
  s.from("sagool_solo_missions").select("code,title,description,action_type,target,reward_coins,reward_xp,cadence,sort_order").eq("active",true).order("sort_order"),
  s.from("sagool_action_log").select("action,created_at").eq("family_id",familyId).eq("member_id",m.id).gte("created_at",since),
  s.from("sagool_daily_claims").select("mission_key,claim_date").eq("family_id",familyId).eq("member_id",m.id).gte("claim_date",week),
  s.from("sagool_inventory").select("item_id,quantity,equipped,acquired_at").eq("family_id",familyId).eq("member_id",m.id).order("acquired_at",{ascending:false})
 ]);for(const r of[missions,actions,claims,inventory])if(r.error)throw r.error;
 const ms=(missions.data||[]).map((x:any)=>{const start=x.cadence==="weekly"?week:today,progress=(actions.data||[]).filter((a:any)=>dayKey(a.created_at)>=start&&(x.action_type==="care_any"||a.action===x.action_type)).length,claimed=(claims.data||[]).some((c:any)=>c.mission_key===x.code&&String(c.claim_date)>=start);return{code:x.code,title:x.title,description:x.description,actionType:x.action_type,target:Number(x.target||1),rewardCoins:Number(x.reward_coins||0),rewardXp:Number(x.reward_xp||0),cadence:x.cadence,progress:Math.min(progress,Number(x.target||1)),complete:progress>=Number(x.target||1),claimed}});
 return{state:state(p.data),missions:ms,inventory:inventory.data||[],founder:Boolean(m.is_founder||m.role==="founder")}}
export async function GET(req:NextRequest){const ses=auth(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{return NextResponse.json({ok:true,data:await readAll(ses.familyId,ses.userId,{tick:true})},{headers:{"cache-control":"no-store"}})}catch(e){console.error("sagool read",e);return NextResponse.json({ok:false,error:"sagool_read_failed"},{status:500})}}
export async function POST(req:NextRequest){const ses=auth(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const body=await req.json(),type=String(body.type||"interact"),s=db(),m=await member(s,ses.familyId,ses.userId);
 if(type==="claim_mission"){const key=String(body.missionKey||"");const r=await s.rpc("sagool_claim_daily_mission_atomic",{p_family_id:ses.familyId,p_member_id:m.id,p_mission_key:key});if(r.error)throw r.error;return NextResponse.json({ok:true,data:{claim:r.data,...await readAll(ses.familyId,ses.userId)}})}
 if(type==="equip"){const itemId=String(body.itemId||"").slice(0,100);if(!itemId)return NextResponse.json({ok:false,error:"item_required"},{status:400});const owned=await s.from("sagool_inventory").select("item_id,equipped").eq("family_id",ses.familyId).eq("member_id",m.id).eq("item_id",itemId).maybeSingle();if(owned.error)throw owned.error;if(!owned.data)return NextResponse.json({ok:false,error:"item_not_owned"},{status:404});const next=typeof body.equipped==="boolean"?body.equipped:!Boolean(owned.data.equipped);if(next&&!owned.data.equipped){const count=await s.from("sagool_inventory").select("item_id",{count:"exact",head:true}).eq("family_id",ses.familyId).eq("member_id",m.id).eq("equipped",true);if(count.error)throw count.error;if((count.count||0)>=3)return NextResponse.json({ok:false,error:"equip_limit"},{status:409})}const updated=await s.from("sagool_inventory").update({equipped:next}).eq("family_id",ses.familyId).eq("member_id",m.id).eq("item_id",itemId);if(updated.error)throw updated.error;return NextResponse.json({ok:true,data:{...await readAll(ses.familyId,ses.userId),message:next?"آیتم روی سگول فعال شد ✨":"آیتم از حالت فعال خارج شد"}})}
 const action=String(body.action||"");const xp=action==="train"?18:action==="walk"?14:action==="play"?12:10;const r=await s.rpc("sagool_interact_atomic",{p_family_id:ses.familyId,p_member_id:m.id,p_action:action,p_cost:0,p_xp:xp});if(r.error)throw r.error;const all=await readAll(ses.familyId,ses.userId);return NextResponse.json({ok:true,data:{...all,message:action==="feed"?"سگول با اشتها غذا خورد!":action==="water"?"سگول آب تازه خورد 💧":action==="play"?"چه بازی خوبی! سگول کلی ذوق کرد ✨":action==="sleep"?"سگول یک خواب آروم داشت 🌙":action==="clean"?"سگول تمیز و مرتب شد ✨":action==="pet"?"سگول از نوازشت خوشش اومد 💜":action==="walk"?"پیاده‌روی امروز انجام شد 🐾":action==="train"?"سگول یک تمرین تازه یاد گرفت 🧠":"حال سگول بهتر شد ✨"}})}catch(e:any){console.error("sagool action",e);const msg=String(e?.message||"");return NextResponse.json({ok:false,error:msg.includes("insufficient_coins")?"insufficient_coins":msg.includes("sagool_cooldown")?"sagool_cooldown":"sagool_action_failed"},{status:400})}}
