import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";
import {stageFor} from "@/lib/sagoolCatalog";
type SagoolAction="feed"|"water"|"play"|"sleep"|"clean"|"train";
const ACTIONS=new Set<SagoolAction>(["feed","water","play","sleep","clean","train"]);
function session(req:NextRequest){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")?verifyFamilySession(a.slice(7)):null}
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("db_not_configured");return createClient(u,k,{db:{schema:"familybot"},auth:{persistSession:false,autoRefreshToken:false}})}
async function member(s:ReturnType<typeof db>,familyId:string,userId:number){const m=await s.from("members").select("id").eq("family_id",familyId).eq("bale_user_id",userId).single();if(m.error)throw m.error;return String(m.data.id)}
async function read(familyId:string,userId:number){const s=db(),memberId=await member(s,familyId,userId);let pet=await s.from("sagool_pets").select("*").eq("family_id",familyId).eq("member_id",memberId).maybeSingle();if(pet.error)throw pet.error;if(!pet.data){const made=await s.from("sagool_pets").insert({family_id:familyId,member_id:memberId}).select("*").single();if(made.error)throw made.error;pet={...pet,data:made.data}}const p=pet.data as Record<string,unknown>,level=Math.max(1,Math.floor(Number(p.xp||0)/100)+1);return{...p,level,stage:stageFor(level).stage}}
export async function GET(req:NextRequest){const ses=session(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{return NextResponse.json({ok:true,data:await read(ses.familyId,ses.userId)},{headers:{"cache-control":"no-store"}})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"sagool_read_failed"},{status:500})}}
export async function POST(req:NextRequest){const ses=session(req);if(!ses)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});try{const body=await req.json() as {action?:SagoolAction};if(!body.action||!ACTIONS.has(body.action))return NextResponse.json({ok:false,error:"unknown_action"},{status:400});const s=db(),memberId=await member(s,ses.familyId,ses.userId),result=await s.rpc("family_sagool_care_atomic",{p_family_id:ses.familyId,p_member_id:memberId,p_action:body.action});if(result.error)throw result.error;const out=result.data as {ok?:boolean;cooldown?:boolean;nextAt?:string}|null;if(out?.cooldown)return NextResponse.json({ok:false,error:"cooldown",nextAt:out.nextAt},{status:429});const state=await read(ses.familyId,ses.userId),message=body.action==="feed"?"سگول با اشتها غذا خورد!":body.action==="play"?"چه بازی خوبی! سگول کلی ذوق کرد ✨":body.action==="train"?"سگول یک حرکت تازه تمرین کرد ⭐":"سگول حالش بهتر شد 💜";return NextResponse.json({ok:true,data:{state,message}})}catch(e){console.error(e);return NextResponse.json({ok:false,error:"sagool_action_failed"},{status:500})}}
