"use client";

import { useEffect, useState } from "react";
import { Icon, IconOrb, Mascot } from "../../ui";

type Achievement={id:string;title:string;description:string;icon:string;reward:number};
type Mission={id:string;title:string;kind:string;progress:number;target:number;reward:number};
async function action(name:string,payload:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("Mini App را از داخل ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action:name,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||"action_failed");return d.data}
export default function AchievementsPage(){
  const[catalog,setCatalog]=useState<Achievement[]>([]),[owned,setOwned]=useState<string[]>([]),[missions,setMissions]=useState<Mission[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
  async function refresh(){try{const[a,m]=await Promise.all([action("achievements.evaluate"),action("missions.read")]);setCatalog(a.catalog||[]);setOwned(a.owned||[]);setMissions(m||[]);if(a.unlocked?.length)setMsg(`🎉 ${a.unlocked.length} نشان جدید آزاد شد و ${a.reward} سکه گرفتی.`)}catch(e){setMsg(e instanceof Error?e.message:"دریافت اطلاعات انجام نشد")}}
  useEffect(()=>{refresh()},[]);
  async function claim(id:string){setBusy(id);setMsg("");try{const r=await action("mission.claim",{missionId:id});setMsg(r.alreadyClaimed?"این پاداش قبلاً دریافت شده.":`🎁 +${r.reward} Family Coin دریافت شد.`);await refresh()}catch(e){setMsg(e instanceof Error&&e.message==="mission_not_complete"?"این مأموریت هنوز کامل نشده.":e instanceof Error?e.message:"Claim انجام نشد")}finally{setBusy("")}}
  return <main className="appShell"><div className="ambient ambientA"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/section/leaderboard">←</a><div className="wordmark"><b>دستاوردها</b><span>نشان‌ها و مأموریت‌های زنده</span></div><IconOrb name="trophy" tone="gold"/></header>{msg&&<div className="adminNotice">{msg}</div>}<section className="homeHero premiumPanel" style={{minHeight:220}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="spark" size={14}/> Achievement Center</span><h1>هر قدم، یک افتخار ✨</h1><p>دستاوردها از فعالیت واقعی شما در Family Bot محاسبه می‌شن.</p></div><Mascot small mood="celebrate"/></section><section className="dashboardGrid" style={{marginTop:14}}>{catalog.map((b,i)=>{const unlocked=owned.includes(b.id);return <article className="dashboardCard" key={b.id} style={{opacity:unlocked?1:.58}}><IconOrb name={(b.icon||"trophy") as any} tone={unlocked?(i%4===0?"pink":i%4===1?"violet":i%4===2?"gold":"cyan"):"violet"}/><div><div style={{display:"flex",gap:7,alignItems:"center"}}><h2 style={{margin:0}}>{b.title}</h2><span className="levelPill">{unlocked?"✓ باز شده":"🔒 قفل"}</span></div><p>{b.description}</p><b style={{fontSize:10,color:"#ffcf72"}}>+{b.reward} 🪙</b></div></article>})}</section><section className="adminPanel premiumPanel" style={{marginTop:14,marginBottom:90}}><h2>مأموریت‌ها</h2><div style={{display:"grid",gap:9}}>{missions.map(m=>{const done=m.progress>=m.target;return <article className="dashboardCard" key={m.id}><IconOrb name={m.kind==="daily"?"spark":"trophy"} tone={m.kind==="daily"?"violet":"gold"}/><div style={{width:"100%"}}><h2>{m.title}</h2><p>{m.progress} / {m.target} · +{m.reward} 🪙</p><div className="houseProgress"><i><em style={{width:`${Math.min(100,m.progress/m.target*100)}%`}}/></i></div></div><button disabled={!done||busy===m.id} onClick={()=>void claim(m.id)}>{busy===m.id?"...":done?"دریافت":"در حال انجام"}</button></article>})}</div></section></main>}
