"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {Icon,Mascot} from "../../ui";
import styles from "./games.module.css";

type Dashboard={profile?:{coins?:number;rank?:number|null;streak?:number;xp?:number;level?:number;is_founder?:boolean}|null;leaderboard?:Array<{display_name?:string|null;first_name?:string|null;xp?:number}>};
type Quiz={id:string;prompt:string;options:string[];reward_coins:number};
type GameResult={kind:"coin"|"dice"|"rps";title:string;main:string;detail?:string;reward?:string};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0);

export default function GamesPage(){
  const[d,setD]=useState<Dashboard>({}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[quiz,setQuiz]=useState<Quiz|null>(null),[trivia,setTrivia]=useState<Quiz|null>(null),[gameResult,setGameResult]=useState<GameResult|null>(null);
  async function api(action:string,extra:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("Mini App را از داخل بله باز کن.");const r=await fetch("/api/family/game",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,...extra})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"game_failed");return x.result}
  async function triviaApi(action:"start"|"answer",extra:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("Mini App را از داخل بله باز کن.");const r=await fetch("/api/family/trivia",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,...extra})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"trivia_failed");return x.result}
  async function play(action:string,extra:Record<string,unknown>={}){setBusy(true);setNotice("");setGameResult(null);try{const r=await api(action,extra);if(action==="dice")setGameResult({kind:"dice",title:"نتیجه تاس",main:fa(r.value),detail:"🎲 تاس امروزت"});if(action==="coin")setGameResult({kind:"coin",title:"شیر یا خط",main:r.side,detail:r.side==="شیر"?"🦁 شیر اومد!":"➖ خط اومد!"});if(action==="rps"){const names=["سنگ","کاغذ","قیچی"],outcome=r.outcome==="win"?"تو بردی! 🎉":r.outcome==="draw"?"مساوی شد 😄":"این دست سکتور برد 🤖";setGameResult({kind:"rps",title:"سنگ کاغذ قیچی",main:outcome,detail:`تو: ${names[r.choice]} · سکتور: ${names[r.bot]}`,reward:r.outcome==="win"?`+${fa(r.reward)} سکه`:undefined})}if(action==="quiz.start")setQuiz(r);if(action==="speed.start")setNotice(`🏁 سؤال مسابقه داخل گروه بله ارسال شد؛ جایزه ${fa(r.reward)} سکه است.`)}catch(e){setNotice(e instanceof Error?e.message:"بازی اجرا نشد")}finally{setBusy(false)}}
  async function startTrivia(){setBusy(true);setNotice("");setGameResult(null);try{setTrivia(await triviaApi("start"))}catch(e){const m=e instanceof Error?e.message:"Family Trivia اجرا نشد";setNotice(m==="trivia_needs_three_members"?"برای Family Trivia حداقل ۳ عضو ثبت‌شده لازم داریم.":m)}finally{setBusy(false)}}
  async function answer(index:number){if(!quiz)return;setBusy(true);try{const r=await api("quiz.answer",{sessionId:quiz.id,option:index});setNotice(r.correct?`✅ درست بود! +${fa(r.reward)} سکه`:`❌ جواب درست نبود`);setQuiz(null)}catch(e){setNotice(e instanceof Error?e.message:"ثبت جواب انجام نشد")}finally{setBusy(false)}}
  async function answerTrivia(index:number){if(!trivia)return;setBusy(true);try{const r=await triviaApi("answer",{sessionId:trivia.id,option:index});setNotice(r.correct?`💜 خانواده‌تو خوب می‌شناسی! +${fa(r.reward)} سکه و +${fa(r.xp)} XP`:`❌ این جواب درست نبود`);setTrivia(null)}catch(e){setNotice(e instanceof Error?e.message:"ثبت جواب انجام نشد")}finally{setBusy(false)}}
  useEffect(()=>{const session=sessionStorage.getItem("familybot.session");if(!session)return;fetch("/api/family/dashboard",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.ok)setD(x.dashboard||{})}).catch(()=>undefined)},[]);
  const leaders=d.leaderboard||[],profile=d.profile,founder=Boolean(profile?.is_founder);
  return <main className={styles.page}>
    <header className={styles.header}><Link href="/" className={styles.back}>←</Link><div><h1>مرکز بازی</h1><p>بازی، رقابت و جایزه خانوادگی</p></div><Link href="/section/leaderboard" className={styles.trophy}><Icon name="trophy"/></Link></header>
    <section className={styles.hero}><div><span className={styles.pill}><Icon name="games" size={15}/> بازی واقعی امروز</span><h2>Family Trivia</h2><p>سؤال از اطلاعات واقعی اعضای همین خانواده ساخته می‌شه؛ ببین چقدر همدیگه رو می‌شناسید.</p><div className={styles.heroButtons}><button disabled={busy} onClick={()=>void startTrivia()}>شروع Family Trivia</button><Link href="/section/game-guide">راهنمای بازی‌ها</Link></div></div><div className={styles.heroArt}><Mascot small/><span>?</span><i>FAMILY</i></div></section>
    {notice&&<div className="adminNotice" style={{marginTop:10}} onClick={()=>setNotice("")}>{notice}<small className={styles.dismiss}>برای بستن لمس کن</small></div>}
    {gameResult&&<section className="gameResultSheet" role="dialog" aria-modal="true" aria-label={gameResult.title}><button onClick={()=>setGameResult(null)} aria-label="بستن" style={{position:"absolute",left:16,top:14,border:0,background:"rgba(255,255,255,.08)",color:"white",width:34,height:34,borderRadius:12,fontSize:20}}>×</button><div style={{textAlign:"center"}}><div className={gameResult.kind==="coin"?"resultCoin":""} style={gameResult.kind!=="coin"?{width:118,height:118,borderRadius:34,margin:"0 auto 12px",display:"grid",placeItems:"center",fontSize:gameResult.kind==="dice"?52:32,fontWeight:1000,background:"radial-gradient(circle at 35% 25%,#7feaff,#6737ff 55%,#1d0b55)",boxShadow:"0 0 44px rgba(86,118,255,.42)"}:undefined}>{gameResult.kind==="coin"?"🪙":gameResult.kind==="dice"?gameResult.main:"✊"}</div><span className="eyebrow">{gameResult.title}</span><h2 style={{fontSize:24,margin:"8px 0"}}>{gameResult.kind==="dice"?`عدد ${gameResult.main}`:gameResult.main}</h2>{gameResult.detail&&<p style={{fontSize:12,color:"#c8bfe1"}}>{gameResult.detail}</p>}{gameResult.reward&&<b style={{display:"block",color:"#ffd36b",fontSize:16,marginTop:8}}>{gameResult.reward}</b>}<button className="primaryCta" style={{marginTop:14}} onClick={()=>setGameResult(null)}>ادامه بازی</button></div></section>}
    {trivia&&<div className={styles.quizBackdrop} onClick={()=>!busy&&setTrivia(null)}><section className={styles.quizSheet} onClick={e=>e.stopPropagation()}><span className={styles.sheetHandle}/><header><b>💜 Family Trivia</b><button disabled={busy} onClick={()=>setTrivia(null)}>×</button></header><h2>{trivia.prompt}</h2><div className={styles.quizOptions}>{trivia.options.map((o,i)=><button disabled={busy} key={`${o}-${i}`} onClick={()=>void answerTrivia(i)}>{o}</button>)}</div><p>جایزه: {fa(trivia.reward_coins)} سکه · +۸ XP · زمان پاسخ: ۲ دقیقه</p></section></div>}
    {quiz&&<div className={styles.quizBackdrop} onClick={()=>!busy&&setQuiz(null)}><section className={styles.quizSheet} onClick={e=>e.stopPropagation()}><span className={styles.sheetHandle}/><header><b>🧠 کوئیز عمومی</b><button disabled={busy} onClick={()=>setQuiz(null)}>×</button></header><h2>{quiz.prompt}</h2><div className={styles.quizOptions}>{quiz.options.map((o,i)=><button disabled={busy} key={`${o}-${i}`} onClick={()=>void answer(i)}>{o}</button>)}</div><p>جایزه: {fa(quiz.reward_coins)} سکه · +۱۰ XP · زمان پاسخ: ۲ دقیقه</p></section></div>}
    <section className={styles.quickStats}><div><Icon name="coins"/><b>{founder?"∞":fa(profile?.coins||0)}</b><span>سکه واقعی</span></div><div><Icon name="trophy"/><b>{profile?.rank?`#${fa(profile.rank)}`:"—"}</b><span>رتبه خانواده</span></div><div><Icon name="spark"/><b>{fa(profile?.streak||0)}</b><span>Streak</span></div></section>
    <div className={styles.title}><h2>بازی‌های فوری</h2><span>۵ بازی فعال</span></div>
    <section className={styles.gameGrid}>
      <button className={styles.game} disabled={busy} onClick={()=>void startTrivia()}><span className={styles.gameIcon}>💜</span><h3>Family Trivia</h3><p>سؤال از اعضای همین خانواده</p><b>+۱۲ سکه · +۸ XP</b><i>فعال</i></button>
      <button className={styles.game} disabled={busy} onClick={()=>void play("quiz.start")}><span className={styles.gameIcon}>🧠</span><h3>کوئیز عمومی</h3><p>تک‌نفره · سؤال زمان‌دار</p><b>+۱۵ سکه · +۱۰ XP</b><i>فعال</i></button>
      <button className={styles.game} disabled={busy} onClick={()=>void play("dice")}><span className={styles.gameIcon}>🎲</span><h3>تاس</h3><p>تک‌نفره</p><b>+۱ XP برای بازی</b><i>فعال</i></button>
      <button className={styles.game} disabled={busy} onClick={()=>void play("coin")}><span className={styles.gameIcon}>🪙</span><h3>شیر یا خط</h3><p>تک‌نفره</p><b>+۱ XP برای بازی</b><i>فعال</i></button>
      <article className={styles.game}><span className={styles.gameIcon}>✊</span><h3>سنگ کاغذ قیچی</h3><p>یک انتخاب بزن</p><div className={styles.rpsButtons}>{["سنگ","کاغذ","قیچی"].map((v,i)=><button key={v} disabled={busy} onClick={()=>void play("rps",{choice:i})}>{v}</button>)}</div><b>برد: +۵ سکه · +۳ XP</b><i>فعال</i></article>
    </section>
    <div className={styles.title}><h2>بازی‌های گروهی</h2><Link href="/section/game-guide">آموزش همه بازی‌ها ←</Link></div>
    <section className={styles.gameGrid}>
      <Link href="/section/community" className={styles.game}><span className={styles.gameIcon}>⚔️</span><h3>دوئل خانوادگی</h3><p>دو نفره · انتخاب همزمان سنگ/کاغذ/قیچی</p><b>جایزه واقعی Family Coin</b><i>فعال</i></Link>
      <Link href="/section/multiplayer" className={styles.game}><span className={styles.gameIcon}>🕵️</span><h3>جاسوس</h3><p>لابی واقعی · حداقل ۳ بازیکن</p><b>نقش خصوصی برای هر عضو</b><i>فعال</i></Link>
      <button className={styles.game} disabled={busy} onClick={()=>void play("speed.start")}><span className={styles.gameIcon}>🏁</span><h3>مسابقه سرعت</h3><p>سؤال به گروه بله ارسال می‌شه</p><b>اولین جواب درست: +۲۰ سکه</b><i>فعال</i></button>
      <Link href="/section/multiplayer" className={styles.game}><span className={styles.gameIcon}>📝</span><h3>اسم‌فامیل</h3><p>لابی واقعی · حرف تصادفی · ۹۰ ثانیه</p><b>امتیاز و جایزه واقعی</b><i>فعال</i></Link>
      <Link href="/section/multiplayer" className={styles.game}><span className={styles.gameIcon}>❓</span><h3>۲۰ سؤال</h3><p>پاسخ مخفی · سؤال بله/خیر · حدس نهایی</p><b>حدس درست: +۳۰ سکه</b><i>فعال</i></Link>
      <Link href="/section/mafia" className={styles.game}><span className={styles.gameIcon}>🎭</span><h3>مافیا Lite</h3><p>نقش مخفی · رأی‌گیری دوری · حذف بازیکن</p><b>برد تیم: +۲۰ سکه</b><i>فعال</i></Link>
    </section>
    <section className={styles.tournament}><div><span>🏆 رتبه‌بندی زنده</span><h2>قهرمان‌های خانواده</h2><p>بر اساس XP واقعی اعضا</p><div className={styles.progress}><i style={{width:`${Math.min(100,Number(profile?.xp||0)/5)}%`}}/></div></div><div className={styles.podium}>{leaders.slice(0,3).map((m,i)=><span className={i===0?styles.first:""} key={i}>{i===0?"🥇":i===1?"🥈":"🥉"}<b>{m.display_name||m.first_name||"عضو"}</b></span>)}</div></section>
    <section className={styles.rewards}><header><h2>جایزه روزانه</h2><span>Streak: {fa(profile?.streak||0)} روز</span></header><p style={{fontSize:10,color:"#a99fba"}}>جایزه روزانه واقعی از منوی ربات یا صفحه پروفایل قابل دریافت است.</p></section>
    <nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a className="active" href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav>
  </main>
}
