import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";

function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Family Core database is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function sessionFrom(req:NextRequest){const auth=req.headers.get("authorization")||"";return auth.startsWith("Bearer ")?verifyFamilySession(auth.slice(7)):null}

export async function GET(req:NextRequest){try{const s=sessionFrom(req);if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});const supabase=db();const member=await supabase.from("members").select("id,coins,xp").eq("family_id",s.familyId).eq("bale_user_id",s.userId).single();if(member.error)throw member.error;const spin=await supabase.from("lucky_wheel_spins").select("last_spun_at,last_reward_kind,last_reward_amount,spin_count").eq("member_id",member.data.id).maybeSingle();if(spin.error)throw spin.error;const nextSpinAt=spin.data?.last_spun_at?new Date(new Date(spin.data.last_spun_at).getTime()+86400000).toISOString():null;return NextResponse.json({ok:true,result:{coins:member.data.coins,xp:member.data.xp,nextSpinAt,lastReward:spin.data?{kind:spin.data.last_reward_kind,amount:spin.data.last_reward_amount}:null,spinCount:spin.data?.spin_count||0}},{headers:{"cache-control":"no-store"}})}catch(error){console.error("wheel status failed",error);return NextResponse.json({ok:false,error:"wheel_unavailable"},{status:500})}}

export async function POST(req:NextRequest){try{const s=sessionFrom(req);if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});const supabase=db();const member=await supabase.from("members").select("id").eq("family_id",s.familyId).eq("bale_user_id",s.userId).single();if(member.error)throw member.error;const result=await supabase.rpc("family_spin_lucky_wheel",{p_family_id:s.familyId,p_member_id:member.data.id});if(result.error)throw result.error;const row=result.data as {spun?:boolean;reason?:string;rewardKind?:"coins"|"xp";rewardAmount?:number;nextSpinAt?:string;coins?:number;xp?:number};return NextResponse.json({ok:Boolean(row?.spun),result:row,error:row?.spun?undefined:row?.reason||"cooldown"},{status:row?.spun?200:409,headers:{"cache-control":"no-store"}})}catch(error){console.error("wheel spin failed",error);return NextResponse.json({ok:false,error:"wheel_failed"},{status:500})}}
