"use client";
import {useEffect} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {Icon} from "./ui";
const ITEMS=[
 {label:"خانه",href:"/",icon:"home" as const,active:(p:string)=>p==="/"},
 {label:"سگول",href:"/section/sagool",icon:"family" as const,active:(p:string)=>p.startsWith("/section/sagool")},
 {label:"بازی‌ها",href:"/section/games",icon:"games" as const,active:(p:string)=>p.startsWith("/section/games")||p.startsWith("/section/multiplayer")||p.startsWith("/section/mafia")},
 {label:"AI",href:"/ai",icon:"ai" as const,active:(p:string)=>p.startsWith("/ai")},
 {label:"پروفایل",href:"/section/leaderboard",icon:"profile" as const,active:(p:string)=>p.startsWith("/section/leaderboard")||p.startsWith("/section/achievements")}
];
export default function BottomNav(){const pathname=usePathname()||"/";const hidden=pathname.startsWith("/admin")||pathname.startsWith("/onboarding");useEffect(()=>{document.documentElement.classList.toggle("jahaniHasBottomNav",!hidden);return()=>document.documentElement.classList.remove("jahaniHasBottomNav")},[hidden]);if(hidden)return null;return <><nav className="jahaniBottomNav" aria-label="ناوبری اصلی">{ITEMS.map(i=>{const active=i.active(pathname);return <Link prefetch key={i.href} href={i.href} className={active?"active":""} aria-current={active?"page":undefined}><span className="jahaniNavIcon"><Icon name={i.icon} size={23}/></span><small>{i.label}</small></Link>})}</nav><style jsx global>{`
.jahaniBottomNav{bottom:0!important;width:min(620px,100%)!important;border-radius:24px 24px 0 0!important;padding:7px 8px max(7px,var(--safe-bottom))!important;min-height:calc(var(--j-nav) + var(--safe-bottom))!important;box-sizing:border-box!important;border-bottom:0!important}.jahaniHasBottomNav .appShell,.jahaniHasBottomNav .shell{padding-bottom:max(118px,calc(var(--j-nav) + var(--safe-bottom) + 34px))!important}@media(max-width:430px){.jahaniBottomNav{width:100%!important;border-radius:22px 22px 0 0!important}}
.profileAvatar>.jahaniAvatar{width:100%!important;height:100%!important}.jahaniAvatar{position:relative;display:grid;place-items:center;flex:0 0 auto;border-radius:50%;isolation:isolate;overflow:visible}.jahaniAvatar>img{position:relative;z-index:1;width:100%;height:100%;object-fit:cover;border-radius:inherit;display:block}.jahaniAvatar>b{position:relative;z-index:1}.jahaniAvatarCosmetic{position:absolute;z-index:2;inset:-5px;border-radius:50%;pointer-events:none;box-sizing:border-box}.jahaniAvatar[data-cosmetic="hero_frame"] .jahaniAvatarCosmetic{border:2px solid #60e8ff;box-shadow:0 0 0 2px rgba(119,91,255,.65),0 0 18px rgba(75,223,255,.62)}.jahaniAvatar[data-cosmetic="guardian_frame"] .jahaniAvatarCosmetic{inset:-6px;border:3px solid #d8a94a;outline:2px solid rgba(126,86,255,.7);box-shadow:0 0 22px rgba(139,88,255,.58),inset 0 0 12px rgba(255,215,112,.28)}.jahaniAvatar[data-cosmetic="sovereign_frame"] .jahaniAvatarCosmetic{inset:-7px;border:3px solid #ffd66b;outline:2px solid rgba(255,236,176,.42);box-shadow:0 0 0 4px rgba(91,65,210,.4),0 0 28px rgba(255,199,95,.55)}.jahaniAvatar[data-cosmetic="legend_glow"] .jahaniAvatarCosmetic,.jahaniAvatar[data-cosmetic="founder_cosmos"] .jahaniAvatarCosmetic{inset:-8px;border:1px solid rgba(184,129,255,.55);box-shadow:0 0 18px #7b5cff,0 0 34px rgba(55,226,255,.62)}.jahaniAvatar[data-cosmetic="cosmic_wings"] .jahaniAvatarCosmetic{inset:-14px -20px;background:radial-gradient(ellipse at 5% 55%,rgba(98,226,255,.7),transparent 30%),radial-gradient(ellipse at 95% 55%,rgba(172,103,255,.72),transparent 30%);filter:drop-shadow(0 0 10px rgba(91,211,255,.55))}.jahaniAvatar[data-cosmetic="cosmic_badge"] .jahaniAvatarCosmetic:after,.jahaniAvatar[data-cosmetic="star_nameplate"] .jahaniAvatarCosmetic:after,.jahaniAvatar[data-cosmetic="aurora_nameplate"] .jahaniAvatarCosmetic:after{content:"✦";position:absolute;right:-3px;bottom:-3px;width:22px;height:22px;display:grid;place-items:center;border-radius:50%;font-style:normal;font-size:12px;color:#fff;background:linear-gradient(145deg,#5de3ff,#7556e9);border:2px solid #11173a;box-shadow:0 4px 12px rgba(0,0,0,.35)}.equippedStoreItem{border-color:rgba(83,226,255,.52)!important;box-shadow:0 0 0 1px rgba(83,226,255,.16),0 16px 42px rgba(62,126,255,.2)!important}
`}</style></>}
