"use client";

import { FormEvent, useEffect, useState } from "react";
import { Icon } from "./ui";

type Member={id?:string;bale_user_id?:number;display_name?:string|null;first_name?:string|null};
type Props={mode:"profile"|"tasks"|"memory"|"tree"|"store";tasks?:Array<{id:string;title:string;status:string;reward_coins?:number}>;members?:Member[];coins?:number;onChanged?:()=>void};
const items=[{id:"purple_tree",name:"درخت بنفش",price:500},{id:"light_fountain",name:"فواره نور",price:800},{id:"heart_bench",name:"نیمکت قلبی",price:600},{id:"hero_frame",name:"فریم قهرمان",price:950}];

async function run(action:string,payload:Record<string,unknown>){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("برای ثبت تغییرات، Mini App را از دکمه ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,payload}),cache:"no-store"});const d=await r.json();if(!d.ok)throw new Error(d.error==="insufficient_coins"?"سکه کافی نیست.":d.error==="memory_viewers_required"?"حداقل یک عضو را برای مشاهده این خاطره انتخاب کن.":d.error==="admin_required_for_reward"?"پاداش سکه برای Task فقط توسط مدیر گروه قابل تعیین است.":d.error==="restricted_memory_requires_private_media"?"برای خاطره خصوصی یا انتخابی، فایل را مستقیم داخل Family Bot آپلود کن؛ لینک عمومی مجاز نیست.":d.error||"ثبت تغییرات ناموفق بود.");return d.data}

export default function FamilyActions({mode,tasks=[],members=[],coins=0,onChanged}:Props){
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[memoryVisibility,setMemoryVisibility]=useState<"family"|"private"|"selected">("family"),[memoryViewers,setMemoryViewers]=useState<string[]>([]),[canManage,setCanManage]=useState(false);
  useEffect(()=>{const flag=sessionStorage.getItem("familybot.canManage")||"";setCanManage(flag==="1"||flag==="true")},[]);
  async function submit(action:string,payload:Record<string,unknown>){setBusy(true);setMessage("");try{await run(action,payload);setMessage("با موفقیت ذخیره شد ✨");onChanged?.()}catch(e){setMessage(e instanceof Error?e.message:"خطا در ذخیره")}finally{setBusy(false)}}
  async function createMemory(form:HTMLFormElement){
    const session=sessionStorage.getItem("familybot.session")||"";if(!session){setMessage("Mini App را از داخل بله باز کن.");return}
    setBusy(true);setMessage("");
    try{
      const f=new FormData(form);let mediaUrl=String(f.get("media")||"").trim();const file=f.get("mediaFile");
      if(file instanceof File&&file.size>0){
        const uploadForm=new FormData();uploadForm.set("file",file);
        const upload=await fetch("/api/family/memory-media",{method:"POST",headers:{authorization:`Bearer ${session}`},body:uploadForm,cache:"no-store"});
        const uploaded=await upload.json();if(!upload.ok||!uploaded.ok)throw new Error(uploaded.error==="file_too_large"?"حجم فایل باید حداکثر ۲۰ مگابایت باشد.":uploaded.error==="unsupported_media_type"?"فقط JPG، PNG، WebP یا MP4 پشتیبانی می‌شود.":"آپلود فایل انجام نشد.");
        mediaUrl=String(uploaded.mediaRef||"");
      }
      if(memoryVisibility!=="family"&&mediaUrl&&!mediaUrl.startsWith("storage:"))throw new Error("برای خاطره خصوصی یا انتخابی، فایل را مستقیم داخل Family Bot آپلود کن؛ لینک عمومی مجاز نیست.");
      await run("memory.create",{title:f.get("title"),caption:f.get("caption"),memoryDate:f.get("date")||null,mediaUrl:mediaUrl||null,tags:String(f.get("tags")||"").split("،").map(x=>x.trim()).filter(Boolean),visibility:memoryVisibility,allowedMemberIds:memoryViewers});
      setMessage("خاطره با موفقیت و با تنظیمات حریم خصوصی ذخیره شد ✨");form.reset();setMemoryVisibility("family");setMemoryViewers([]);onChanged?.();
    }catch(e){setMessage(e instanceof Error?e.message:"ثبت خاطره انجام نشد.")}finally{setBusy(false)}
  }
  if(mode==="tree")return null;
  if(mode==="profile")return <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ویرایش پروفایل من</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit("profile.update",{displayName:f.get("name"),relationLabel:f.get("relation"),bio:f.get("bio"),birthday:f.get("birthday")})}} style={{display:"grid",gap:10}}><input name="name" placeholder="نام نمایشی"/><input name="relation" placeholder="نسبت خانوادگی؛ مثلاً پدر، خواهر..."/><input name="birthday" type="date"/><textarea name="bio" placeholder="بیوی کوتاه" rows={3}/><button className="adminSave" disabled={busy}>ذخیره پروفایل</button></form>{message&&<div className="adminNotice">{message}</div>}</section>;
  if(mode==="tasks")return <><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ساخت کار جدید</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void submit("task.create",{title:f.get("title"),description:f.get("description"),dueAt:f.get("dueAt")||null,rewardCoins:canManage?Number(f.get("reward")||0):0}).then(()=>form.reset())}} style={{display:"grid",gap:10}}><input name="title" placeholder="عنوان کار" required/><textarea name="description" placeholder="توضیح" rows={2}/><input name="dueAt" type="datetime-local"/>{canManage?<><input name="reward" type="number" min="0" max="500" placeholder="پاداش سکه"/><small style={{opacity:.68}}>پاداش سکه فقط برای مدیر گروه فعال است.</small></>:<small style={{opacity:.68}}>Task اعضای عادی بدون پاداش سیستمی ساخته می‌شود.</small>}<button className="adminSave" disabled={busy}>افزودن کار</button></form>{message&&<div className="adminNotice">{message}</div>}</section><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>تکمیل سریع</h2><div style={{display:"grid",gap:8}}>{tasks.filter(t=>t.status!=="done").map(t=><button key={t.id} className="dashboardCard" style={{textAlign:"right",width:"100%"}} disabled={busy} onClick={()=>void submit("task.complete",{taskId:t.id})}><Icon name="tasks"/> <b>{t.title}</b>{t.reward_coins?` · +${t.reward_coins} 🪙`:""}</button>)}</div></section></>;
  if(mode==="memory")return <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ثبت خاطره جدید</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();void createMemory(e.currentTarget)}} style={{display:"grid",gap:10}}><input name="title" placeholder="عنوان خاطره" required/><textarea name="caption" placeholder="چه اتفاقی افتاد؟" rows={3}/><input name="date" type="date"/><label style={{display:"grid",gap:6}}><span style={{fontSize:12}}>عکس یا ویدیو خصوصی</span><input name="mediaFile" type="file" accept="image/jpeg,image/png,image/webp,video/mp4"/><small style={{opacity:.68}}>حداکثر ۲۰MB؛ فایل در فضای خصوصی خانواده ذخیره می‌شود.</small></label>{memoryVisibility==="family"&&<input name="media" type="url" placeholder="یا لینک عمومی عکس/ویدیو (اختیاری)"/>}<input name="tags" placeholder="برچسب‌ها با ، جدا شوند"/><select value={memoryVisibility} onChange={e=>setMemoryVisibility(e.target.value as "family"|"private"|"selected")}><option value="family">قابل مشاهده برای همه خانواده</option><option value="private">خصوصی؛ فقط خودم</option><option value="selected">فقط افراد انتخاب‌شده</option></select>{memoryVisibility!=="family"&&<div className="adminNotice">🔒 رسانه این خاطره فقط از Storage خصوصی Family Bot پذیرفته می‌شود و با لینک امضاشده کوتاه‌عمر نمایش داده خواهد شد.</div>}{memoryVisibility==="selected"&&<div style={{display:"grid",gap:7}}><b style={{fontSize:12}}>چه کسانی ببینند؟</b>{members.filter(m=>m.id).map(m=><label key={m.id} style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={memoryViewers.includes(String(m.id))} onChange={e=>setMemoryViewers(v=>e.target.checked?[...v,String(m.id)]:v.filter(id=>id!==String(m.id)))}/><span>{m.display_name||m.first_name||"عضو خانواده"}</span></label>)}</div>}<button className="adminSave" disabled={busy}>{busy?"در حال ذخیره...":"ثبت خاطره"}</button></form>{message&&<div className="adminNotice">{message}</div>}</section>;
  return <section className="adminPanel premiumPanel" style={{marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow"><Icon name="coins" size={14}/> موجودی</span><h2>{new Intl.NumberFormat("fa-IR").format(coins)} سکه</h2></div></div><div className="dashboardGrid">{items.map(item=><article className="dashboardCard" key={item.id}><div><h2>{item.name}</h2><p>{new Intl.NumberFormat("fa-IR").format(item.price)} 🪙</p><button className="primaryCta" disabled={busy} onClick={()=>void submit("store.purchase",{itemId:item.id})}>خرید</button></div></article>)}</div>{message&&<div className="adminNotice">{message}</div>}</section>;
}
