"use client";

import { FormEvent, useState } from "react";
import { Icon } from "./ui";

type Props={mode:"profile"|"tasks"|"memory"|"tree"|"store";tasks?:Array<{id:string;title:string;status:string;reward_coins?:number}>;members?:Array<{id?:string;bale_user_id?:number;display_name?:string|null;first_name?:string|null}>;coins?:number;onChanged?:()=>void};
const items=[{id:"purple_tree",name:"درخت بنفش",price:500},{id:"light_fountain",name:"فواره نور",price:800},{id:"heart_bench",name:"نیمکت قلبی",price:600},{id:"hero_frame",name:"فریم قهرمان",price:950}];

async function run(action:string,payload:Record<string,unknown>){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("برای ثبت تغییرات، Mini App را از دکمه ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error==="insufficient_coins"?"سکه کافی نیست.":d.error||"ثبت تغییرات ناموفق بود.");return d.data}

export default function FamilyActions({mode,tasks=[],members=[],coins=0,onChanged}:Props){const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function submit(action:string,payload:Record<string,unknown>){setBusy(true);setMessage("");try{await run(action,payload);setMessage("با موفقیت ذخیره شد ✨");onChanged?.()}catch(e){setMessage(e instanceof Error?e.message:"خطا در ذخیره")}finally{setBusy(false)}}
  if(mode==="profile")return <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ویرایش پروفایل من</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);submit("profile.update",{displayName:f.get("name"),relationLabel:f.get("relation"),bio:f.get("bio"),birthday:f.get("birthday")})}} style={{display:"grid",gap:10}}><input name="name" placeholder="نام نمایشی"/><input name="relation" placeholder="نسبت خانوادگی؛ مثلاً پدر، خواهر..."/><input name="birthday" type="date"/><textarea name="bio" placeholder="بیوی کوتاه" rows={3}/><button className="adminSave" disabled={busy}>ذخیره پروفایل</button></form>{message&&<div className="adminNotice">{message}</div>}</section>;
  if(mode==="tasks")return <><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ساخت کار جدید</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);submit("task.create",{title:f.get("title"),description:f.get("description"),dueAt:f.get("dueAt")||null,rewardCoins:Number(f.get("reward")||0)}).then(()=>e.currentTarget.reset())}} style={{display:"grid",gap:10}}><input name="title" placeholder="عنوان کار" required/><textarea name="description" placeholder="توضیح" rows={2}/><input name="dueAt" type="datetime-local"/><input name="reward" type="number" min="0" max="500" placeholder="پاداش سکه"/><button className="adminSave" disabled={busy}>افزودن کار</button></form>{message&&<div className="adminNotice">{message}</div>}</section><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>تکمیل سریع</h2><div style={{display:"grid",gap:8}}>{tasks.filter(t=>t.status!=="done").map(t=><button key={t.id} className="dashboardCard" style={{textAlign:"right",width:"100%"}} disabled={busy} onClick={()=>submit("task.complete",{taskId:t.id})}><Icon name="tasks"/> <b>{t.title}</b>{t.reward_coins?` · +${t.reward_coins} 🪙`:""}</button>)}</div></section></>;
  if(mode==="memory")return <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ثبت خاطره جدید</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);submit("memory.create",{title:f.get("title"),caption:f.get("caption"),memoryDate:f.get("date")||null,mediaUrl:f.get("media")||null,tags:String(f.get("tags")||"").split("،").map(x=>x.trim()).filter(Boolean),visibility:f.get("visibility")==="private"?"private":"family"}).then(()=>e.currentTarget.reset())}} style={{display:"grid",gap:10}}><input name="title" placeholder="عنوان خاطره" required/><textarea name="caption" placeholder="چه اتفاقی افتاد؟" rows={3}/><input name="date" type="date"/><input name="media" type="url" placeholder="لینک عکس/ویدیو (اختیاری)"/><input name="tags" placeholder="برچسب‌ها با ، جدا شوند"/><select name="visibility" defaultValue="family"><option value="family">قابل مشاهده برای خانواده</option><option value="private">خصوصی؛ فقط خودم</option></select><button className="adminSave" disabled={busy}>ثبت خاطره</button></form>{message&&<div className="adminNotice">{message}</div>}</section>;
  if(mode==="tree")return <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>افزودن نسبت در شجره‌نامه</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);submit("relationship.save",{toMemberId:f.get("member"),relationType:f.get("relation")})}} style={{display:"grid",gap:10}}><select name="member" required defaultValue=""><option value="" disabled>عضو خانواده</option>{members.filter(m=>m.id).map(m=><option value={m.id} key={m.id}>{m.display_name||m.first_name||"عضو"}</option>)}</select><input name="relation" placeholder="نسبت؛ مثلاً خواهر، عمو، مادر..." required/><button className="adminSave" disabled={busy}>ثبت نسبت</button></form>{message&&<div className="adminNotice">{message}</div>}</section>;
  return <section className="adminPanel premiumPanel" style={{marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow"><Icon name="coins" size={14}/> موجودی</span><h2>{new Intl.NumberFormat("fa-IR").format(coins)} سکه</h2></div></div><div className="dashboardGrid">{items.map(item=><article className="dashboardCard" key={item.id}><div><h2>{item.name}</h2><p>{new Intl.NumberFormat("fa-IR").format(item.price)} 🪙</p><button className="primaryCta" disabled={busy} onClick={()=>submit("store.purchase",{itemId:item.id})}>خرید</button></div></article>)}</div>{message&&<div className="adminNotice">{message}</div>}</section>;
}
