"use client";

import { useEffect, useMemo, useState } from "react";
import { Icon, IconOrb, Mascot } from "../../ui";

type Settings={timezone:string;task_reminders_enabled:boolean;event_reminders_enabled:boolean;birthday_reminders_enabled:boolean;task_reminder_minutes:number;event_reminder_minutes:number;birthday_hour:number};
const fallback:Settings={timezone:"Asia/Tehran",task_reminders_enabled:true,event_reminders_enabled:true,birthday_reminders_enabled:true,task_reminder_minutes:60,event_reminder_minutes:60,birthday_hour:9};
const zones=["Asia/Tehran","Asia/Dubai","Asia/Istanbul","Europe/London","Europe/Berlin","America/New_York","America/Los_Angeles","America/Toronto","Australia/Sydney"];
const timings=[{value:15,label:"۱۵ دقیقه قبل"},{value:60,label:"۱ ساعت قبل"},{value:1440,label:"۱ روز قبل"}];

export default function ReminderAdminPage(){
  const session=useMemo(()=>typeof window!=="undefined"?new URLSearchParams(window.location.search).get("session")||"":"",[]);
  const [settings,setSettings]=useState<Settings>(fallback);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{if(!session){setLoading(false);return}fetch(`/api/admin/settings?session=${encodeURIComponent(session)}`).then(r=>r.json()).then(d=>{if(d.ok)setSettings({timezone:d.settings.timezone,task_reminders_enabled:d.settings.task_reminders_enabled,event_reminders_enabled:d.settings.event_reminders_enabled,birthday_reminders_enabled:d.settings.birthday_reminders_enabled,task_reminder_minutes:d.settings.task_reminder_minutes,event_reminder_minutes:d.settings.event_reminder_minutes,birthday_hour:d.settings.birthday_hour});else setMessage("جلسه مدیریت معتبر نیست یا منقضی شده.")}).catch(()=>setMessage("دریافت تنظیمات اعلان ممکن نشد.")).finally(()=>setLoading(false))},[session]);
  function patch<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(s=>({...s,[key]:value}))}
  async function save(){if(!session){setMessage("این صفحه باید از نشست امن مدیریت باز شود.");return}setSaving(true);setMessage("");try{const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify(settings)});const d=await r.json();if(!d.ok)throw new Error();setMessage("تنظیمات اعلان ذخیره شد ✨")}catch{setMessage("ذخیره تنظیمات انجام نشد.")}finally{setSaving(false)}}
  const toggle=(key:keyof Pick<Settings,"task_reminders_enabled"|"event_reminders_enabled"|"birthday_reminders_enabled">,title:string,text:string,icon:"tasks"|"calendar"|"birthday")=><article className="adminCard"><div className="adminCardHead"><IconOrb name={icon} tone="violet"/><button className={`switch${settings[key]?" on":""}`} onClick={()=>patch(key,!settings[key])}><i/></button></div><h2>{title}</h2><p>{text}</p></article>;
  return <main className="appShell adminScreen"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/>
    <header className="appHeader"><a className="roundButton" href={session?`/admin?session=${encodeURIComponent(session)}`:"/admin"}>←</a><div className="wordmark"><b>اعلان‌ها و زمان‌بندی</b><span>Reminder Control Center</span></div><span className="profileAvatar"><Icon name="reminder"/></span></header>
    <section className="adminHero premiumPanel"><div><span className="eyebrow"><Icon name="reminder" size={15}/> یادآوری هوشمند</span><h1>هیچ چیز مهمی جا نمی‌مونه</h1><p>زمان محلی خانواده و فاصله یادآوری کارها، برنامه‌ها و تولدها را تنظیم کن.</p></div><Mascot small mood="thinking"/></section>
    {!session&&<div className="adminNotice">🔐 این صفحه را از نشست امن مدیریت باز کن.</div>}{message&&<div className="adminNotice">{message}</div>}
    <section className="adminGrid">{toggle("task_reminders_enabled","یادآوری کارها","برای Taskهای باز قبل از موعد پیام می‌فرستد.","tasks")}{toggle("event_reminders_enabled","یادآوری برنامه‌ها","دورهمی و Eventهای نزدیک را یادآوری می‌کند.","calendar")}{toggle("birthday_reminders_enabled","Birthday Mode","روز تولد در ساعت انتخابی خانواده پیام جشن می‌فرستد.","birthday")}</section>
    <section className="adminPanel premiumPanel"><h2>منطقه زمانی خانواده</h2><select className="adminInput" value={settings.timezone} onChange={e=>patch("timezone",e.target.value)}>{zones.map(z=><option key={z} value={z}>{z}</option>)}</select><p style={{fontSize:11,color:"#9e95b9"}}>تمام ساعت‌های Reminder و Birthday Mode با این timezone محاسبه می‌شن.</p></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>فاصله یادآوری</h2><label style={{display:"grid",gap:6,marginTop:10}}>Taskها<select className="adminInput" value={settings.task_reminder_minutes} onChange={e=>patch("task_reminder_minutes",Number(e.target.value))}>{timings.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label style={{display:"grid",gap:6,marginTop:12}}>برنامه‌ها<select className="adminInput" value={settings.event_reminder_minutes} onChange={e=>patch("event_reminder_minutes",Number(e.target.value))}>{timings.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><p style={{fontSize:10,color:"#8f85a9",lineHeight:1.8}}>گزینه ۱۵ دقیقه روی Cronهای کم‌فرکانس به‌صورت best-effort اجرا می‌شود؛ برای دقت دقیقه‌ای باید اجرای Cron با فاصله کوتاه‌تر در پلن میزبانی فعال باشد.</p></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ساعت Birthday Mode</h2><label>ساعت محلی <b>{settings.birthday_hour.toLocaleString("fa-IR")}:۰۰</b><input type="range" min="0" max="23" value={settings.birthday_hour} onChange={e=>patch("birthday_hour",Number(e.target.value))}/></label></section>
    <button className="adminSave" disabled={loading||saving} onClick={save}>{loading?"در حال دریافت...":saving?"در حال ذخیره...":"ذخیره تنظیمات اعلان"}</button>
  </main>
}
