import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {verifyFamilySession} from "@/lib/familySession";
import {baleApi} from "@/lib/bale";
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Family Core database is not configured");return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function sessionFrom(req:NextRequest){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")?verifyFamilySession(a.slice(7)):null}
async function ownerCheck(chatId:number,userId:number){const r=await baleApi<{result?:Array<{status?:string;user?:{id?:number}}> }>("getChatAdministrators",{chat_id:chatId});const row=r.result?.find(x=>String(x.user?.id)===String(userId));return Boolean(row&&["creator","owner"].includes(String(row.status||"").toLowerCase()))}
async function member(familyId:string,userId:number){const r=await db().from("members").select("id").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data.id as string}
export async function GET(req:NextRequest){try{const s=sessionFrom(req);if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});const supabase=db(),me=await member(s.familyId,s.userId),owner=await ownerCheck(s.chatId,s.userId).catch(()=>false);const mine=await supabase.from("family_fund_memberships").select("id,status,note,created_at,reviewed_at").eq("family_id",s.familyId).eq("member_id",me).maybeSingle();if(mine.error)throw mine.error;let rows:unknown[]=[];if(owner){const q=await supabase.from("family_fund_memberships").select("id,status,note,created_at,reviewed_at,member_id,members!family_fund_memberships_member_id_fkey(display_name,first_name,relation_label)").eq("family_id",s.familyId).order("created_at",{ascending:false});if(q.error)throw q.error;rows=q.data||[]}return NextResponse.json({ok:true,isOwner:owner,mine:mine.data||null,rows,featureStatus:"coming_soon"})}catch(error){console.error("fund read failed",error);return NextResponse.json({ok:false,error:"fund_unavailable"},{status:500})}}
export async function POST(req:NextRequest){try{const s=sessionFrom(req);if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});const body=await req.json() as {action?:string;membershipId?:string;note?:string;status?:string};const supabase=db(),me=await member(s.familyId,s.userId),action=String(body.action||"");if(action==="join"){const r=await supabase.from("family_fund_memberships").upsert({family_id:s.familyId,member_id:me,status:"pending",note:String(body.note||"").slice(0,500)||null,reviewed_at:null,reviewed_by_member_id:null},{onConflict:"family_id,member_id"}).select("id,status").single();if(r.error)throw r.error;return NextResponse.json({ok:true,row:r.data})}if(action==="review"){if(!await ownerCheck(s.chatId,s.userId))return NextResponse.json({ok:false,error:"owner_required"},{status:403});const status=String(body.status||"");if(!["approved","rejected"].includes(status))return NextResponse.json({ok:false,error:"invalid_status"},{status:400});const r=await supabase.from("family_fund_memberships").update({status,reviewed_at:new Date().toISOString(),reviewed_by_member_id:me}).eq("id",String(body.membershipId||"")).eq("family_id",s.familyId).select("id,status").single();if(r.error)throw r.error;return NextResponse.json({ok:true,row:r.data})}return NextResponse.json({ok:false,error:"unknown_action"},{status:400})}catch(error){console.error("fund action failed",error);return NextResponse.json({ok:false,error:"fund_action_failed"},{status:500})}}
