"use client";
import {useEffect,useMemo,useState} from "react";
import "./wheel.css";

type Status={coins:number;xp:number;nextSpinAt:string|null;lastReward:{kind:"coins"|"xp";amount:number}|null;spinCount:number};
type Reward={kind:"coins"|"xp";amount:number};
const slices=["۵۰ سکه","۶۰ XP","۱۰۰ سکه","۳۰ XP","۲۵۰ سکه","۱۲۰ XP"];
export default function WheelPage(){const[status,setStatus]=useState<Status|null>(null);const[busy,setBusy]=useState(false);const[rotation,setRotation]=useState(0);const[reward,setReward]=useState<Reward|null>(null);const[now,setNow]=useState(Date.now());const session=useMemo(()=>typeof window!=="undefined"?sessionStorage.getItem("familybot.session")||"":"",[]);
useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
async function load(){if(!session)return;const r=await fetch("/api/family/wheel",{headers:{authorization:`Bearer ${session}`},cache:"no-store"});const d=await r.json();if(d.ok)setStatus(d.result)}
useEffect(()=>{void load()},[session]);
const remaining=status?.nextSpinAt?Math.max(0,new Date(status.nextSpinAt).getTime()-now):0;const ready=!status?.nextSpinAt||remaining<=0;const clock=remaining?`${String(Math.floor(remaining/3600000)).padStart(2,"0")}:${String(Math.floor((remaining%3600000)/60000)).padStart(2,"0")}:${String(Math.floor((remaining%60000)/1000)).padStart(2,"0")}`:"آماده";
async function spin(){if(!session||busy||!ready)return;setBusy(true);setReward(null);try{const r=await fetch("/api/family/wheel",{method:"POST",headers:{authorization:`Bearer ${session}`}});const d=await r.json();if(!d.ok){await load();return}const got={kind:d.result.rewardKind,amount:Number(d.result.rewardAmount)} as Reward;const index=got.kind==="coins"?(got.amount===50?0:got.amount===100?2:4):(got.amount===60?1:got.amount===30?3:5);const target=360*7+(360-index*60-30);setRotation(x=>x+target);setTimeout(()=>{setReward(got);setStatus(s=>s?{...s,coins:Number(d.result.coins),xp:Number(d.result.xp),nextSpinAt:d.result.nextSpinAt,lastReward:got,spinCount:s.spinCount+1}:s);setBusy(false)},4300)}catch{setBusy(false)}}
return <main className="wheelPage"><div className="wheelStars"/><header className="wheelHeader"><a href="/" aria-label="بازگشت">←</a><div><b>گردونه شانس</b><span>یک شانس در هر ۲۴ ساعت</span></div><i>✦</i></header><section className="wheelHero"><span className="wheelKicker">DAILY LUCK</span><h1>امروز ستاره‌ها چی برات دارن؟</h1><p>گردونه رو بچرخون و Family Coin یا XP بگیر.</p></section><section className="wheelStage"><div className="wheelPointer">◆</div><div className="wheelHalo"/><div className="wheelDisc" style={{transform:`rotate(${rotation}deg)`}}>{slices.map((x,i)=><span key={x} style={{transform:`rotate(${i*60+30}deg) translateY(-126px) rotate(${-i*60-30}deg)`}}>{x}</span>)}</div><button className="wheelHub" onClick={spin} disabled={!ready||busy}><b>{busy?"...":"SPIN"}</b><small>{busy?"در حال چرخش":"بزن بریم"}</small></button></section><section className="wheelStats"><article><span>🪙</span><div><small>Family Coin</small><b>{Number(status?.coins||0).toLocaleString("fa-IR")}</b></div></article><article><span>✦</span><div><small>XP</small><b>{Number(status?.xp||0).toLocaleString("fa-IR")}</b></div></article></section><div className={`wheelCooldown ${ready?"ready":""}`}><span>{ready?"✦":"◷"}</span><div><small>{ready?"گردونه آماده است":"شانس بعدی"}</small><b>{clock}</b></div></div>{reward&&<div className="rewardOverlay" onClick={()=>setReward(null)}><div className="rewardAura">{Array.from({length:18}).map((_,i)=><i key={i} style={{transform:`rotate(${i*20}deg) translateY(-112px)`}}>✦</i>)}</div><div className="rewardCard"><span>✦</span><small>برنده شدی!</small><strong>{reward.amount.toLocaleString("fa-IR")} {reward.kind==="coins"?"Family Coin":"XP"}</strong><p>جایزه به حساب Family Bot تو اضافه شد.</p><button>عالیه!</button></div></div>}</main>}
