import { createClient } from "@supabase/supabase-js";

export type AdminGroupSettings={anti_flood:boolean;anti_link:boolean;lock_photo:boolean;lock_video:boolean;lock_document:boolean;lock_forward:boolean;flood_limit:number;flood_window_seconds:number;flood_mute_minutes:number;warn_limit:number;welcome_enabled:boolean};
const defaults:AdminGroupSettings={anti_flood:true,anti_link:false,lock_photo:false,lock_video:false,lock_document:false,lock_forward:false,flood_limit:5,flood_window_seconds:5,flood_mute_minutes:10,warn_limit:3,welcome_enabled:true};
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Family Core database is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
const columns="anti_flood,anti_link,lock_photo,lock_video,lock_document,lock_forward,flood_limit,flood_window_seconds,flood_mute_minutes,warn_limit,welcome_enabled";
export async function readAdminSettings(familyId:string){const {data,error}=await db().from("group_settings").select(columns).eq("family_id",familyId).maybeSingle();if(error)throw error;return {...defaults,...(data??{})} as AdminGroupSettings}
export async function writeAdminSettings(familyId:string,input:Partial<AdminGroupSettings>){const clean:AdminGroupSettings={anti_flood:Boolean(input.anti_flood),anti_link:Boolean(input.anti_link),lock_photo:Boolean(input.lock_photo),lock_video:Boolean(input.lock_video),lock_document:Boolean(input.lock_document),lock_forward:Boolean(input.lock_forward),welcome_enabled:Boolean(input.welcome_enabled),flood_limit:Math.max(3,Math.min(20,Number(input.flood_limit)||5)),flood_window_seconds:Math.max(2,Math.min(30,Number(input.flood_window_seconds)||5)),flood_mute_minutes:Math.max(1,Math.min(10080,Number(input.flood_mute_minutes)||10)),warn_limit:Math.max(1,Math.min(10,Number(input.warn_limit)||3))};const {data,error}=await db().from("group_settings").upsert({family_id:familyId,...clean,updated_at:new Date().toISOString()},{onConflict:"family_id"}).select(columns).single();if(error)throw error;return data as AdminGroupSettings}
export async function readModerationLog(familyId:string,limit=30){const {data,error}=await db().from("moderation_actions").select("id,actor_bale_user_id,target_bale_user_id,action,reason,metadata,created_at").eq("family_id",familyId).order("created_at",{ascending:false}).limit(Math.max(1,Math.min(100,limit)));if(error)throw error;return data??[]}
