type BaleMethod = "sendMessage"|"editMessageText"|"deleteMessage"|"answerCallbackQuery"|"banChatMember"|"unbanChatMember"|"restrictChatMember"|"getChatAdministrators"|"pinChatMessage"|"unpinChatMessage"|"setWebhook"|"getWebhookInfo";
const API_BASE="https://tapi.bale.ai/bot",DEFAULT_APP_URL="https://familybot-gray.vercel.app";
export type BaleInlineButton={text:string;callback_data?:string;url?:string;web_app?:{url:string}};
export async function baleApi<T=unknown>(method:BaleMethod,payload:Record<string,unknown>={}){const token=process.env.BALE_BOT_TOKEN;if(!token)throw new Error("BALE_BOT_TOKEN is not configured");const response=await fetch(`${API_BASE}${token}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),cache:"no-store"});const data=await response.json();if(!response.ok||data?.ok===false)throw new Error(data?.description??`Bale API ${method} failed`);return data as T}
export function sendMessage(chatId:string|number,text:string,extra:Record<string,unknown>={}){return baleApi("sendMessage",{chat_id:chatId,text,...extra})}
export function answerCallbackQuery(callbackQueryId:string,text?:string,showAlert=false){return baleApi("answerCallbackQuery",{callback_query_id:callbackQueryId,...(text?{text}:{}),show_alert:showAlert})}
export function editMessageText(chatId:string|number,messageId:number,text:string,extra:Record<string,unknown>={}){return baleApi("editMessageText",{chat_id:chatId,message_id:messageId,text,...extra})}
export function openMiniAppKeyboard(){const url=process.env.NEXT_PUBLIC_APP_URL||DEFAULT_APP_URL;return{inline_keyboard:[[{text:"🏠 باز کردن JAHANI",web_app:{url}}],[{text:"🐾 سگول",web_app:{url:new URL('/section/sagool',url).toString()}},{text:"👤 پروفایل",callback_data:"menu:profile"}]]}}
function webAppButton(base:string|undefined,path:string,text:string):BaleInlineButton{return base?{text,web_app:{url:new URL(path,base).toString()}}:{text,callback_data:"menu:miniapp"}}
export function mainMenuKeyboard(_canManage=false){const base=process.env.NEXT_PUBLIC_APP_URL||DEFAULT_APP_URL;const b=(p:string,t:string)=>webAppButton(base,p,t);return{inline_keyboard:[
[b("/","🏠 Mini App")],[b("/section/sagool","🐾 سگول"),b("/section/family","👨‍👩‍👧‍👦 خانواده")],[b("/section/tree","🌳 شجره‌نامه"),b("/section/planner","📅 برنامه‌ریز")],[b("/section/wheel","🎡 گردونه"),b("/section/store","🛍 فروشگاه")],[b("/section/fund","🏦 صندوق"),b("/section/finance","💳 بانک و حساب")],[b("/section/memories","🖼 خاطرات"),b("/section/legacy","📖 خانواده ما")],[b("/section/fun","🎭 سرگرمی و دزفولی")],[b("/section/achievements","🏅 دستاوردها"),{text:"🎮 بازی‌ها",callback_data:"menu:games"}],[b("/section/community","🌍 چالش‌ها"),b("/section/tools","🧰 کاربردی")],[b("/ai","🤖 سکتور AI"),{text:"👤 پروفایل",callback_data:"menu:profile"}],[{text:"🏆 رتبه‌بندی",callback_data:"menu:rank"},{text:"🎁 جایزه روزانه",callback_data:"menu:daily"}],[{text:"🛡 مدیریت و تنظیمات گروه",callback_data:"menu:admin"}],[{text:"📜 قوانین",callback_data:"menu:rules"},{text:"❓ راهنما",callback_data:"menu:help"}]
]}}
export async function isAdmin(chatId:string|number,userId:string|number){const result=await baleApi<{result?:Array<{user?:{id?:number}}> }>("getChatAdministrators",{chat_id:chatId});return Boolean(result.result?.some(admin=>String(admin.user?.id)===String(userId)))}
