import {isFamilySafe} from "@/lib/contentSafety";
type Candidate={text?:string;extra?:string;options?:string[];source?:string;sourceMode?:string};
export type Validation={accepted:boolean;reason?:"article_not_joke"|"too_long"|"unsafe"|"duplicate"|"invalid_persian"|"missing_punchline"|"invalid_answer"|"unsupported_source"|"empty"};
const Persian=/[\u0600-\u06ff]/;
export function validateJoke(row:Candidate):Validation{const text=String(row.text||"").trim();if(!text)return{accepted:false,reason:"empty"};if(text.length>420)return{accepted:false,reason:"too_long"};if(!Persian.test(text))return{accepted:false,reason:"invalid_persian"};if(!isFamilySafe(text))return{accepted:false,reason:"unsafe"};if(/https?:\/\/|www\.|تعریف طنز|در این جوک|این لطیفه نشان می‌دهد|تحلیل|منبع:|ویکی‌پدیا|دانشنامه|عبارت است از|گونه‌ای از/i.test(text))return{accepted:false,reason:"article_not_joke"};const structured=/[؟?!]|گفت|پرسید|جواب داد|میگه|گفتم|آخرش|بعد گفت|صدا زد|نوشت|معلم|دکتر|مشتری|فروشنده/.test(text);return structured?{accepted:true}:{accepted:false,reason:"missing_punchline"}}
export function validateRiddle(row:Candidate):Validation{const q=String(row.text||"").trim(),answer=String(row.extra||"").split("/")[0].trim(),options=(row.options||[]).map(x=>String(x).trim()).filter(Boolean);if(!q||!answer)return{accepted:false,reason:"empty"};if(!Persian.test(q)||q.length<8||q.length>240)return{accepted:false,reason:"invalid_persian"};if(!isFamilySafe(`${q} ${answer}`))return{accepted:false,reason:"unsafe"};if(options.length!==4||new Set(options).size!==4||!options.includes(answer))return{accepted:false,reason:"invalid_answer"};return{accepted:true}}
export function validateFact(row:Candidate):Validation{const text=String(row.text||"").trim();if(!text)return{accepted:false,reason:"empty"};if(row.sourceMode==="sector-ai")return{accepted:false,reason:"unsupported_source"};if(text.length>900)return{accepted:false,reason:"too_long"};if(!Persian.test(text))return{accepted:false,reason:"invalid_persian"};return isFamilySafe(text)?{accepted:true}:{accepted:false,reason:"unsafe"}}
export function validateDezfuli(row:Candidate):Validation{const text=String(row.text||"").trim();if(!text)return{accepted:false,reason:"empty"};if(!["cached-remote","verified-import","curated-local"].includes(String(row.sourceMode||"")))return{accepted:false,reason:"unsupported_source"};return isFamilySafe(text)?{accepted:true}:{accepted:false,reason:"unsafe"}}
export function validateContent(kind:string,row:Candidate):Validation{if(kind==="joke")return validateJoke(row);if(kind==="riddle")return validateRiddle(row);if(kind==="fact")return validateFact(row);if(kind.startsWith("dezfuli"))return validateDezfuli(row);const text=String(row.text||"").trim();return text&&isFamilySafe(text)?{accepted:true}:{accepted:false,reason:text?"unsafe":"empty"}}
