import {sendMessage} from "@/lib/bale";

function stripXml(s:string){return s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim()}
function parseRss(xml:string,source:string){const items=[...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].slice(0,12);return items.map(m=>{const block=m[0];const title=block.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"";const link=block.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1]||"";return{title:stripXml(title),link:stripXml(link),source}}).filter(x=>x.title)}
async function fetchNews(){const feeds=[['ایرنا','https://www.irna.ir/rss'],['ایسنا','https://www.isna.ir/rss'],['مهر','https://www.mehrnews.com/rss']] as const;const all=(await Promise.all(feeds.map(async([source,url])=>{try{const r=await fetch(url,{cache:'no-store',headers:{'user-agent':'FamilyBot/1.0'}});if(!r.ok)return[];return parseRss(await r.text(),source)}catch{return[]}}))).flat();const seen=new Set<string>();return all.filter(x=>{const key=x.title.replace(/[\s‌]+/g,' ').trim();if(seen.has(key))return false;seen.add(key);return true}).slice(0,24)}
async function chooseImportant(items:Array<{title:string;source:string;link:string}>){if(!items.length)return[];const key=process.env.GROQ_API_KEY||process.env.AI_API_KEY;if(!key)return items.slice(0,5);try{const base=(process.env.AI_BASE_URL||'https://api.groq.com/openai/v1').replace(/\/$/,''),model=process.env.AI_MODEL||'llama-3.3-70b-versatile';const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:.1,messages:[{role:'system',content:'از بین تیترهای خبری ایران، فقط 5 مورد مهم‌تر و اثرگذارتر برای یک خانواده ایرانی را انتخاب کن. خروجی فقط آرایه JSON از شماره‌های 1-based باشد؛ بدون توضیح. هرگز تیتر جدید نساز و فقط شماره تیترهای ورودی را برگردان.'},{role:'user',content:items.map((x,i)=>`${i+1}. [${x.source}] ${x.title}`).join('\n')} ]}),cache:'no-store'});if(!r.ok)return items.slice(0,5);const d=await r.json();const raw=String(d?.choices?.[0]?.message?.content||'');const arr=JSON.parse(raw.match(/\[[\s\S]*?\]/)?.[0]||'[]') as number[];const chosen=[...new Set(arr)].map(n=>items[n-1]).filter(Boolean).slice(0,5);return chosen.length?chosen:items.slice(0,5)}catch{return items.slice(0,5)}}
function extractNumber(html:string,labelPattern:string){const re=new RegExp(`(?:${labelPattern})[\\s\\S]{0,220}?([0-9][0-9,]{3,})`,'i');const m=html.match(re);return m?Number(m[1].replace(/,/g,'')):null}
function plausibleRial(value:number|null,kind:'dollar'|'gold18'){if(!value||!Number.isFinite(value))return null;const min=kind==='dollar'?50_000:500_000;const max=kind==='dollar'?100_000_000:2_000_000_000;return value>=min&&value<=max?value:null}
async function fetchMarket(){try{const r=await fetch('https://www.tgju.org/',{cache:'no-store',headers:{'user-agent':'FamilyBot/1.0'}});if(!r.ok)return null;const html=await r.text();const dollar=plausibleRial(extractNumber(html,'دلار'),'dollar');const gold18=plausibleRial(extractNumber(html,'طلا\\s*۱۸|طلای\\s*18'),'gold18');if(!dollar&&!gold18)return null;return{dollar,gold18}}catch{return null}}
const money=(rial:number|null)=>rial?new Intl.NumberFormat('fa-IR').format(Math.round(rial/10)):"نامشخص";
export async function buildDailyBriefing(slot:'morning'|'evening'){const[market,news]=await Promise.all([fetchMarket(),fetchNews().then(chooseImportant)]);const title=slot==='morning'?'☀️ گزارش ۹ صبح Family Bot':'🌙 گزارش ۹ شب Family Bot';const marketText=market?`💵 دلار آزاد: ${money(market.dollar)} تومان\n🟡 طلای ۱۸ عیار: ${money(market.gold18)} تومان`:'💹 داده بازار فعلاً در دسترس نیست.';const newsText=news.length?news.map((n,i)=>`${i+1}) ${n.title} — ${n.source}`).join('\n'):'خبر مهمی دریافت نشد.';return `${title}\n\n${marketText}\n\n📰 خبرهای مهم ایران:\n${newsText}\n\nℹ️ قیمت‌ها اطلاع‌رسانی هستند و ممکن است با بازار لحظه‌ای اختلاف داشته باشند.`}
export async function sendDailyBriefingToChats(chatIds:Array<string|number>,slot:'morning'|'evening'){const text=await buildDailyBriefing(slot);const results=[];for(const chatId of chatIds){try{await sendMessage(chatId,text);results.push({chatId,ok:true})}catch(error){results.push({chatId,ok:false,error:error instanceof Error?error.message:'send_failed'})}}return results}
