import { createClient } from "@supabase/supabase-js";

function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Family Core database is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function me(familyId:string,userId:number){const r=await db().from("members").select("id,display_name,first_name").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data}
const LOCATIONS=["رستوران","فرودگاه","پارک","مدرسه","بیمارستان","سینما","هتل","ساحل","باشگاه","سوپرمارکت","ایستگاه قطار","کافه"];

export async function createSpyGame(familyId:string,userId:number){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").insert({family_id:familyId,host_member_id:m.id,game_type:"spy",public_state:{round:1}}).select("id,status,host_member_id,created_at").single();if(g.error)throw g.error;const p=await s.from("multiplayer_players").insert({game_id:g.data.id,member_id:m.id});if(p.error)throw p.error;return g.data}
export async function joinSpyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status").eq("id",gameId).eq("family_id",familyId).eq("game_type","spy").single();if(g.error)throw g.error;if(g.data.status!=="lobby")throw new Error("spy_game_started");const p=await s.from("multiplayer_players").upsert({game_id:gameId,member_id:m.id},{onConflict:"game_id,member_id"});if(p.error)throw p.error;return{joined:true}}
export async function startSpyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status,host_member_id").eq("id",gameId).eq("family_id",familyId).eq("game_type","spy").single();if(g.error)throw g.error;if(g.data.host_member_id!==m.id)throw new Error("spy_host_only");if(g.data.status!=="lobby")throw new Error("spy_game_started");const players=await s.from("multiplayer_players").select("member_id").eq("game_id",gameId);if(players.error)throw players.error;const rows=players.data||[];if(rows.length<3)throw new Error("spy_needs_three_players");const spy=rows[Math.floor(Math.random()*rows.length)].member_id,location=LOCATIONS[Math.floor(Math.random()*LOCATIONS.length)];for(const row of rows){const role=row.member_id===spy?"spy":"citizen";const u=await s.from("multiplayer_players").update({role,private_state:role==="spy"?{}:{location}}).eq("game_id",gameId).eq("member_id",row.member_id);if(u.error)throw u.error}const up=await s.from("multiplayer_games").update({status:"active",secret_state:{spyMemberId:spy,location},started_at:new Date().toISOString()}).eq("id",gameId);if(up.error)throw up.error;return{started:true,players:rows.length}}
export async function finishSpyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,host_member_id,status,secret_state").eq("id",gameId).eq("family_id",familyId).eq("game_type","spy").single();if(g.error)throw g.error;if(g.data.host_member_id!==m.id)throw new Error("spy_host_only");if(g.data.status!=="active")throw new Error("spy_not_active");const up=await s.from("multiplayer_games").update({status:"finished",finished_at:new Date().toISOString()}).eq("id",gameId);if(up.error)throw up.error;return{finished:true,reveal:g.data.secret_state}}
export async function readSpyGames(familyId:string,userId:number){const s=db(),m=await me(familyId,userId);const games=await s.from("multiplayer_games").select("id,status,host_member_id,created_at,started_at,finished_at").eq("family_id",familyId).eq("game_type","spy").order("created_at",{ascending:false}).limit(12);if(games.error)throw games.error;const ids=(games.data||[]).map(g=>g.id);if(!ids.length)return{me:m,games:[]};const players=await s.from("multiplayer_players").select("game_id,member_id,role,private_state,joined_at,members!multiplayer_players_member_id_fkey(display_name,first_name)").in("game_id",ids);if(players.error)throw players.error;return{me:m,games:(games.data||[]).map(g=>{const ps=(players.data||[]).filter(p=>p.game_id===g.id);const mine=ps.find(p=>p.member_id===m.id);return{...g,players:ps.map(p=>({member_id:p.member_id,name:(p.members as any)?.display_name||(p.members as any)?.first_name||"عضو"})),joined:Boolean(mine),myRole:mine?.role||null,myPrivate:mine?.private_state||{},isHost:g.host_member_id===m.id}})}}
