import {createClient} from "@supabase/supabase-js";

function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Family Core database is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function me(familyId:string,userId:number){const r=await db().from("members").select("id,display_name,first_name").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data}
const LETTERS=["ا","ب","پ","ت","ج","چ","خ","د","ر","ز","س","ش","ص","ط","ع","ف","ق","ک","گ","ل","م","ن","و","ه","ی"];
const CATEGORIES=["name","family","city","food","animal","object"] as const;
function normalize(v:unknown){return String(v||"").trim().replace(/ي/g,"ی").replace(/ك/g,"ک").toLocaleLowerCase("fa-IR")}
function startsWithLetter(value:string,letter:string){return normalize(value).startsWith(normalize(letter))}

export async function createNameFamilyGame(familyId:string,userId:number){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").insert({family_id:familyId,host_member_id:m.id,game_type:"name_family",public_state:{categories:CATEGORIES,durationSeconds:90}}).select("id,status,host_member_id,created_at,public_state").single();if(g.error)throw g.error;const p=await s.from("multiplayer_players").insert({game_id:g.data.id,member_id:m.id});if(p.error)throw p.error;return g.data}
export async function joinNameFamilyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status").eq("id",gameId).eq("family_id",familyId).eq("game_type","name_family").single();if(g.error)throw g.error;if(g.data.status!=="lobby")throw new Error("name_family_started");const p=await s.from("multiplayer_players").upsert({game_id:gameId,member_id:m.id},{onConflict:"game_id,member_id"});if(p.error)throw p.error;return{joined:true}}
export async function startNameFamilyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status,host_member_id,public_state").eq("id",gameId).eq("family_id",familyId).eq("game_type","name_family").single();if(g.error)throw g.error;if(g.data.host_member_id!==m.id)throw new Error("name_family_host_only");if(g.data.status!=="lobby")throw new Error("name_family_started");const players=await s.from("multiplayer_players").select("member_id",{count:"exact"}).eq("game_id",gameId);if(players.error)throw players.error;if((players.count||0)<2)throw new Error("name_family_needs_two_players");const letter=LETTERS[Math.floor(Math.random()*LETTERS.length)],endsAt=new Date(Date.now()+90_000).toISOString();const up=await s.from("multiplayer_games").update({status:"active",public_state:{...(g.data.public_state||{}),letter,endsAt},started_at:new Date().toISOString()}).eq("id",gameId).eq("status","lobby");if(up.error)throw up.error;return{started:true,letter,endsAt}}
export async function submitNameFamily(familyId:string,userId:number,gameId:string,answers:Record<string,unknown>){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status,public_state").eq("id",gameId).eq("family_id",familyId).eq("game_type","name_family").single();if(g.error)throw g.error;if(g.data.status!=="active")throw new Error("name_family_not_active");const joined=await s.from("multiplayer_players").select("member_id").eq("game_id",gameId).eq("member_id",m.id).maybeSingle();if(joined.error)throw joined.error;if(!joined.data)throw new Error("name_family_join_required");const endsAt=String((g.data.public_state as any)?.endsAt||"");if(endsAt&&new Date(endsAt).getTime()+5000<Date.now())throw new Error("name_family_time_up");const clean:Object=Object.fromEntries(CATEGORIES.map(k=>[k,normalize(answers[k])]).filter(([,v])=>Boolean(v)));const up=await s.from("multiplayer_answers").upsert({game_id:gameId,member_id:m.id,answers:clean,submitted_at:new Date().toISOString()},{onConflict:"game_id,member_id"});if(up.error)throw up.error;return{submitted:true}}
export async function finishNameFamilyGame(familyId:string,userId:number,gameId:string){const s=db(),m=await me(familyId,userId);const g=await s.from("multiplayer_games").select("id,status,host_member_id,public_state").eq("id",gameId).eq("family_id",familyId).eq("game_type","name_family").single();if(g.error)throw g.error;if(g.data.host_member_id!==m.id)throw new Error("name_family_host_only");if(g.data.status!=="active")throw new Error("name_family_not_active");const locked=await s.from("multiplayer_games").update({status:"finished",finished_at:new Date().toISOString()}).eq("id",gameId).eq("status","active").select("id").maybeSingle();if(!locked.data)throw new Error("name_family_finished");const answers=await s.from("multiplayer_answers").select("member_id,answers").eq("game_id",gameId);if(answers.error)throw answers.error;const letter=String((g.data.public_state as any)?.letter||"");const rows=answers.data||[];const scored=rows.map(row=>{let score=0;for(const category of CATEGORIES){const value=normalize((row.answers as any)?.[category]);if(!value||!startsWithLetter(value,letter))continue;const same=rows.filter(r=>normalize((r.answers as any)?.[category])===value).length;score+=same>1?5:10}return{member_id:row.member_id,score}});for(const row of scored){const u=await s.from("multiplayer_answers").update({score:row.score}).eq("game_id",gameId).eq("member_id",row.member_id);if(u.error)throw u.error;if(row.score>0){const reward=Math.min(60,Math.max(5,Math.floor(row.score/10)*5));const bal=await s.rpc("family_add_member_coins",{p_member_id:row.member_id,p_delta:reward});if(bal.error)throw bal.error;await s.from("coin_ledger").insert({family_id:familyId,member_id:row.member_id,amount:reward,reason:"name_family_score",reference_type:"multiplayer_game",reference_id:gameId})}}return{finished:true,letter,scores:scored.sort((a,b)=>b.score-a.score)}}
export async function readNameFamilyGames(familyId:string,userId:number){const s=db(),m=await me(familyId,userId);const games=await s.from("multiplayer_games").select("id,status,host_member_id,public_state,created_at,started_at,finished_at").eq("family_id",familyId).eq("game_type","name_family").order("created_at",{ascending:false}).limit(12);if(games.error)throw games.error;const ids=(games.data||[]).map(g=>g.id);if(!ids.length)return{me:m,games:[]};const [players,answers]=await Promise.all([s.from("multiplayer_players").select("game_id,member_id,members!multiplayer_players_member_id_fkey(display_name,first_name)").in("game_id",ids),s.from("multiplayer_answers").select("game_id,member_id,answers,score,submitted_at").in("game_id",ids)]);if(players.error)throw players.error;if(answers.error)throw answers.error;return{me:m,games:(games.data||[]).map(g=>{const ps=(players.data||[]).filter(p=>p.game_id===g.id),mine=(answers.data||[]).find(a=>a.game_id===g.id&&a.member_id===m.id);return{...g,players:ps.map(p=>({member_id:p.member_id,name:(p.members as any)?.display_name||(p.members as any)?.first_name||"عضو"})),joined:ps.some(p=>p.member_id===m.id),isHost:g.host_member_id===m.id,mySubmission:mine||null,scoreboard:g.status==="finished"?(answers.data||[]).filter(a=>a.game_id===g.id).map(a=>({member_id:a.member_id,score:a.score})).sort((a,b)=>b.score-a.score):[]}})}}
