import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";

function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Family Core database is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function me(familyId:string,userId:number){const r=await db().from("members").select("id,display_name,first_name").eq("family_id",familyId).eq("bale_user_id",userId).single();if(r.error)throw r.error;return r.data}
function derange<T>(items:T[]){if(items.length<2)throw new Error("secret_gift_requires_two_members");const out=[...items];for(let i=out.length-1;i>0;i--){const j=crypto.randomInt(0,i);[out[i],out[j]]=[out[j],out[i]]}return out}
export async function createSecretGift(familyId:string,userId:number,input:{title?:string;eventDate?:string|null;budgetNote?:string;memberIds?:string[]}){const s=db();const creator=await me(familyId,userId);const title=String(input.title||"").trim().slice(0,160);if(!title)throw new Error("secret_gift_title_required");let q=s.from("members").select("id").eq("family_id",familyId);if(input.memberIds?.length)q=q.in("id",input.memberIds);const members=await q;if(members.error)throw members.error;const ids=(members.data||[]).map(x=>x.id);if(ids.length<2)throw new Error("secret_gift_requires_two_members");const targets=derange(ids);const event=await s.from("secret_gift_events").insert({family_id:familyId,creator_member_id:creator.id,title,event_date:input.eventDate||null,budget_note:String(input.budgetNote||"").trim().slice(0,300)||null,status:"drawn"}).select("id,title,event_date,budget_note,status,created_at").single();if(event.error)throw event.error;const assignments=ids.map((giver,i)=>({event_id:event.data.id,giver_member_id:giver,target_member_id:targets[i]}));const ins=await s.from("secret_gift_assignments").insert(assignments);if(ins.error){await s.from("secret_gift_events").delete().eq("id",event.data.id);throw ins.error}return event.data}
export async function readSecretGifts(familyId:string,userId:number){const s=db();const member=await me(familyId,userId);const events=await s.from("secret_gift_events").select("id,title,event_date,budget_note,status,created_at").eq("family_id",familyId).order("created_at",{ascending:false}).limit(20);if(events.error)throw events.error;const ids=(events.data||[]).map(x=>x.id);if(!ids.length)return{events:[],assignments:[]};const own=await s.from("secret_gift_assignments").select("event_id,target_member_id,revealed_at").eq("giver_member_id",member.id).in("event_id",ids);if(own.error)throw own.error;const targetIds=[...new Set((own.data||[]).map(x=>x.target_member_id))];const targets=targetIds.length?await s.from("members").select("id,display_name,first_name").in("id",targetIds):{data:[],error:null};if(targets.error)throw targets.error;const names=new Map((targets.data||[]).map(x=>[x.id,x.display_name||x.first_name||"عضو خانواده"]));return{events:events.data||[],assignments:(own.data||[]).map(x=>({...x,target_name:names.get(x.target_member_id)||"عضو خانواده"}))}}
export async function revealSecretGift(familyId:string,userId:number,eventId:string){const s=db();const member=await me(familyId,userId);const event=await s.from("secret_gift_events").select("id,status").eq("id",eventId).eq("family_id",familyId).single();if(event.error)throw event.error;if(event.data.status!=="drawn")throw new Error("secret_gift_closed");const a=await s.from("secret_gift_assignments").update({revealed_at:new Date().toISOString()}).eq("event_id",eventId).eq("giver_member_id",member.id).select("target_member_id,revealed_at").single();if(a.error)throw a.error;const target=await s.from("members").select("display_name,first_name").eq("id",a.data.target_member_id).single();if(target.error)throw target.error;return{targetName:target.data.display_name||target.data.first_name||"عضو خانواده",revealedAt:a.data.revealed_at}}
