/** Maps every catalog item to a painted JAHANI store icon. */
export const STORE_ART_KEYS = [
  "galaxy_sofa",
  "family_cinema",
  "cosmic_library",
  "golden_family_tree",
  "star_pool",
  "sagool_crown",
  "sagool_royal_staff",
  "sagool_sleep_pod",
  "cosmic_wings",
  "cosmic_clock",
  "crystal_lantern",
  "nebula_plant",
  "cosmic_chandelier",
  "cosmic_aquarium",
  "nebula_fireplace",
  "sagool_food",
  "sagool_collar",
  "hero_frame",
  "light_fountain",
  "tea_table",
  "trophy_cabinet",
  "sagool_bone",
  "sagool_ball",
  "sagool_hoverboard",
  "sagool_armor",
  "sagool_cape",
  "cosmic_badge",
] as const;

export type StoreArtKey = (typeof STORE_ART_KEYS)[number];

const ITEM_ART: Record<string, StoreArtKey> = {
  galaxy_sofa: "galaxy_sofa",
  cosmic_clock: "cosmic_clock",
  light_fountain: "light_fountain",
  crystal_lantern: "crystal_lantern",
  nebula_plant: "nebula_plant",
  home_theater: "family_cinema",
  memory_bench: "tea_table",
  moon_clock: "cosmic_clock",
  star_pool: "star_pool",
  family_cinema: "family_cinema",
  cosmic_chandelier: "cosmic_chandelier",
  trophy_cabinet: "trophy_cabinet",
  nebula_wardrobe: "trophy_cabinet",
  tea_table: "tea_table",
  family_photo_frame: "hero_frame",
  cosmic_music_box: "cosmic_chandelier",
  water_fountain: "light_fountain",
  sagool_dog_house: "sagool_sleep_pod",
  toy_chest: "sagool_bone",
  pet_corner: "sagool_sleep_pod",
  cosmic_aquarium: "cosmic_aquarium",
  nebula_fireplace: "nebula_fireplace",
  family_observatory: "cosmic_library",
  royal_room: "golden_family_tree",
  garden_gate: "light_fountain",
  sky_window: "cosmic_clock",
  cosmic_library: "cosmic_library",
  star_rug: "nebula_plant",
  golden_family_tree: "golden_family_tree",
  memory_wall: "hero_frame",
  sagool_food: "sagool_food",
  sagool_royal_food: "sagool_food",
  sagool_water: "cosmic_aquarium",
  sagool_hydration_station: "cosmic_aquarium",
  sagool_bone: "sagool_bone",
  sagool_bone_pro: "sagool_bone",
  sagool_ball: "sagool_ball",
  sagool_robo_disc: "sagool_hoverboard",
  sagool_bed: "sagool_sleep_pod",
  sagool_bed_royal: "sagool_sleep_pod",
  sagool_sleep_pod: "sagool_sleep_pod",
  sagool_shampoo: "crystal_lantern",
  sagool_smart_feeder: "sagool_food",
  sagool_collar: "sagool_collar",
  sagool_sector_collar: "sagool_collar",
  sagool_walk_harness: "sagool_collar",
  sagool_glasses: "sagool_crown",
  sagool_outfit: "sagool_cape",
  sagool_cape: "sagool_cape",
  sagool_armor: "sagool_armor",
  sagool_crown: "sagool_crown",
  sagool_guardian: "sagool_armor",
  sagool_toy_pack: "sagool_ball",
  sagool_sleep_pack: "sagool_sleep_pod",
  sagool_training_beacon: "sagool_hoverboard",
  sagool_pet_showcase: "trophy_cabinet",
  sagool_house: "sagool_sleep_pod",
  sagool_grooming_kit: "crystal_lantern",
  sagool_affection_charm: "sagool_collar",
  sagool_legend_aura: "cosmic_wings",
  hero_frame: "hero_frame",
  cosmic_badge: "cosmic_badge",
  legend_glow: "cosmic_wings",
  guardian_frame: "hero_frame",
  star_nameplate: "cosmic_badge",
  founder_cosmos: "cosmic_wings",
  royal_cosmic_throne: "sagool_crown",
  quantum_home_portal: "cosmic_wings",
  galaxy_grand_piano: "family_cinema",
  sagool_quantum_armor: "sagool_armor",
  sagool_hoverboard: "sagool_hoverboard",
  sagool_royal_staff: "sagool_royal_staff",
  sovereign_frame: "hero_frame",
  aurora_nameplate: "cosmic_badge",
  cosmic_wings: "cosmic_wings",
  mat_brick: "tea_table",
  mat_cement: "tea_table",
  mat_wood: "nebula_plant",
  mat_water: "light_fountain",
  mat_tile: "crystal_lantern",
  mat_paint: "nebula_plant",
};

export function storeArtKey(itemId: string): StoreArtKey {
  return ITEM_ART[itemId] ?? "galaxy_sofa";
}

export function storeArtSrc(itemId: string): string {
  if(itemId.startsWith("mat_")){
    const key=itemId.slice(4);
    return `/assets/house/materials/${key}.jpg`;
  }
  return `/assets/store/items/${storeArtKey(itemId)}.jpg`;
}
