export type StoreKind="house"|"profile"|"sagool"|"material";
export type StoreRarity="common"|"rare"|"epic"|"legendary";
export type StoreItem={id:string;name:string;price:number;kind:StoreKind;sprite:number;description:string;rarity:StoreRarity;stackable?:boolean;material?:string;packQty?:number};

export const STORE_ITEMS:StoreItem[]=[
{id:"mat_brick",name:"بسته آجر",price:180,kind:"material",sprite:4,description:"۸ آجر برای ارتقای خانه",rarity:"common",stackable:true,material:"brick",packQty:8},
{id:"mat_cement",name:"بسته سیمان",price:220,kind:"material",sprite:4,description:"۶ کیسه سیمان",rarity:"common",stackable:true,material:"cement",packQty:6},
{id:"mat_wood",name:"بسته چوب",price:200,kind:"material",sprite:4,description:"۶ الوار مرغوب",rarity:"common",stackable:true,material:"wood",packQty:6},
{id:"mat_water",name:"آب ساخت",price:90,kind:"material",sprite:6,description:"۸ واحد آب ساخت‌وساز",rarity:"common",stackable:true,material:"water",packQty:8},
{id:"mat_tile",name:"بسته کاشی",price:320,kind:"material",sprite:7,description:"۴ کاشی پرمیوم",rarity:"rare",stackable:true,material:"tile",packQty:4},
{id:"mat_paint",name:"رنگ کیهانی",price:280,kind:"material",sprite:7,description:"۳ قوطی رنگ JAHANI",rarity:"rare",stackable:true,material:"paint",packQty:3},
{id:"galaxy_sofa",name:"مبل کهکشانی",price:7500,kind:"house",sprite:4,description:"مبل لوکس بنفش برای سالن خانه",rarity:"common"},
{id:"cosmic_clock",name:"ساعت کیهانی",price:9200,kind:"house",sprite:5,description:"ساعت تزئینی آینده‌نگر",rarity:"common"},
{id:"light_fountain",name:"فواره پنجه نور",price:39000,kind:"house",sprite:6,description:"فواره نئونی برای حیاط",rarity:"rare"},
{id:"crystal_lantern",name:"فانوس کریستالی",price:42000,kind:"house",sprite:7,description:"چراغ کریستالی با هاله کهکشانی",rarity:"rare"},
{id:"nebula_plant",name:"گلدان سحابی",price:44000,kind:"house",sprite:8,description:"گیاه نئونی برای فضای خانه",rarity:"rare"},
{id:"home_theater",name:"سینمای جهانی",price:85000,kind:"house",sprite:9,description:"سینمای خانگی آینده‌نگر",rarity:"epic"},
{id:"memory_bench",name:"نیمکت خاطره",price:48000,kind:"house",sprite:4,description:"گوشه‌ای آرام برای خاطره‌های خانواده",rarity:"rare"},
{id:"moon_clock",name:"ساعت ماه",price:91000,kind:"house",sprite:5,description:"نسخه ویژه ساعت با تم ماه",rarity:"epic"},
{id:"star_pool",name:"استخر ستاره",price:125000,kind:"house",sprite:6,description:"استخر نورانی با بازتاب ستاره‌ها",rarity:"legendary"},
{id:"family_cinema",name:"سینمای خانواده",price:158000,kind:"house",sprite:9,description:"سینمای افسانه‌ای Family House",rarity:"legendary"},
{id:"cosmic_chandelier",name:"لوستر کیهانی",price:98000,kind:"house",sprite:7,description:"لوستر طلایی-بنفش برای تالار خانه",rarity:"epic"},
{id:"trophy_cabinet",name:"ویترین افتخارات",price:107000,kind:"house",sprite:9,description:"نمایش جام‌ها و دستاوردهای خانواده",rarity:"epic"},
{id:"nebula_wardrobe",name:"کمد سحابی",price:52000,kind:"house",sprite:4,description:"کمد مدرن با نور نئونی",rarity:"rare"},
{id:"tea_table",name:"میز چای خانوادگی",price:10800,kind:"house",sprite:4,description:"میز کوچک برای دورهمی‌های خانوادگی",rarity:"common"},
{id:"family_photo_frame",name:"قاب عکس خانواده",price:12500,kind:"house",sprite:5,description:"قاب نورانی برای گوشه خاطرات",rarity:"common"},
{id:"cosmic_music_box",name:"جعبه موسیقی کیهانی",price:118000,kind:"house",sprite:7,description:"دکور موزیکال با هاله ستاره‌ای",rarity:"epic"},
{id:"water_fountain",name:"آبنمای کریستالی",price:128000,kind:"house",sprite:6,description:"آبنمای آرامش‌بخش برای محوطه خانه",rarity:"epic"},
{id:"sagool_dog_house",name:"خانه اختصاصی سگول",price:138000,kind:"house",sprite:8,description:"گوشه امن و گرم برای سگول",rarity:"epic"},
{id:"toy_chest",name:"صندوق اسباب‌بازی",price:58000,kind:"house",sprite:8,description:"محل نگهداری اسباب‌بازی‌های سگول",rarity:"rare"},
{id:"pet_corner",name:"گوشه حیوان خانگی",price:62000,kind:"house",sprite:8,description:"فضای کامل استراحت و بازی سگول",rarity:"rare"},
{id:"cosmic_aquarium",name:"آکواریوم کیهانی",price:169000,kind:"house",sprite:6,description:"آکواریوم نورانی با حس اقیانوس فضایی",rarity:"legendary"},
{id:"nebula_fireplace",name:"شومینه سحابی",price:148000,kind:"house",sprite:7,description:"شومینه گرم با شعله‌های نئونی",rarity:"epic"},
{id:"family_observatory",name:"رصدخانه خانوادگی",price:188000,kind:"house",sprite:9,description:"تماشای آسمان از خانه جهانی",rarity:"legendary"},
{id:"royal_room",name:"اتاق رویال",price:225000,kind:"house",sprite:9,description:"ارتقای افسانه‌ای فضای خانه",rarity:"legendary"},
{id:"garden_gate",name:"دروازه باغ ستاره‌ای",price:160000,kind:"house",sprite:6,description:"ورودی نئونی باغ خانواده",rarity:"epic"},
{id:"sky_window",name:"پنجره آسمان",price:68000,kind:"house",sprite:5,description:"پنجره‌ای با نمای آسمان بنفش",rarity:"rare"},
{id:"cosmic_library",name:"کتابخانه جهانی",price:248000,kind:"house",sprite:9,description:"کتابخانه باشکوه برای Family House",rarity:"legendary"},
{id:"star_rug",name:"فرش ستاره‌ای",price:14800,kind:"house",sprite:4,description:"فرش نرم با طرح صورت‌های فلکی",rarity:"common"},
{id:"golden_family_tree",name:"درخت طلایی خانواده",price:275000,kind:"house",sprite:8,description:"نماد افسانه‌ای پیوند اعضای خانواده",rarity:"legendary"},
{id:"memory_wall",name:"دیوار خاطرات",price:172000,kind:"house",sprite:5,description:"نمایشگاه کوچک برای لحظه‌های خانوادگی",rarity:"epic"},
{id:"sagool_food",name:"غذای انرژی",price:450000,kind:"sagool",sprite:0,description:"یک وعده خوشمزه برای سگول",rarity:"common"},
{id:"sagool_royal_food",name:"غذای رویال",price:980000,kind:"sagool",sprite:0,description:"وعده ویژه برای سگول‌های سطح بالا",rarity:"rare"},
{id:"sagool_water",name:"ظرف آب نئونی",price:620000,kind:"sagool",sprite:0,description:"ظرف آب مخصوص سگول",rarity:"common"},
{id:"sagool_hydration_station",name:"ایستگاه آب هوشمند",price:1250000,kind:"sagool",sprite:0,description:"آبخوری پیشرفته با نور وضعیت",rarity:"epic"},
{id:"sagool_bone",name:"استخوان کهکشانی",price:780000,kind:"sagool",sprite:1,description:"اسباب‌بازی جویدنی نورانی",rarity:"common"},
{id:"sagool_bone_pro",name:"Toy Bone سکتور",price:1180000,kind:"sagool",sprite:1,description:"استخوان حرفه‌ای برای بازی بیشتر",rarity:"rare"},
{id:"sagool_ball",name:"توپ پلاسما",price:890000,kind:"sagool",sprite:1,description:"توپ نورانی برای بازی و تحرک",rarity:"common"},
{id:"sagool_robo_disc",name:"Robo Disc",price:1550000,kind:"sagool",sprite:1,description:"دیسک رباتیک برای تمرین واکنش",rarity:"epic"},
{id:"sagool_bed",name:"Pet Bed ابری",price:1350000,kind:"sagool",sprite:2,description:"خواب راحت و انرژی بیشتر",rarity:"rare"},
{id:"sagool_bed_royal",name:"تخت رویال",price:2250000,kind:"sagool",sprite:2,description:"تخت لوکس سگول برای مراحل بالا",rarity:"epic"},
{id:"sagool_sleep_pod",name:"کپسول خواب",price:2450000,kind:"sagool",sprite:2,description:"استراحت افسانه‌ای با طراحی فضایی",rarity:"legendary"},
{id:"sagool_shampoo",name:"شامپو کریستالی",price:902000,kind:"sagool",sprite:0,description:"تمیزی و بوی خوب برای سگول",rarity:"common"},
{id:"sagool_smart_feeder",name:"Smart Feeder",price:2280000,kind:"sagool",sprite:0,description:"غذاخوری هوشمند با طراحی JAHANI",rarity:"epic"},
{id:"sagool_collar",name:"قلاده نئونی",price:1580000,kind:"sagool",sprite:3,description:"قلاده اختصاصی با آویز نورانی",rarity:"rare"},
{id:"sagool_sector_collar",name:"قلاده سکتور",price:3250000,kind:"sagool",sprite:3,description:"استایل اختصاصی Sector",rarity:"epic"},
{id:"sagool_walk_harness",name:"هارنس پیاده‌روی",price:1860000,kind:"sagool",sprite:3,description:"قلاده ایمن برای ماجراجویی بیرون",rarity:"rare"},
{id:"sagool_glasses",name:"عینک نئونی",price:1980000,kind:"sagool",sprite:3,description:"عینک آینده‌نگر برای استایل سگول",rarity:"rare"},
{id:"sagool_outfit",name:"لباس JAHANI",price:3650000,kind:"sagool",sprite:3,description:"لباس رسمی بنفش و طلایی",rarity:"epic"},
{id:"sagool_cape",name:"شنل قهرمان",price:3662000,kind:"sagool",sprite:3,description:"شنل مخصوص سگول‌های شجاع",rarity:"epic"},
{id:"sagool_armor",name:"زره نگهبان",price:2850000,kind:"sagool",sprite:3,description:"زره افسانه‌ای مرحله نگهبان",rarity:"legendary"},
{id:"sagool_crown",name:"تاج جهانی",price:3950000,kind:"sagool",sprite:3,description:"برای سگول‌های سطح بالا",rarity:"legendary"},
{id:"sagool_guardian",name:"نشان نگهبان",price:4250000,kind:"sagool",sprite:3,description:"آیتم افسانه‌ای مرحله نگهبان",rarity:"legendary"},
{id:"sagool_toy_pack",name:"پک بازی سگول",price:3674000,kind:"sagool",sprite:1,description:"پک ویژه سرگرمی و تمرین",rarity:"epic"},
{id:"sagool_sleep_pack",name:"پک خواب آرام",price:3686000,kind:"sagool",sprite:2,description:"پک مخصوص استراحت سگول",rarity:"epic"},
{id:"sagool_training_beacon",name:"Training Beacon",price:3698000,kind:"sagool",sprite:1,description:"ابزار هوشمند برای تمرین‌های سگول",rarity:"epic"},
{id:"sagool_pet_showcase",name:"Pet Showcase",price:4650000,kind:"sagool",sprite:3,description:"استیج نمایش افسانه‌ای سگول",rarity:"legendary"},
{id:"sagool_house",name:"Dog House فضایی",price:3710000,kind:"sagool",sprite:2,description:"خانه شخصی سگول با طراحی کیهانی",rarity:"epic"},
{id:"sagool_grooming_kit",name:"پک نظافت حرفه‌ای",price:1992000,kind:"sagool",sprite:0,description:"پک حمام و مراقبت روزانه",rarity:"rare"},
{id:"sagool_affection_charm",name:"آویز دوستی",price:3722000,kind:"sagool",sprite:3,description:"نماد پیوند و صمیمیت با سگول",rarity:"epic"},
{id:"sagool_legend_aura",name:"هاله افسانه‌ای سگول",price:4850000,kind:"sagool",sprite:3,description:"هاله ستاره‌ای مخصوص مرحله افسانه‌ای",rarity:"legendary"},
{id:"hero_frame",name:"فریم قهرمان",price:88000,kind:"profile",sprite:3,description:"قاب ویژه پروفایل",rarity:"rare"},
{id:"cosmic_badge",name:"نشان جهانی",price:138000,kind:"profile",sprite:5,description:"نشان پروفایل خانواده جهانی",rarity:"epic"},
{id:"legend_glow",name:"هاله افسانه‌ای",price:198000,kind:"profile",sprite:7,description:"هاله ویژه اطراف آواتار",rarity:"legendary"},
{id:"guardian_frame",name:"فریم نگهبان",price:158000,kind:"profile",sprite:3,description:"قاب بنفش و طلایی سطح بالا",rarity:"epic"},
{id:"star_nameplate",name:"نیم‌تگ ستاره‌ای",price:98000,kind:"profile",sprite:5,description:"پلاک نام با درخشش ستاره",rarity:"rare"},
{id:"founder_cosmos",name:"Cosmos Showcase",price:228000,kind:"profile",sprite:7,description:"نمایش افسانه‌ای پروفایل JAHANI",rarity:"legendary"},
{id:"royal_cosmic_throne",name:"تخت سلطنتی جهانی",price:345000,kind:"house",sprite:9,description:"تخت سلطنتی طلایی-کهکشانی برای تالار اصلی",rarity:"legendary"},
{id:"quantum_home_portal",name:"دروازه کوانتومی خانه",price:420000,kind:"house",sprite:9,description:"پرتال نورانی افسانه‌ای برای دکور سطح نهایی",rarity:"legendary"},
{id:"galaxy_grand_piano",name:"پیانوی بزرگ کهکشانی",price:385000,kind:"house",sprite:9,description:"پیانوی لوکس با هاله ستاره‌ای و نور پویا",rarity:"legendary"},
{id:"sagool_quantum_armor",name:"زره کوانتومی سگول",price:5750000,kind:"sagool",sprite:3,description:"زره نهایی نگهبان با انرژی کوانتومی",rarity:"legendary"},
{id:"sagool_hoverboard",name:"هاوربرد ستاره‌ای سگول",price:4450000,kind:"sagool",sprite:1,description:"وسیله بازی و حرکت افسانه‌ای در جهان JAHANI",rarity:"legendary"},
{id:"sagool_royal_staff",name:"عصای سلطنتی سگول",price:6250000,kind:"sagool",sprite:3,description:"آیتم End-game با گوی پنجه کیهانی",rarity:"legendary"},
{id:"sovereign_frame",name:"فریم فرمانروای جهانی",price:348000,kind:"profile",sprite:7,description:"فریم طلایی سلطنتی ویژه پروفایل‌های سطح بالا",rarity:"legendary"},
{id:"aurora_nameplate",name:"نیم‌تگ شفق جهانی",price:218000,kind:"profile",sprite:5,description:"پلاک نام کریستالی با هاله شفق",rarity:"epic"},
{id:"cosmic_wings",name:"بال‌های کیهانی پروفایل",price:398000,kind:"profile",sprite:7,description:"جلوه افسانه‌ای بال و ستاره برای هویت پروفایل",rarity:"legendary"}
];
export const storeItem=(id:string)=>STORE_ITEMS.find(x=>x.id===id);
