"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {Icon,IconOrb,Mascot} from "../../ui";

type Player={member_id:string;name:string};
type SpyGame={id:string;status:string;players:Player[];joined:boolean;myRole?:string|null;myPrivate?:{location?:string};isHost:boolean};
type NameFamilyGame={id:string;status:string;players:Player[];joined:boolean;isHost:boolean;public_state?:{letter?:string};mySubmission?:{score?:number}|null;scoreboard:Array<{member_id:string;score:number}>};
type Question={id:string;asker_member_id:string;askerName:string;question:string;answer?:"yes"|"no"|"maybe"|null};
type TwentyGame={id:string;status:string;players:Player[];joined:boolean;isHost:boolean;public_state?:{hint?:string;questionLimit?:number;winnerMemberId?:string};questions:Question[]};
type Data={spy:SpyGame[];nameFamily:NameFamilyGame[];twenty:TwentyGame[]};
const fields=[['name','اسم'],['family','فامیل'],['city','شهر'],['food','غذا'],['animal','حیوان'],['object','اشیا']] as const;
export default function MultiplayerPage(){
  const[data,setData]=useState<Data>({spy:[],nameFamily:[],twenty:[]}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
  const load=useCallback(()=>{const s=sessionStorage.getItem("familybot.session");if(!s)return;fetch("/api/family/multiplayer",{headers:{authorization:`Bearer ${s}`},cache:"no-store"}).then(r=>r.json()).then(x=>x.ok&&setData({spy:x.data.spy||[],nameFamily:x.data.nameFamily||[],twenty:x.data.twenty||[]})).catch(()=>undefined)},[]);useEffect(()=>load(),[load]);
  async function act(action:string,gameId?:string,extra:Record<string,unknown>={}){const s=sessionStorage.getItem("familybot.session");if(!s)return setMsg("Mini App را از داخل بله باز کن.");setBusy(true);setMsg("");try{const r=await fetch("/api/family/multiplayer",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${s}`},body:JSON.stringify({action,gameId,...extra})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"multiplayer_failed");if(action==="spy.finish"&&x.data?.reveal)setMsg(`🎭 جاسوس مشخص شد · مکان: ${x.data.reveal.location}`);else if(action==="name_family.finish")setMsg("📝 امتیازهای اسم‌فامیل نهایی شد.");else if(action==="twenty.guess")setMsg(x.data?.correct?`🎉 حدس درست! +${x.data.reward} سکه`:"این حدس درست نبود.");else if(action==="twenty.finish"&&x.data?.secret)setMsg(`پایان بازی · پاسخ: ${x.data.secret}`);else setMsg("انجام شد ✨");load()}catch(e){const m=e instanceof Error?e.message:"عملیات انجام نشد";const labels:Record<string,string>={spy_needs_three_players:"حداقل ۳ نفر باید وارد لابی جاسوس بشن.",spy_host_only:"فقط میزبان جاسوس می‌تونه این کار رو انجام بده.",name_family_needs_two_players:"حداقل ۲ نفر برای اسم‌فامیل لازمه.",name_family_host_only:"فقط میزبان اسم‌فامیل می‌تونه شروع/پایان بده.",name_family_time_up:"زمان این دور تمام شده.",name_family_join_required:"اول وارد لابی اسم‌فامیل شو.",twenty_needs_two_players:"حداقل ۲ نفر برای ۲۰ سؤال لازمه.",twenty_host_only:"فقط میزبان می‌تونه این کار رو انجام بده.",twenty_question_limit:"۲۰ سؤال کامل شده؛ حالا حدس بزنید.",twenty_join_required:"اول وارد بازی ۲۰ سؤال شو."};setMsg(labels[m]||m)}finally{setBusy(false)}}
  const names=useMemo(()=>{const m=new Map<string,string>();[...data.spy,...data.nameFamily,...data.twenty].forEach(g=>g.players.forEach(p=>m.set(p.member_id,p.name)));return m},[data]);
  return <main className="appShell"><div className="ambient ambientA"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/section/games">←</a><div className="wordmark"><b>Multiplayer</b><span>بازی گروهی واقعی</span></div><IconOrb name="games" tone="violet"/></header>
    <section className="homeHero premiumPanel" style={{minHeight:210}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="games" size={15}/> Family Multiplayer</span><h1>رقابت خانوادگی 🎮</h1><p>جاسوس، اسم‌فامیل و ۲۰ سؤال با لابی واقعی.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="primaryCta" disabled={busy} onClick={()=>void act("spy.create")}>جاسوس</button><button className="primaryCta" disabled={busy} onClick={()=>void act("name_family.create")}>اسم‌فامیل</button></div><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("twenty.create",undefined,{secret:f.get("secret"),hint:f.get("hint")});e.currentTarget.reset()}} style={{display:"grid",gridTemplateColumns:"1fr 1fr auto",gap:7,marginTop:8}}><input name="secret" placeholder="پاسخ مخفی ۲۰ سؤال" required/><input name="hint" placeholder="راهنمای عمومی"/><button disabled={busy}>ساخت ۲۰ سؤال</button></form></div><Mascot small mood="thinking"/></section>{msg&&<div className="adminNotice" style={{marginTop:10}}>{msg}</div>}

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>🕵️ جاسوس</h2>{data.spy.map(g=><article className="dashboardCard" key={g.id} style={{display:"block",marginTop:8}}><h2>{g.players.length} بازیکن · {g.status}</h2><div>{g.players.map(p=><span className="levelPill" key={p.member_id}>{p.name}</span>)}</div>{g.status==="active"&&g.joined&&<div className="adminNotice">{g.myRole==="spy"?"🕵️ تو جاسوسی؛ مکان رو نمی‌دونی.":`👤 مکان: ${g.myPrivate?.location||"—"}`}</div>}<div>{g.status==="lobby"&&!g.joined&&<button onClick={()=>void act("spy.join",g.id)}>ورود</button>}{g.status==="lobby"&&g.isHost&&<button onClick={()=>void act("spy.start",g.id)}>شروع</button>}{g.status==="active"&&g.isHost&&<button onClick={()=>void act("spy.finish",g.id)}>پایان</button>}</div></article>)}</section>

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>📝 اسم‌فامیل</h2>{data.nameFamily.map(g=><article className="dashboardCard" key={g.id} style={{display:"block",marginTop:8}}><h2>{g.public_state?.letter?`حرف «${g.public_state.letter}» · `:""}{g.players.length} بازیکن · {g.status}</h2>{g.status==="lobby"&&<div>{!g.joined&&<button onClick={()=>void act("name_family.join",g.id)}>ورود</button>}{g.isHost&&<button onClick={()=>void act("name_family.start",g.id)}>شروع</button>}</div>}{g.status==="active"&&g.joined&&!g.mySubmission&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("name_family.submit",g.id,{answers:Object.fromEntries(fields.map(([k])=>[k,f.get(k)]))})}} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7}}>{fields.map(([k,l])=><input key={k} name={k} placeholder={`${l} با ${g.public_state?.letter||"حرف"}`}/>)}<button className="adminSave" style={{gridColumn:"1/-1"}}>ثبت</button></form>}{g.status==="active"&&g.isHost&&<button onClick={()=>void act("name_family.finish",g.id)}>پایان و امتیاز</button>}{g.status==="finished"&&g.scoreboard.map((r,i)=><div key={r.member_id}>{i+1}. {names.get(r.member_id)||"عضو"} — {r.score.toLocaleString("fa-IR")}</div>)}</article>)}</section>

    <section className="adminPanel premiumPanel" style={{marginTop:14,marginBottom:90}}><h2>❓ ۲۰ سؤال</h2>{data.twenty.map(g=><article className="dashboardCard" key={g.id} style={{display:"block",marginTop:8}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2>{g.public_state?.hint?`راهنما: ${g.public_state.hint}`:"بدون راهنما"}</h2><p>{g.questions.length}/۲۰ سؤال · {g.status}</p></div><span className="levelPill">{g.players.length} نفر</span></div>{g.status==="lobby"&&<div style={{display:"flex",gap:7}}>{!g.joined&&<button onClick={()=>void act("twenty.join",g.id)}>ورود</button>}{g.isHost&&<button onClick={()=>void act("twenty.start",g.id)}>شروع</button>}</div>}{g.status==="active"&&g.joined&&!g.isHost&&<><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("twenty.ask",g.id,{question:f.get("question")});e.currentTarget.reset()}} style={{display:"flex",gap:7,marginTop:8}}><input name="question" required placeholder="سؤال بله/خیر بپرس"/><button>ارسال</button></form><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("twenty.guess",g.id,{guess:f.get("guess")});e.currentTarget.reset()}} style={{display:"flex",gap:7,marginTop:8}}><input name="guess" required placeholder="حدس نهایی"/><button>حدس</button></form></>}{g.questions.map(q=><div className="adminNotice" key={q.id} style={{marginTop:7}}><b>{q.askerName}: {q.question}</b>{q.answer?<span> · {q.answer==="yes"?"بله":q.answer==="no"?"نه":"شاید"}</span>:g.isHost&&g.status==="active"?<div style={{display:"flex",gap:5,marginTop:6}}>{([['yes','بله'],['no','نه'],['maybe','شاید']] as const).map(([v,l])=><button key={v} onClick={()=>void act("twenty.answer",g.id,{questionId:q.id,answer:v})}>{l}</button>)}</div>:<span> · منتظر پاسخ میزبان</span>}</div>)}{g.isHost&&g.status==="active"&&<button style={{marginTop:8}} onClick={()=>void act("twenty.finish",g.id)}>پایان و نمایش پاسخ</button>}{g.status==="finished"&&g.public_state?.winnerMemberId&&<div className="adminNotice">🏆 برنده: {names.get(g.public_state.winnerMemberId)||"عضو خانواده"}</div>}</article>)}</section>
  </main>}
