"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {Icon,IconOrb,Mascot} from "../../ui";

type Player={member_id:string;name:string};
type SpyGame={id:string;status:string;host_member_id:string;players:Player[];joined:boolean;myRole?:string|null;myPrivate?:{location?:string};isHost:boolean};
type NameFamilyGame={id:string;status:string;host_member_id:string;players:Player[];joined:boolean;isHost:boolean;public_state?:{letter?:string;endsAt?:string;durationSeconds?:number};mySubmission?:{answers?:Record<string,string>;score?:number}|null;scoreboard:Array<{member_id:string;score:number}>};
type Data={spy:SpyGame[];nameFamily:NameFamilyGame[]};
const fields=[['name','اسم'],['family','فامیل'],['city','شهر'],['food','غذا'],['animal','حیوان'],['object','اشیا']] as const;
export default function MultiplayerPage(){
  const[data,setData]=useState<Data>({spy:[],nameFamily:[]}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
  const load=useCallback(()=>{const s=sessionStorage.getItem("familybot.session");if(!s)return;fetch("/api/family/multiplayer",{headers:{authorization:`Bearer ${s}`},cache:"no-store"}).then(r=>r.json()).then(x=>x.ok&&setData({spy:x.data.spy||[],nameFamily:x.data.nameFamily||[]})).catch(()=>undefined)},[]);useEffect(()=>load(),[load]);
  async function act(action:string,gameId?:string,extra:Record<string,unknown>={}){const s=sessionStorage.getItem("familybot.session");if(!s)return setMsg("Mini App را از داخل بله باز کن.");setBusy(true);setMsg("");try{const r=await fetch("/api/family/multiplayer",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${s}`},body:JSON.stringify({action,gameId,...extra})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"multiplayer_failed");if(action==="spy.finish"&&x.data?.reveal)setMsg(`🎭 جاسوس مشخص شد · مکان: ${x.data.reveal.location}`);else if(action==="name_family.finish")setMsg("📝 امتیازهای اسم‌فامیل نهایی و جایزه‌ها ثبت شد.");else setMsg("انجام شد ✨");load()}catch(e){const m=e instanceof Error?e.message:"عملیات انجام نشد";const labels:Record<string,string>={spy_needs_three_players:"حداقل ۳ نفر باید وارد لابی جاسوس بشن.",spy_host_only:"فقط میزبان جاسوس می‌تونه این کار رو انجام بده.",name_family_needs_two_players:"حداقل ۲ نفر برای اسم‌فامیل لازمه.",name_family_host_only:"فقط میزبان اسم‌فامیل می‌تونه شروع/پایان بده.",name_family_time_up:"زمان این دور تمام شده.",name_family_join_required:"اول وارد لابی اسم‌فامیل شو."};setMsg(labels[m]||m)}finally{setBusy(false)}}
  const names=useMemo(()=>{const m=new Map<string,string>();[...data.spy,...data.nameFamily].forEach(g=>g.players.forEach(p=>m.set(p.member_id,p.name)));return m},[data]);
  return <main className="appShell"><div className="ambient ambientA"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/section/games">←</a><div className="wordmark"><b>Multiplayer</b><span>بازی گروهی واقعی</span></div><IconOrb name="games" tone="violet"/></header>
    <section className="homeHero premiumPanel" style={{minHeight:210}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="games" size={15}/> Family Multiplayer</span><h1>رقابت خانوادگی 🎮</h1><p>جاسوس و اسم‌فامیل با لابی واقعی و اطلاعات خصوصی هر بازیکن.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="primaryCta" disabled={busy} onClick={()=>void act("spy.create")}>لابی جاسوس</button><button className="primaryCta" disabled={busy} onClick={()=>void act("name_family.create")}>لابی اسم‌فامیل</button></div></div><Mascot small mood="thinking"/></section>{msg&&<div className="adminNotice" style={{marginTop:10}}>{msg}</div>}

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>🕵️ لابی‌های جاسوس</h2><div style={{display:"grid",gap:10}}>{data.spy.length?data.spy.map(g=><article className="dashboardCard" key={g.id} style={{display:"block"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><h2>بازی جاسوس</h2><p>{g.players.length} بازیکن · {g.status==="lobby"?"در انتظار شروع":g.status==="active"?"در حال بازی":"تمام‌شده"}</p></div><span className="levelPill">{g.status}</span></div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:10}}>{g.players.map(p=><span className="levelPill" key={p.member_id}>{p.name}</span>)}</div>{g.status==="active"&&g.joined&&<div className="adminNotice" style={{marginTop:10}}>{g.myRole==="spy"?"🕵️ تو جاسوسی؛ مکان رو نمی‌دونی.":`👤 تو عضو عادی هستی · مکان: ${g.myPrivate?.location||"—"}`}</div>}<div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}>{g.status==="lobby"&&!g.joined&&<button disabled={busy} onClick={()=>void act("spy.join",g.id)}>ورود</button>}{g.status==="lobby"&&g.isHost&&<button disabled={busy} onClick={()=>void act("spy.start",g.id)}>شروع</button>}{g.status==="active"&&g.isHost&&<button disabled={busy} onClick={()=>void act("spy.finish",g.id)}>پایان و Reveal</button>}</div></article>):<div className="adminNotice">هنوز لابی جاسوس نیست.</div>}</div></section>

    <section className="adminPanel premiumPanel" style={{marginTop:14,marginBottom:90}}><h2>📝 اسم‌فامیل</h2><div style={{display:"grid",gap:10}}>{data.nameFamily.length?data.nameFamily.map(g=><article className="dashboardCard" key={g.id} style={{display:"block"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><h2>اسم‌فامیل {g.public_state?.letter?`با «${g.public_state.letter}»`:""}</h2><p>{g.players.length} بازیکن · {g.status==="lobby"?"لابی":g.status==="active"?"۹۰ ثانیه برای پاسخ":"پایان‌یافته"}</p></div><span className="levelPill">{g.status}</span></div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8}}>{g.players.map(p=><span className="levelPill" key={p.member_id}>{p.name}</span>)}</div>{g.status==="lobby"&&<div style={{display:"flex",gap:8,marginTop:10}}>{!g.joined&&<button disabled={busy} onClick={()=>void act("name_family.join",g.id)}>ورود به لابی</button>}{g.isHost&&<button disabled={busy} onClick={()=>void act("name_family.start",g.id)}>شروع با حرف تصادفی</button>}</div>}{g.status==="active"&&g.joined&&!g.mySubmission&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const answers=Object.fromEntries(fields.map(([key])=>[key,f.get(key)]));void act("name_family.submit",g.id,{answers})}} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}>{fields.map(([key,label])=><input key={key} name={key} placeholder={`${label} با ${g.public_state?.letter||"حرف"}`}/>) }<button className="adminSave" style={{gridColumn:"1/-1"}} disabled={busy}>ثبت جواب‌ها</button></form>}{g.status==="active"&&g.mySubmission&&<div className="adminNotice" style={{marginTop:10}}>✅ جواب‌های تو ثبت شده؛ منتظر پایان دور باش.</div>}{g.status==="active"&&g.isHost&&<button style={{marginTop:10}} disabled={busy} onClick={()=>void act("name_family.finish",g.id)}>پایان دور و امتیازدهی</button>}{g.status==="finished"&&g.scoreboard?.length>0&&<div style={{display:"grid",gap:6,marginTop:10}}>{g.scoreboard.map((r,i)=><div className="dashboardCard" key={r.member_id}><span className="levelPill">#{i+1}</span><div><h2>{names.get(r.member_id)||"عضو"}</h2><p>{r.score.toLocaleString("fa-IR")} امتیاز</p></div></div>)}</div>}</article>):<div className="adminNotice">هنوز لابی اسم‌فامیل نیست.</div>}</div></section>
  </main>}
