"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import FamilyActions from "../../FamilyActions";
import { Icon, IconName, IconOrb, Mascot } from "../../ui";

type Member={id:string;bale_user_id:number;display_name?:string|null;first_name?:string|null;relation_label?:string|null;avatar_url?:string|null;xp:number;coins:number;level:number};
type Relationship={id:string;from_member_id:string;to_member_id:string;relation_type:string};
type Dashboard={
  family:{name:string;level:number;xp:number;coins:number;houseLevel:number;membersCount:number;upcomingEventsCount:number;upcomingBirthdaysCount:number;memoriesCount:number;levelProgress:{current:number;target:number}};
  profile:null|{display_name?:string|null;first_name?:string|null;relation_label?:string|null;bio?:string|null;birthday?:string|null;avatar_url?:string|null;xp:number;coins:number;level:number;streak:number;rank?:number|null;is_founder?:boolean};
  members:Member[];leaderboard:Member[];
  birthdays:Array<{display_name?:string|null;first_name?:string|null;birthday:string;days:number;next:string}>;
  tasks:Array<{id:string;title:string;status:string;due_at?:string|null;reward_coins:number}>;
  events:Array<{id:string;title:string;event_type:string;starts_at:string}>;
  relationships:Relationship[];ownedItems:Array<{id:string;item_id:string;item_name:string;item_kind:string}>;
};
const empty:Dashboard={family:{name:"خانواده ما",level:1,xp:0,coins:0,houseLevel:1,membersCount:0,upcomingEventsCount:0,upcomingBirthdaysCount:0,memoriesCount:0,levelProgress:{current:0,target:500}},profile:null,members:[],leaderboard:[],birthdays:[],tasks:[],events:[],relationships:[],ownedItems:[]};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0);const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("fa-IR",{timeZone:"Asia/Tehran",month:"long",day:"numeric"}):"بدون تاریخ";
function MemberAvatar({member,size=46}:{member:Member,size?:number}){return <span style={{width:size,height:size,borderRadius:15,overflow:"hidden",display:"grid",placeItems:"center",background:"rgba(255,255,255,.06)",border:"1px solid rgba(255,255,255,.1)",flex:"0 0 auto"}}>{member.avatar_url?<img src={member.avatar_url} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<Icon name="profile" size={22}/>}</span>}
function Shell({title,icon,children}:{title:string;icon:IconName;children:React.ReactNode}){return <main className="appShell"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/">←</a><div className="wordmark"><b style={{fontSize:22}}>{title}</b><span>Family Bot · داده زنده</span></div><span className="profileAvatar"><Icon name={icon}/></span></header>{children}<nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav></main>}
function EmptyNote(){return <div className="adminNotice" style={{marginTop:12}}>هنوز داده‌ای ثبت نشده؛ اطلاعاتی که از ربات و Mini App ثبت کنی اینجا نمایش داده می‌شن.</div>}

export default function LiveSection({slug}:{slug:string}){
  const [d,setD]=useState<Dashboard>(empty),[live,setLive]=useState(false);
  const load=useCallback(()=>{const session=sessionStorage.getItem("familybot.session");if(!session)return;fetch("/api/family/dashboard",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.ok&&x.dashboard){setD({...empty,...x.dashboard,members:x.dashboard.members||[],relationships:x.dashboard.relationships||[],ownedItems:x.dashboard.ownedItems||[]});setLive(true)}}).catch(()=>undefined)},[]);useEffect(()=>load(),[load]);
  const progress=useMemo(()=>Math.max(0,Math.min(100,Math.round(d.family.levelProgress.current/Math.max(1,d.family.levelProgress.target)*100))),[d]);
  const names=useMemo(()=>new Map(d.members.map(m=>[m.id,m.display_name||m.first_name||"عضو خانواده"])),[d.members]);

  if(slug==="family")return <Shell title="خانواده" icon="family"><section className="homeHero premiumPanel" style={{minHeight:245}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="family" size={15}/> {live?"همگام با Family Core":"در انتظار ورود امن"}</span><h1>{d.family.name}</h1><p>{fa(d.family.membersCount)} عضو در این خانواده</p><div className="heroStats"><div><Icon name="birthday"/><b>{fa(d.family.upcomingBirthdaysCount)}</b><span>تولد نزدیک</span></div><div><Icon name="calendar"/><b>{fa(d.family.upcomingEventsCount)}</b><span>رویداد</span></div><div><Icon name="memories"/><b>{fa(d.family.memoriesCount)}</b><span>خاطره</span></div></div></div><Mascot/></section><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>اعضای خانواده</h2>{d.members.length?<div className="dashboardGrid">{d.members.slice(0,12).map(m=><article className="dashboardCard" key={m.id}><MemberAvatar member={m}/><div><h2>{m.display_name||m.first_name||"عضو"}</h2><p>{m.relation_label||`Lv.${fa(m.level)}`}</p></div></article>)}</div>:<EmptyNote/>}</section><section className="adminPanel premiumPanel" style={{marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow"><Icon name="tree" size={14}/> Family Tree</span><h2>شجره‌نامه زنده</h2></div><span className="levelPill">{fa(d.relationships.length)} رابطه</span></div>{d.relationships.length?<div style={{display:"grid",gap:9,marginTop:10}}>{d.relationships.map(r=><div key={r.id} className="dashboardCard" style={{gridTemplateColumns:"1fr auto 1fr",alignItems:"center",textAlign:"center"}}><b>{names.get(r.from_member_id)||"عضو"}</b><span style={{fontSize:11,color:"#c4b5fd"}}>── {r.relation_type} ──</span><b>{names.get(r.to_member_id)||"عضو"}</b></div>)}</div>:<EmptyNote/>}<a className="primaryCta" href="/section/tree" style={{marginTop:12}}>باز کردن شجره‌نامه حرفه‌ای ←</a></section></Shell>;

  if(slug==="occasions")return <Shell title="تولدها و مناسبت‌ها" icon="birthday"><section className="homeHero premiumPanel" style={{minHeight:220}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="birthday" size={15}/> Birthday Mode</span><h1>{fa(d.family.upcomingBirthdaysCount)} تولد نزدیک</h1><p>یادآوری خودکار برای لحظه‌های مهم خانواده</p></div><Mascot small mood="love"/></section><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>تولدهای بعدی</h2>{d.birthdays.length?<div style={{display:"grid",gap:10}}>{d.birthdays.map((b,i)=><article className="dashboardCard" key={`${b.birthday}-${i}`}><IconOrb name="birthday" tone={i===0?"pink":"violet"}/><div><h2>{b.display_name||b.first_name||"عضو خانواده"}</h2><p>{b.days===0?"امروز 🎉":`${fa(b.days)} روز دیگر`} · {date(b.next)}</p></div></article>)}</div>:<EmptyNote/>}</section><FamilyActions mode="profile" onChanged={load}/></Shell>;

  if(slug==="tasks")return <Shell title="کارها و یادآورها" icon="tasks"><section className="homeHero premiumPanel" style={{minHeight:215}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="tasks" size={15}/> برنامه مشترک</span><h1>{fa(d.tasks.length)} کار باز</h1><p>کارهای خانواده، مهلت و پاداش‌ها در یکجا</p></div><Mascot small mood="thinking"/></section><section className="adminPanel premiumPanel" style={{marginTop:14}}>{d.tasks.length?<div style={{display:"grid",gap:10}}>{d.tasks.map(t=><article className="dashboardCard" key={t.id}><IconOrb name={t.status==="doing"?"spark":"tasks"} tone={t.status==="doing"?"violet":"cyan"}/><div><h2>{t.title}</h2><p>{t.status==="doing"?"در حال انجام":"باز"} · {date(t.due_at)}{t.reward_coins?` · ${fa(t.reward_coins)} سکه`:""}</p></div></article>)}</div>:<EmptyNote/>}</section><FamilyActions mode="tasks" tasks={d.tasks} onChanged={load}/></Shell>;

  if(slug==="leaderboard")return <Shell title="پروفایل و رتبه‌بندی" icon="trophy"><section className="homeHero premiumPanel" style={{minHeight:235}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="trophy" size={15}/> Family Ranking</span><h1>{d.profile?.display_name||d.profile?.first_name||"پروفایل من"}</h1><p>Level {fa(d.profile?.level||1)} · {d.profile?.is_founder?"∞":fa(d.profile?.xp||0)} XP · {d.profile?.is_founder?"∞":fa(d.profile?.coins||0)} سکه</p><div className="heroStats"><div><Icon name="trophy"/><b>{d.profile?.is_founder?"FOUNDER":d.profile?.rank?fa(d.profile.rank):"—"}</b><span>رتبه</span></div><div><Icon name="spark"/><b>{fa(d.profile?.streak||0)}</b><span>Streak</span></div><div><Icon name="coins"/><b>{d.profile?.is_founder?"∞":fa(d.profile?.coins||0)}</b><span>سکه</span></div></div></div>{d.profile?.avatar_url?<div className="mascotVisual"><span className="mascotHalo"/><img src={d.profile.avatar_url} alt="پروفایل من" style={{width:150,height:150,objectFit:"cover",borderRadius:42}}/><span className="mascotShadow"/></div>:<Mascot/>}</section><FamilyActions mode="profile" onChanged={load}/><section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>برترین اعضا</h2>{d.leaderboard.length?<div style={{display:"grid",gap:8}}>{d.leaderboard.slice(0,5).map((r,i)=><article className="dashboardCard" key={r.bale_user_id}><span className="levelPill">#{fa(i+1)}</span><MemberAvatar member={r}/><div><h2>{r.display_name||r.first_name||"عضو خانواده"}</h2><p>Lv.{fa(r.level)} · {fa(r.xp)} XP · {fa(r.coins)} سکه</p></div></article>)}</div>:<EmptyNote/>}</section></Shell>;

  if(slug==="house")return <Shell title="Family House" icon="home"><section className="housePreview premiumPanel" style={{marginTop:8}}><div className="sectionHeading"><div><span className="eyebrow"><Icon name="home" size={15}/> خانه مشترک خانواده</span><h2>{d.family.name}</h2></div><span className="levelPill">LV. {fa(d.family.houseLevel)}</span></div><div className="houseStage"><div className="moonGlow"/><div className="treeBlob left"/><div className="treeBlob right"/><div className="houseArt"><span className="roofArt"/><span className="chimney"/><span className="bodyArt"><i className="window w1"/><i className="window w2"/><i className="door"/></span></div><Mascot small mood="celebrate"/></div><div className="houseProgress"><span><b>{fa(d.family.levelProgress.current)}</b> / {fa(d.family.levelProgress.target)} XP</span><i><em style={{width:`${progress}%`}}/></i></div></section><section className="dashboardGrid" style={{marginTop:14}}><article className="dashboardCard"><IconOrb name="family" tone="violet"/><div><h2>{fa(d.family.membersCount)} عضو</h2><p>هر فعالیت به رشد خانه کمک می‌کند</p></div></article><article className="dashboardCard"><IconOrb name="store" tone="gold"/><div><h2>{fa(d.ownedItems.length)} آیتم خریداری‌شده</h2><p><a href="/section/store">رفتن به فروشگاه ←</a></p></div></article></section></Shell>;
  return null;
}
