"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Icon, Mascot, type MascotMood } from "../ui";

type ChatMessage={role:"user"|"assistant";content:string};
type SpeechRecognitionLike={lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((event:any)=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null};
const quick=[["calendar","ثبت برنامه با AI","دورهمی شام جمعه ساعت ۲۰ ثبت کن"],["birthday","تولدهای نزدیک","تولدهای نزدیک رو بهم بگو"],["poll","ساخت نظرسنجی","نظرسنجی شام کجا باشه گزینه‌ها: خونه، رستوران بساز"],["coins","هدیه با فرمان","به سارا ۲۰ سکه بده"]] as const;

export default function AiPage(){
  const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",content:"سلام! من Family AI هستم. هر چیزی برای خانواده لازم داری، تایپ کن یا با صدات بگو 💜"}]);
  const [input,setInput]=useState("");const [voiceDraft,setVoiceDraft]=useState("");const [listening,setListening]=useState(false);const [busy,setBusy]=useState(false);const [speaking,setSpeaking]=useState(false);const [toast,setToast]=useState("");
  const recognitionRef=useRef<SpeechRecognitionLike|null>(null);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const audioRef=useRef<HTMLAudioElement|null>(null);const audioUrlRef=useRef<string|null>(null);
  const speechSupported=useMemo(()=>typeof window!=="undefined"&&Boolean((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition),[]);
  function showToast(text:string){setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(""),2200)}
  function stopAudio(){audioRef.current?.pause();audioRef.current=null;if(audioUrlRef.current){URL.revokeObjectURL(audioUrlRef.current);audioUrlRef.current=null}if(typeof window!=="undefined")window.speechSynthesis?.cancel();setSpeaking(false)}
  function browserSpeak(text:string){if(typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="fa-IR";u.rate=.98;u.pitch=1;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)}
  async function speak(text:string){if(typeof window==="undefined")return;stopAudio();try{const r=await fetch("/api/voice/tts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw new Error("voice_fallback");const blob=await r.blob();const url=URL.createObjectURL(blob);audioUrlRef.current=url;const audio=new Audio(url);audioRef.current=audio;audio.onplay=()=>setSpeaking(true);audio.onended=()=>{setSpeaking(false);URL.revokeObjectURL(url);if(audioUrlRef.current===url)audioUrlRef.current=null;audioRef.current=null};audio.onerror=()=>{setSpeaking(false);browserSpeak(text)};await audio.play()}catch{browserSpeak(text)}}
  async function submit(e?:FormEvent,forced?:string){e?.preventDefault();const value=(forced??input).trim();if(!value||busy)return;setMessages(c=>[...c,{role:"user",content:value}]);setInput("");setBusy(true);try{const session=sessionStorage.getItem("familybot.session");const response=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json",...(session?{authorization:`Bearer ${session}`}:{})},body:JSON.stringify({message:value,history:messages.slice(-12)})});const data=await response.json();const reply=data.reply||"فعلاً نتونستم پاسخ بدم؛ دوباره امتحان کن 💜";setMessages(c=>[...c,{role:"assistant",content:reply}]);if(data.action)showToast("اکشن در Family Core ثبت شد ✨");void speak(reply)}catch{showToast("ارتباط با Family AI برقرار نشد")}finally{setBusy(false)}}
  useEffect(()=>{if(!speechSupported)return;const SpeechRecognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;const r:SpeechRecognitionLike=new SpeechRecognition();r.lang="fa-IR";r.interimResults=false;r.continuous=false;r.onresult=(e:any)=>{const text=String(e.results?.[0]?.[0]?.transcript??"").trim();if(text){setInput(text);setVoiceDraft(text);showToast("صدات رو گرفتم؛ دارم اجرا می‌کنم ✨")}};r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);showToast("دوباره امتحان کن؛ صدات کامل دریافت نشد")};recognitionRef.current=r;return()=>{r.stop();stopAudio()}},[speechSupported]);
  useEffect(()=>{if(!voiceDraft||busy)return;const text=voiceDraft;setVoiceDraft("");void submit(undefined,text)},[voiceDraft,busy]);
  function toggleListening(){const r=recognitionRef.current;if(!r){showToast("تشخیص گفتار روی این مرورگر آماده نیست");return}if(listening){r.stop();setListening(false)}else{stopAudio();setListening(true);r.start()}}
  const mood:MascotMood=listening?"listening":busy?"thinking":speaking?"speaking":"idle";const status=listening?"در حال گوش دادن":busy?"در حال اجرا":speaking?"در حال پاسخ دادن":"آماده گفتگو";const waveClass=listening?"active":busy?"thinking":speaking?"speaking":"";
  return <main className="appShell aiScreen"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/><div className={`motionToast${toast?" show":""}`}>{toast}</div><header className="aiTop"><a className="roundButton" href="/">←</a><div className="aiTitle"><h1>هوش مصنوعی خانواده <span style={{color:"#ff6fae"}}>♥</span></h1><p>دستیار متصل به Family Core</p></div><span className="profileAvatar"><Icon name="ai"/></span></header><section className={`aiStage premiumPanel${listening?" isListening":busy?" isThinking":speaking?" isSpeaking":""}`}><div className="listeningBubble"><b>{status}</b>{listening?"صحبت کن؛ بعد از پایان خودکار ارسال می‌شه":busy?"فرمانت رو بررسی و اجرا می‌کنم":speaking?"پاسخ رو با صدای Family Bot می‌خونم":"لمس کن و مستقیم فرمان بده"}</div><Mascot mood={mood}/><span className={`voiceStatus ${mood}`}><i/>{status}</span><h2>{listening?"گوش می‌دم...":busy?"دارم انجامش می‌دم...":speaking?"اینم نتیجه":"با من حرف بزن"}</h2><p>ElevenLabs روی سرور اولویت داره و اگر در دسترس نباشه صدای مرورگر جایگزین می‌شه 💜</p><div className={`voiceWave ${waveClass}`}><i/><i/><i/><i/><i/><i/></div><div className="voiceActions"><button className="speakerCircle" onClick={()=>messages.filter(m=>m.role==="assistant").slice(-1).forEach(m=>void speak(m.content))} aria-label="خواندن آخرین پاسخ"><span>◖))</span></button><button className={`voiceCircle${listening?" listening":""}`} onClick={toggleListening} aria-label={listening?"توقف گوش دادن":"شروع فرمان صوتی"}><span style={{color:"#5b2cf6",fontSize:28}}>⌁</span></button></div>{!speechSupported&&<p style={{marginTop:12,color:"#ff9dbf"}}>مرورگر فعلی STT داخلی نداره؛ تایپ همچنان فعاله و TTS سروری مستقل کار می‌کنه.</p>}</section><section className="chatList">{messages.slice(-5).map((m,i)=><div className={`chatBubble ${m.role}`} key={i}>{m.content}{m.role==="assistant"&&<button onClick={()=>void speak(m.content)} aria-label="خواندن پاسخ">◖))</button>}</div>)}</section><div className="quickTitle"><h3>فرمان‌های سریع ✨</h3><span style={{fontSize:11,color:"#8f85a9"}}>{busy?"در حال اجرا...":"آنلاین"}</span></div><div className="quickGrid">{quick.map(([icon,label,prompt])=><button className="quickCard" key={label} onClick={()=>submit(undefined,prompt)}><span><Icon name={icon}/></span><b>{label}</b></button>)}</div><form className="composer" onSubmit={e=>submit(e)}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="مثلاً: به سارا ۲۰ سکه بده"/><button className="sendBtn" disabled={busy} aria-label="ارسال">←</button></form></main>
}
