import Link from "next/link";
import {Icon,IconOrb,Mascot} from "../../ui";

const guides=[
  {icon:"🕵️",title:"جاسوس",players:"۳ نفر به بالا",steps:["یک نفر لابی را می‌سازد و بقیه وارد می‌شوند.","با شروع بازی، یک نفر مخفیانه جاسوس می‌شود؛ بقیه مکان مشترک را می‌بینند.","بازیکن‌ها با سؤال‌های غیرمستقیم سعی می‌کنند جاسوس را پیدا کنند؛ جاسوس هم باید مکان را حدس بزند.","میزبان در پایان بازی نقش‌ها و مکان را آشکار می‌کند."],tip:"اسم مکان را مستقیم در سؤال نگو؛ سؤال خوب باید اطلاعات بدهد ولی جواب را لو ندهد."},
  {icon:"📝",title:"اسم‌فامیل",players:"۲ نفر به بالا",steps:["میزبان لابی می‌سازد و بعد از ورود بازیکن‌ها شروع می‌کند.","ربات یک حرف فارسی تصادفی می‌دهد و تایمر ۹۰ ثانیه‌ای شروع می‌شود.","اسم، فامیل، شهر، غذا، حیوان و اشیا را با همان حرف پر کن.","پاسخ درست و یکتا ۱۰ امتیاز و پاسخ تکراری ۵ امتیاز می‌گیرد؛ در پایان بر اساس امتیاز Family Coin داده می‌شود."],tip:"اول خانه‌هایی را پر کن که جوابشان سخت‌تر است؛ جواب خالی امتیاز ندارد."},
  {icon:"❓",title:"۲۰ سؤال",players:"۲ نفر به بالا",steps:["میزبان یک پاسخ مخفی و در صورت تمایل یک راهنمای عمومی می‌نویسد.","بازیکن‌ها حداکثر ۲۰ سؤال می‌پرسند و میزبان فقط «بله»، «نه» یا «شاید» جواب می‌دهد.","هر بازیکن می‌تواند هر زمان حدس نهایی بزند.","اولین حدس درست بازی را می‌بندد و ۳۰ Family Coin جایزه می‌گیرد."],tip:"از سؤال‌های کلی شروع کن: زنده است؟ مکان است؟ قابل حمل است؟ بعد دایره جواب را کوچک کن."},
  {icon:"🎭",title:"مافیا Lite",players:"۴ نفر به بالا",steps:["میزبان لابی می‌سازد؛ با ۴ نفر یا بیشتر بازی قابل شروع است.","نقش هر نفر خصوصی است: مافیا یا شهروند. در گروه‌های بزرگ‌تر تعداد مافیا بیشتر می‌شود.","بازیکن‌های زنده در هر دور به یک نفر رأی می‌دهند؛ میزبان رأی‌گیری را می‌بندد و فرد منتخب حذف می‌شود.","اگر همه مافیا حذف شوند شهر می‌برد؛ اگر تعداد مافیا به تعداد شهروندهای زنده برسد مافیا برنده است."],tip:"نقشت را لو نده. رفتار، رأی و تناقض حرف‌ها مهم‌تر از حدس تصادفی است."},
  {icon:"⚔️",title:"دوئل خانوادگی",players:"دقیقاً ۲ نفر",steps:["یک عضو، نفر مقابل را انتخاب و دوئل را ایجاد می‌کند.","هر دو بدون دیدن انتخاب طرف مقابل سنگ، کاغذ یا قیچی را می‌زنند.","وقتی هر دو انتخاب ثبت شد، نتیجه سمت سرور محاسبه می‌شود.","برنده Family Coin واقعی دریافت می‌کند."],tip:"انتخاب‌ها تا پایان دست مخفی می‌مانند؛ نتیجه با قوانین استاندارد سنگ، کاغذ، قیچی محاسبه می‌شود."},
];

export default function GameGuidePage(){return <main className="appShell"><div className="ambient ambientA"/><div className="starField"/><header className="appHeader"><Link className="roundButton" href="/section/games">←</Link><div className="wordmark"><b>راهنمای بازی‌ها</b><span>قانون، روش بازی و نکته‌ها</span></div><IconOrb name="games" tone="violet"/></header><section className="homeHero premiumPanel" style={{minHeight:210,marginBottom:14}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="games" size={15}/> Game Academy</span><h1>قبل از شروع، حرفه‌ای شو 🎮</h1><p>قوانین بازی‌های گروهی Family Bot اینجا کوتاه و مرحله‌به‌مرحله توضیح داده شده.</p><Link className="primaryCta" href="/section/games">رفتن به مرکز بازی ←</Link></div><Mascot small mood="thinking"/></section><section style={{display:"grid",gap:12,marginBottom:100}}>{guides.map(g=><article className="premiumPanel" key={g.title} style={{padding:18}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{width:52,height:52,borderRadius:17,display:"grid",placeItems:"center",fontSize:28,background:"linear-gradient(145deg,#7658ff,#bc3bd6)",boxShadow:"0 10px 28px #6f4aff40"}}>{g.icon}</span><div><h2 style={{margin:0,fontSize:18}}>{g.title}</h2><p style={{margin:"3px 0 0",fontSize:10,color:"#b7aacb"}}>{g.players}</p></div></div><span className="levelPill">راهنما</span></div><ol style={{display:"grid",gap:9,paddingRight:20,margin:"16px 0",fontSize:11,lineHeight:1.9,color:"#e7ddf5"}}>{g.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><div className="adminNotice" style={{margin:0}}>💡 {g.tip}</div></article>)}</section><nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a className="active" href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav></main>}
