"use client";
import {useState} from "react";
import {Icon,IconOrb,Mascot} from "../../ui";

type Kind="joke"|"fact"|"riddle"|"truth"|"dare"|"question"|"motivation"|"hafez";
const items:Array<{kind:Kind;title:string;icon:string;desc:string}>=[
  {kind:"joke",title:"جوک",icon:"😄",desc:"یه چیزی برای خندیدن"},{kind:"fact",title:"فکت",icon:"💡",desc:"دانستنی کوتاه"},{kind:"riddle",title:"چیستان",icon:"🧩",desc:"جوابش رو حدس بزن"},{kind:"truth",title:"حقیقت",icon:"👀",desc:"سؤال صادقانه"},{kind:"dare",title:"جرأت",icon:"🔥",desc:"چالش بامزه"},{kind:"question",title:"سؤال روز",icon:"💬",desc:"بحث خانوادگی"},{kind:"motivation",title:"انگیزشی",icon:"✨",desc:"یک تلنگر خوب"},{kind:"hafez",title:"فال حافظ",icon:"📖",desc:"یک بیت و حال خوب"},
];
export default function FunPage(){const[text,setText]=useState("یکی از گزینه‌ها رو انتخاب کن 💜"),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false);async function get(kind:Kind){const session=sessionStorage.getItem("familybot.session");if(!session)return setText("Mini App را از داخل بله باز کن.");setBusy(true);setAnswer("");try{const r=await fetch("/api/family/fun",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({type:kind})});const x=await r.json();if(!r.ok||!x.ok)throw new Error();setText(x.data.text);if(x.data.answer)setAnswer(x.data.answer)}catch{setText("فعلاً محتوا آماده نشد؛ دوباره امتحان کن.")}finally{setBusy(false)}}return <main className="appShell"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/><header className="appHeader"><a href="/" className="roundButton">←</a><div className="wordmark"><b>سرگرمی خانواده</b><span>Family Fun</span></div><IconOrb name="gift" tone="pink"/></header><section className="homeHero premiumPanel" style={{minHeight:220}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="spark" size={15}/> حال خوب خانوادگی</span><h1>یه چیزی برای خنده و گفتگو 😄</h1><p>جوک، چیستان، حقیقت یا جرأت، سؤال روز و فال حافظ.</p></div><Mascot small mood="celebrate"/></section><section className="adminPanel premiumPanel" style={{marginTop:14,minHeight:150,display:"grid",placeItems:"center",textAlign:"center"}}><div><p style={{fontSize:17,lineHeight:2,whiteSpace:"pre-line"}}>{text}</p>{answer&&<details><summary style={{cursor:"pointer"}}>نمایش جواب چیستان</summary><b style={{display:"block",marginTop:8,color:"#ffd36a"}}>{answer}</b></details>}</div></section><section className="dashboardGrid" style={{marginTop:14,marginBottom:90}}>{items.map(i=><button className="dashboardCard" disabled={busy} key={i.kind} onClick={()=>void get(i.kind)} style={{textAlign:"right",width:"100%"}}><span style={{fontSize:30}}>{i.icon}</span><div><h2>{i.title}</h2><p>{i.desc}</p></div><span className="cardArrow">←</span></button>)}</section><nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav></main>}
