"use client";
import {useEffect,useMemo,useState} from "react";
import {Icon,IconOrb} from "../../ui";
import SpriteAsset from "../../SpriteAsset";
import {SagoolMission,SagoolState,sagoolAdvice,stageFor} from "@/lib/sagoolCatalog";
const fallback:SagoolState={stage:"puppy",level:1,xp:0,hunger:72,thirst:70,energy:80,hygiene:76,happiness:78,affection:50,health:100};
const bars:[keyof Pick<SagoolState,"hunger"|"thirst"|"energy"|"hygiene"|"happiness"|"affection">,string][]=[["hunger","غذا"],["thirst","آب"],["energy","انرژی"],["hygiene","تمیزی"],["happiness","شادی"],["affection","صمیمیت"]];
const actions=[{id:"feed",title:"غذا",sprite:0},{id:"water",title:"آب",sprite:0},{id:"play",title:"بازی",sprite:1},{id:"sleep",title:"خواب",sprite:2},{id:"clean",title:"حمام",sprite:6},{id:"pet",title:"نوازش",sprite:3},{id:"walk",title:"پیاده‌روی",sprite:1},{id:"train",title:"آموزش",sprite:3}];
function feedback(success=true){try{navigator.vibrate?.(success?[18,25,18]:[50]);const W=window as any,C=W.AudioContext||W.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.value=success?660:180;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.07,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.17)}catch{}}
export default function SagoolPage(){const[state,setState]=useState(fallback),[missions,setMissions]=useState<SagoolMission[]>([]),[founder,setFounder]=useState(false),[busy,setBusy]=useState(""),[note,setNote]=useState("");const stage=useMemo(()=>stageFor(state.level),[state.level]);async function load(){const s=sessionStorage.getItem("familybot.session");if(!s)return;try{const r=await fetch("/api/family/sagool",{headers:{authorization:`Bearer ${s}`},cache:"no-store"}),x=await r.json();if(x.ok&&x.data){setState(x.data.state);setMissions(x.data.missions||[]);setFounder(Boolean(x.data.founder))}}catch{}}useEffect(()=>{void load()},[]);async function care(action:string){const s=sessionStorage.getItem("familybot.session");if(!s)return setNote("Mini App را از داخل بله باز کن.");setBusy(action);try{feedback(true);const r=await fetch("/api/family/sagool",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${s}`},body:JSON.stringify({type:"interact",action})}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"failed");setState(x.data.state);setMissions(x.data.missions||[]);setFounder(Boolean(x.data.founder));setNote(x.data.message||"سگول خوشحال شد ✨")}catch{feedback(false);setNote("این کار فعلاً انجام نشد؛ دوباره امتحان کن.")}finally{setBusy("")}}async function claim(m:SagoolMission){const s=sessionStorage.getItem("familybot.session");if(!s)return;setBusy(m.code);try{const r=await fetch("/api/family/sagool",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${s}`},body:JSON.stringify({type:"claim_mission",missionKey:m.code})}),x=await r.json();if(!r.ok||!x.ok)throw new Error();setState(x.data.state);setMissions(x.data.missions||[]);const c=x.data.claim||{};setNote(c.alreadyClaimed?"این جایزه قبلاً دریافت شده.":c.claimed?`جایزه دریافت شد: +${c.xp||0} XP${founder?" · Founder ∞":` · +${c.coins||0} سکه`}`:"هنوز ماموریت کامل نشده.");feedback(Boolean(c.claimed))}catch{feedback(false);setNote("دریافت جایزه انجام نشد.")}finally{setBusy("")}}
return <main className="appShell sagoolPage"><div className="ambient ambientA"/><div className="starField"/><header className="appHeader"><a href="/" className="roundButton">←</a><div className="wordmark"><b>سگول</b><span>همراه کوچولوی خانواده</span></div><IconOrb name="spark" tone="cyan"/></header><section className="premiumPanel sagoolHero"><div className="sagoolStage"><div className="sagoolAura"/><img src={stage.asset} alt={`سگول - ${stage.title}`}/><span className="levelPill">LV. {state.level} · {stage.title}</span></div><div className="sagoolAdvice"><span className="eyebrow">پیشنهاد سگول</span><h1>{sagoolAdvice(state)}</h1><p>با رسیدگی روزانه، سگول بزرگ‌تر می‌شود و در سطح‌های ۵، ۱۲، ۲۰ و ۳۰ ظاهر تازه می‌گیرد.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><span className="levelPill">XP {state.xp}</span><span className="levelPill">سلامت {state.health}٪</span>{founder&&<span className="levelPill">Founder · ∞</span>}</div></div></section><section className="premiumPanel sagoolNeeds"><h2>حال سگول</h2><div className="needGrid">{bars.map(([k,t])=><div className="need" key={k}><span>{t}</span><b>{state[k]}٪</b><i><em style={{width:`${state[k]}%`}}/></i></div>)}</div></section><section className="sagoolActions">{actions.map(a=><button disabled={Boolean(busy)} onClick={()=>void care(a.id)} key={a.id}><SpriteAsset atlas="store" index={a.sprite} size={54}/><b>{busy===a.id?"...":a.title}</b></button>)}</section>{note&&<div className="motionToast show">{note}</div>}<section className="premiumPanel sagoolMissions"><div className="sectionHeading"><div><span className="eyebrow">همه ماموریت‌ها انفرادی‌اند</span><h2>ماموریت‌های سگول</h2></div><Icon name="tasks"/></div>{missions.map(m=><article key={m.code} style={{alignItems:"center"}}><div><span>{m.cadence==="weekly"?"هفتگی · ":"روزانه · "}{m.title}</span><small style={{display:"block",opacity:.65,marginTop:4}}>{m.progress}/{m.target} · +{m.rewardXp} XP · +{m.rewardCoins} 🪙</small></div><button className="primaryCta" style={{width:"auto",minWidth:82,padding:"8px 10px"}} disabled={!m.complete||m.claimed||Boolean(busy)} onClick={()=>void claim(m)}>{m.claimed?"گرفته شد":m.complete?"دریافت":"در حال انجام"}</button></article>)}</section><a href="/section/store?tab=sagool" className="primaryCta sagoolShopLink">فروشگاه گرافیکی سگول ←</a></main>}
