"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { Icon,IconOrb,Mascot } from "../../ui";

type Member={id:string;display_name?:string|null;first_name?:string|null};
type Expense={id:string;title:string;amount:number;spent_at:string;payer_member_id:string;expense_splits:Array<{member_id:string;share_amount:number;settled:boolean}>};
type Shopping={id:string;title:string;quantity?:string|null;done:boolean;assigned_member_id?:string|null};
type Data={me:{id:string};members:Member[];expenses:Expense[];shopping:Shopping[];summary:{owedByMe:number;owedToMe:number;balance:number}};
const empty:Data={me:{id:""},members:[],expenses:[],shopping:[],summary:{owedByMe:0,owedToMe:0,balance:0}};const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0);

export default function FinancePage(){
  const[d,setD]=useState<Data>(empty),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");const[participants,setParticipants]=useState<string[]>([]);
  const load=useCallback(()=>{const session=sessionStorage.getItem("familybot.session");if(!session)return;fetch("/api/family/finance",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.ok)setD(x.data)}).catch(()=>undefined)},[]);useEffect(()=>load(),[load]);
  async function act(action:string,payload:Record<string,unknown>){const session=sessionStorage.getItem("familybot.session");if(!session){setMsg("Mini App را از داخل بله باز کن.");return}setBusy(true);setMsg("");try{const r=await fetch("/api/family/finance",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,payload})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"finance_action_failed");setMsg("با موفقیت ثبت شد ✨");load()}catch(e){setMsg(e instanceof Error?e.message:"ثبت انجام نشد")}finally{setBusy(false)}}
  const names=useMemo(()=>new Map(d.members.map(m=>[m.id,m.display_name||m.first_name||"عضو خانواده"])),[d.members]);
  return <main className="appShell"><div className="ambient ambientA"/><div className="ambient ambientB"/><div className="starField"/><header className="appHeader"><a className="roundButton" href="/">←</a><div className="wordmark"><b>حساب خانواده</b><span>Finance Lite · بدون پرداخت واقعی</span></div><span className="profileAvatar"><Icon name="coins"/></span></header>
    <section className="homeHero premiumPanel" style={{minHeight:220}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="coins" size={15}/> حساب مشترک</span><h1>هزینه‌ها و خریدها</h1><p>فقط ثبت و تقسیم هزینه؛ هیچ پرداخت بانکی انجام نمی‌شه.</p><div className="heroStats"><div><Icon name="coins"/><b>{fa(d.summary.owedToMe)}</b><span>طلب من</span></div><div><Icon name="reminder"/><b>{fa(d.summary.owedByMe)}</b><span>بدهی من</span></div><div><Icon name="spark"/><b>{fa(d.summary.balance)}</b><span>مانده</span></div></div></div><Mascot small mood="thinking"/></section>{msg&&<div className="adminNotice" style={{marginTop:10}}>{msg}</div>}
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>ثبت هزینه و Split Bill</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("expense.create",{title:f.get("title"),amount:Number(f.get("amount")||0),category:f.get("category"),notes:f.get("notes"),participantMemberIds:participants.length?participants:[d.me.id]});e.currentTarget.reset();setParticipants([])}} style={{display:"grid",gap:9}}><input name="title" placeholder="مثلاً شام خانوادگی" required/><input name="amount" type="number" min="1" placeholder="مبلغ" required/><input name="category" placeholder="دسته‌بندی؛ غذا، سفر، خرید..."/><textarea name="notes" rows={2} placeholder="توضیح اختیاری"/><div style={{display:"grid",gap:6}}><b style={{fontSize:12}}>بین چه کسانی تقسیم شود؟</b>{d.members.map(m=><label key={m.id} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={participants.includes(m.id)} onChange={e=>setParticipants(p=>e.target.checked?[...p,m.id]:p.filter(x=>x!==m.id))}/><span>{m.display_name||m.first_name||"عضو"}</span></label>)}</div><button className="adminSave" disabled={busy}>ثبت هزینه</button></form></section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>هزینه‌های اخیر</h2>{d.expenses.length?<div style={{display:"grid",gap:8}}>{d.expenses.map(e=>{const mine=e.expense_splits.find(s=>s.member_id===d.me.id);return <article className="dashboardCard" key={e.id}><IconOrb name="coins" tone="gold"/><div><h2>{e.title}</h2><p>{fa(e.amount)} · پرداخت‌کننده: {names.get(e.payer_member_id)||"عضو"}</p>{mine&&<p>سهم من: {fa(mine.share_amount)} · {mine.settled?"تسویه شده":"تسویه نشده"}</p>}</div>{mine&&!mine.settled&&e.payer_member_id!==d.me.id&&<button disabled={busy} onClick={()=>void act("expense.settle",{expenseId:e.id})}>تسویه شد</button>}</article>})}</div>:<div className="adminNotice">هنوز هزینه‌ای ثبت نشده.</div>}</section>
    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>لیست خرید خانواده</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("shopping.add",{title:f.get("title"),quantity:f.get("quantity"),assignedMemberId:f.get("assigned")||null});e.currentTarget.reset()}} style={{display:"grid",gap:8}}><input name="title" placeholder="چی باید بخریم؟" required/><input name="quantity" placeholder="تعداد / مقدار"/><select name="assigned" defaultValue=""><option value="">مسئول مشخص نشده</option>{d.members.map(m=><option key={m.id} value={m.id}>{m.display_name||m.first_name||"عضو"}</option>)}</select><button className="adminSave" disabled={busy}>افزودن به لیست خرید</button></form><div style={{display:"grid",gap:8,marginTop:10}}>{d.shopping.map(i=><button className="dashboardCard" key={i.id} disabled={busy} onClick={()=>void act("shopping.toggle",{itemId:i.id,done:!i.done})} style={{width:"100%",textAlign:"right",opacity:i.done?.6:1}}><Icon name={i.done?"spark":"tasks"}/><div><h2>{i.done?"✓ ":""}{i.title}</h2><p>{i.quantity||"بدون مقدار"}{i.assigned_member_id?` · ${names.get(i.assigned_member_id)||"عضو"}`:""}</p></div></button>)}</div></section>
    <nav className="bottomNav"><a href="/"><Icon name="home"/><span>خانه</span></a><a href="/section/family"><Icon name="family"/><span>خانواده</span></a><a href="/section/games"><Icon name="games"/><span>بازی‌ها</span></a><a href="/ai"><Icon name="ai"/><span>AI</span></a><a href="/section/leaderboard"><Icon name="profile"/><span>پروفایل</span></a></nav>
  </main>
}
