"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
import {Icon,Mascot} from "../../ui";
import AssetSprite from "../../AssetSprite";
import {STORE_ITEMS,StoreItem} from "@/lib/storeCatalog";
import styles from "./house.module.css";

type HouseData={family:{name:string;xp:number;houseLevel:number;levelProgress:{current:number;target:number}};profile?:{coins?:number|null;is_founder?:boolean|null}|null;ownedItems?:Array<{item_id:string}>};
const fallback:HouseData={family:{name:"خانواده ما",xp:0,houseLevel:1,levelProgress:{current:0,target:500}},profile:{coins:0,is_founder:false},ownedItems:[]};
const houseItems=STORE_ITEMS.filter(x=>x.kind==="house"&&typeof x.sprite==="number");
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0);
const rarityLabel=(r:StoreItem["rarity"])=>r==="legendary"?"افسانه‌ای":r==="epic"?"حماسی":r==="rare"?"کمیاب":"معمولی";
async function familyAction(action:string,payload:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("Mini App رو از داخل ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||"action_failed");return d.data}

export default function HousePage(){
  const[selected,setSelected]=useState<StoreItem>(houseItems[0]),[toast,setToast]=useState(""),[levelBurst,setLevelBurst]=useState(false),[data,setData]=useState<HouseData>(fallback);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  function notify(text:string){setToast(text);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(""),2200)}
  async function refresh(){const session=sessionStorage.getItem("familybot.session");if(!session)return;try{const r=await fetch("/api/family/dashboard",{headers:{authorization:`Bearer ${session}`},cache:"no-store"});const d=await r.json();if(d.ok&&d.dashboard)setData(d.dashboard)}catch{notify("دریافت اطلاعات خانه ممکن نشد")}}
  useEffect(()=>{void refresh()},[]);
  async function buy(){try{const result=await familyAction("store.purchase",{itemId:selected.id});notify(result.alreadyOwned?"این آیتم رو قبلاً داری 💜":data.profile?.is_founder?`${selected.name} برای Founder فعال شد ✨`:`${selected.name} خریداری شد ✨`);setLevelBurst(!result.alreadyOwned);setTimeout(()=>setLevelBurst(false),1400);void refresh()}catch(e){const m=e instanceof Error?e.message:"خرید انجام نشد";notify(m.includes("insufficient_coins")?"سکه کافی نداری 🪙":m)}}
  async function claimReward(){try{const result=await familyAction("mission.claim",{missionId:"daily_task"});notify(result.alreadyClaimed?"پاداش امروز قبلاً دریافت شده.":`+${result.reward} سکه دریافت شد ✨`);setLevelBurst(!result.alreadyClaimed);setTimeout(()=>setLevelBurst(false),1500);void refresh()}catch(e){const m=e instanceof Error?e.message:"پاداش آماده نیست";notify(m==="mission_not_complete"?"اول مأموریت امروز رو کامل کن 💜":m)}}
  const owned=useMemo(()=>new Set((data.ownedItems||[]).map(x=>x.item_id)),[data.ownedItems]),progress=Math.max(0,Math.min(100,Math.round(data.family.levelProgress.current/Math.max(1,data.family.levelProgress.target)*100))),founder=Boolean(data.profile?.is_founder),coins=founder?"∞":fa(Number(data.profile?.coins||0));
  return <main className={styles.page}><div className={`motionToast${toast?" show":""}`}>{toast}</div><div className={`levelBurst${levelBurst?" show":""}`}><div className="levelBurstCore"><div><b>✨</b><span>Family House به‌روز شد</span></div></div></div>
    <header className={styles.header}><Link href="/" className={styles.back}>←</Link><div><b>Family House</b><span>{data.family.name}</span></div><span className={styles.bot}><Mascot small mood={levelBurst?"celebrate":"love"}/></span></header>
    <section className={styles.stats}><div><span className={styles.statIcon}><Icon name="spark"/></span><p>سطح خانه</p><b>Lv. {fa(data.family.houseLevel)}</b><i><em style={{width:`${progress}%`}}/></i></div><div><span className={styles.coin}>●</span><p>Family Coin</p><b>{coins}</b></div><div><span className={styles.statIcon}><Icon name="trophy"/></span><p>XP خانواده</p><b>{founder?"∞":fa(data.family.xp)}</b></div></section>
    <section className={styles.sceneCard}><div className={styles.sceneTitle}><div><p>خانه خانواده</p><span>سطح {fa(data.family.houseLevel)} · {fa(owned.size)} آیتم فعال</span></div><span className={styles.score}>{founder?"∞":fa(data.family.xp)}<br/><small>مجموع XP</small></span></div><div className={styles.sky}><i className={styles.starA}/><i className={styles.starB}/><i className={styles.starC}/></div><div className={styles.land}><span className={styles.tree}/><span className={styles.bushA}/><span className={styles.bushB}/><span className={styles.fence}/><div className={styles.house}><span className={styles.chimney}/><span className={styles.roof}/><span className={styles.wall}><i/><i/><b>♥</b></span></div><div className={styles.pet}><Mascot small mood="love"/></div>{typeof selected.sprite==="number"&&<button className={styles.selectedDecor} onClick={()=>notify(`${selected.name} برای چیدمان انتخاب شده`)} aria-label={`قرار دادن ${selected.name}`}><AssetSprite index={selected.sprite} size={92} label={selected.name}/></button>}</div>
      <div className={styles.decorRail}>{houseItems.slice(0,8).map(item=><button key={item.id} onClick={()=>{setSelected(item);notify(`${item.name} انتخاب شد`)}} aria-pressed={selected.id===item.id} style={selected.id===item.id?{outline:"2px solid rgba(172,132,255,.8)",transform:"translateY(-3px)"}:undefined}>{typeof item.sprite==="number"&&<AssetSprite index={item.sprite} size={48} label={item.name}/>}<b>{owned.has(item.id)?"✓ فعال":rarityLabel(item.rarity)}</b></button>)}</div>
      <div className={styles.selectionBar}><span>انتخاب: <b>{selected.name}</b></span><button onClick={()=>void buy()} disabled={owned.has(selected.id)}>{owned.has(selected.id)?"فعال شده":founder?"فعال‌سازی رایگان":`خرید · ${fa(selected.price)} 🪙`}</button></div>
    </section>
    <section className={styles.challenge}><div><span>🎯 چالش امروز</span><h2>یک کار خانوادگی رو کامل کن</h2><p>پاداش واقعی Family Coin</p><i><em/></i></div><div className={styles.challengeArt}>🎯✨</div><button className={styles.reward} onClick={()=>void claimReward()}>دریافت</button></section>
    <section className={styles.dual}><article><header><h2>ماموریت‌ها و نشان‌ها</h2><span><Icon name="trophy"/></span></header><p>پیشرفت واقعی از فعالیت Family Bot</p><Link href="/section/achievements">مشاهده دستاوردها ←</Link></article><article><header><h2>کالکشن خانه</h2><span><Icon name="store"/></span></header><div className={styles.shop}>{houseItems.slice(0,6).map(item=><div key={item.id}>{typeof item.sprite==="number"&&<AssetSprite index={item.sprite} size={42} label={item.name}/>}<b>{owned.has(item.id)?"✓":founder?"∞":`${fa(item.price)} 🪙`}</b></div>)}</div><Link href="/section/store?tab=house">همه ۱۲ آیتم خانه ←</Link></article></section>
  </main>
}
