"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
import {Icon} from "../../ui";
import SpriteAsset from "../../SpriteAsset";
import {STORE_ITEMS,StoreItem} from "@/lib/storeCatalog";
import {stageFor} from "@/lib/sagoolCatalog";
import {MATERIALS,houseLevel,nextHouseLevel,type MaterialId} from "@/lib/progressionCatalog";
import styles from "./house.module.css";

type Dash={family:{name:string;xp:number;houseLevel:number};profile?:{coins?:number|null;is_founder?:boolean;avatar_url?:string|null;display_name?:string|null;first_name?:string|null}|null;ownedItems?:Array<{item_id:string}>};
type Progress={level:number;xp:number;coins:number;founder:boolean;inventory:Record<string,number>};
const fallback:Dash={family:{name:"خانواده ما",xp:0,houseLevel:1},profile:{coins:0},ownedItems:[]};const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0),houseItems=STORE_ITEMS.filter(x=>x.kind==="house");
async function familyAction(action:string,payload:Record<string,unknown>={}){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("Mini App رو از داخل ربات باز کن.");const r=await fetch("/api/family/action",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify({action,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||"action_failed");return d.data}
export default function HousePage(){const[selected,setSelected]=useState<StoreItem>(houseItems[0]),[toast,setToast]=useState(""),[levelBurst,setLevelBurst]=useState(false),[data,setData]=useState<Dash>(fallback),[progress,setProgress]=useState<Progress>({level:1,xp:0,coins:0,founder:false,inventory:{}}),[sagoolLevel,setSagoolLevel]=useState(1),[busy,setBusy]=useState("");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);function notify(t:string){setToast(t);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(""),2600)}
 async function refresh(){const session=sessionStorage.getItem("familybot.session");if(!session)return;try{const[dash,pet,house]=await Promise.all([fetch("/api/family/dashboard",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json()),fetch("/api/family/sagool",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json()).catch(()=>null),fetch("/api/family/house",{headers:{authorization:`Bearer ${session}`},cache:"no-store"}).then(r=>r.json())]);if(dash.ok&&dash.dashboard)setData(dash.dashboard);if(pet?.ok&&pet.data?.state?.level)setSagoolLevel(Number(pet.data.state.level)||1);if(house.ok&&house.data)setProgress(house.data)}catch{notify("دریافت اطلاعات خانه ممکن نشد")}}
 useEffect(()=>{void refresh()},[]);
 async function housePost(payload:Record<string,unknown>){const session=sessionStorage.getItem("familybot.session");if(!session)throw new Error("no_session");const r=await fetch("/api/family/house",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session}`},body:JSON.stringify(payload)}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"house_action_failed");if(x.data)setProgress(x.data);return x.data}
 async function buyMaterial(id:MaterialId,qty:number){setBusy(`material:${id}`);try{await housePost({type:"buy_material",materialId:id,quantity:qty});notify(`${fa(qty)} عدد ${MATERIALS[id].name} به انبار خانه اضافه شد ✨`)}catch(e){notify(e instanceof Error&&e.message==="insufficient_coins"?"سکه کافی برای خرید این مقدار مصالح نداری.":"خرید مصالح انجام نشد.")}finally{setBusy("")}}
 async function upgrade(){const target=nextHouseLevel(progress.level);if(!target)return;setBusy("upgrade");try{const d=await housePost({type:"upgrade"});setLevelBurst(true);setTimeout(()=>setLevelBurst(false),1800);notify(`🎉 Family House به سطح ${d.level} ارتقا پیدا کرد!`);void refresh()}catch(e){const c=e instanceof Error?e.message:"";notify(c==="insufficient_xp"?"XP خانواده هنوز برای این سطح کافی نیست.":c==="insufficient_coins"?"سکه کافی برای هزینه ارتقا نداری.":c==="insufficient_material"?"مصالح لازم هنوز کامل نشده.":"ارتقا انجام نشد؛ وضعیت را تازه کن و دوباره امتحان کن.")}finally{setBusy("")}}
 async function buyDecor(){try{const result=await familyAction("store.purchase",{itemId:selected.id});notify(result.alreadyOwned?"این آیتم رو قبلاً داری 💜":`${selected.name} خریداری شد ✨`);void refresh()}catch(e){notify(e instanceof Error&&e.message==="insufficient_coins"?"سکه کافی نداری 🪙":"خرید انجام نشد")}}
 async function claimReward(){try{const result=await familyAction("mission.claim",{missionId:"daily_task"});notify(result.alreadyClaimed?"پاداش امروز قبلاً دریافت شده.":`+${result.reward} سکه دریافت شد ✨`);void refresh()}catch{notify("اول مأموریت امروز رو کامل کن 💜")}}
 const owned=useMemo(()=>new Set((data.ownedItems||[]).map(x=>x.item_id)),[data.ownedItems]),current=houseLevel(progress.level),target=nextHouseLevel(progress.level),hasXp=!target||progress.xp>=target.xpRequired,hasCoins=!target||progress.founder||progress.coins>=target.upgradeCoins,hasMaterials=!target||target.materials.every(r=>(progress.inventory[r.id]||0)>=r.qty),canUpgrade=Boolean(target&&hasXp&&hasCoins&&hasMaterials),petAsset=stageFor(sagoolLevel).asset;
 return <main className={styles.page}><div className={`motionToast${toast?" show":""}`}>{toast}</div><div className={`levelBurst${levelBurst?" show":""}`}><div className="levelBurstCore"><div><b>✨</b><span>Family House ارتقا پیدا کرد</span></div></div></div><header className={styles.header}><Link href="/" className={styles.back}>←</Link><div><b>Family House</b><span>{data.family.name}</span></div><span className={styles.bot}>{data.profile?.avatar_url?<img src={data.profile.avatar_url} alt={data.profile.display_name||data.profile.first_name||"پروفایل"} style={{width:48,height:48,objectFit:"cover",borderRadius:16,border:"1px solid rgba(255,255,255,.22)"}}/>:<Icon name="profile"/>}</span></header>
 <section className={styles.stats}><div><span className={styles.statIcon}><Icon name="home"/></span><p>سطح خانه</p><b>Lv. {fa(progress.level)}</b></div><div><span className={styles.coin}>●</span><p>سکه‌های من</p><b>{progress.founder?"∞":fa(progress.coins)}</b></div><div><span className={styles.statIcon}><Icon name="trophy"/></span><p>XP خانواده</p><b>{fa(progress.xp)}</b></div></section>
 <section className={`${styles.sceneCard} premiumPanel`} style={{padding:12,overflow:"hidden"}}><div className={styles.sceneTitle}><div><p>{current.title}</p><span>مرحله {fa(progress.level)} از ۱۰</span></div><span className={styles.score}>{fa(progress.xp)}<br/><small>مجموع XP</small></span></div><div style={{position:"relative",minHeight:330,display:"grid",placeItems:"center",borderRadius:24,overflow:"hidden",background:"radial-gradient(circle at 50% 35%,rgba(153,104,255,.18),transparent 58%),linear-gradient(180deg,#0d1530,#080a19)"}}><img src={current.asset} alt={`Family House سطح ${progress.level}`} style={{width:"100%",height:320,objectFit:"contain",zIndex:2,filter:"drop-shadow(0 24px 35px rgba(0,0,0,.45))"}}/><img src={petAsset} alt={`سگول سطح ${fa(sagoolLevel)}`} style={{position:"absolute",width:84,height:84,objectFit:"contain",right:"5%",bottom:"4%",zIndex:5,filter:"drop-shadow(0 10px 18px rgba(53,210,255,.38))"}}/>{owned.has(selected.id)&&<div style={{position:"absolute",left:"7%",bottom:"7%",zIndex:6,filter:"drop-shadow(0 12px 20px rgba(0,0,0,.4))"}}><SpriteAsset atlas="store" index={selected.sprite} size={76} label={selected.name}/></div>}</div></section>
 {target?<section className="premiumPanel" style={{padding:16,marginTop:14}}><div className="sectionHeading"><div><span className="eyebrow">ساخت و ساز</span><h2>ارتقا به LV.{target.level} · {target.title}</h2></div><span className="levelPill">{[hasXp,hasCoins,hasMaterials].filter(Boolean).length}/3</span></div><div style={{display:"grid",gap:8,marginTop:12}}><div className="adminNotice" style={{display:"flex",justifyContent:"space-between",gap:10}}><span>XP خانواده</span><b>{fa(progress.xp)} / {fa(target.xpRequired)} {hasXp?"✓":""}</b></div><div className="adminNotice" style={{display:"flex",justifyContent:"space-between",gap:10}}><span>هزینه نهایی ساخت</span><b>{progress.founder?"Founder ∞":`${fa(progress.coins)} / ${fa(target.upgradeCoins)} 🪙`} {hasCoins?"✓":""}</b></div></div><h3 style={{fontSize:13,margin:"16px 0 8px"}}>مصالح لازم</h3><div style={{display:"grid",gap:8}}>{target.materials.map(req=>{const mat=MATERIALS[req.id],ownedQty=progress.inventory[req.id]||0,missing=Math.max(0,req.qty-ownedQty),ok=missing===0;return <div key={req.id} style={{display:"grid",gridTemplateColumns:"50px 1fr auto",alignItems:"center",gap:9,padding:9,border:"1px solid rgba(255,255,255,.09)",borderRadius:16,background:ok?"rgba(65,220,155,.07)":"rgba(255,255,255,.035)"}}><img src={mat.asset} alt="" style={{width:46,height:46,objectFit:"contain"}} onError={e=>{(e.currentTarget as HTMLImageElement).style.display="none"}}/><div><b style={{fontSize:12,display:"block"}}>{mat.name} {ok?"✓":""}</b><small style={{opacity:.72}}>{fa(ownedQty)} / {fa(req.qty)} · هر عدد {fa(mat.unitPrice)} سکه</small></div><div style={{display:"grid",gap:4}}>{missing>0&&<button className="roundButton" style={{width:74,height:34,fontSize:10}} disabled={Boolean(busy)} onClick={()=>void buyMaterial(req.id,Math.min(missing,100000))}>{busy===`material:${req.id}`?"...":`خرید ${fa(Math.min(missing,100000))}`}</button>}<button className="roundButton" style={{width:74,height:30,fontSize:10}} disabled={Boolean(busy)} onClick={()=>void buyMaterial(req.id,Math.min(1000,Math.max(1,missing||1000)))}>+ {fa(Math.min(1000,Math.max(1,missing||1000)))}</button></div></div>})}</div><button className="primaryCta" style={{marginTop:14}} disabled={!canUpgrade||Boolean(busy)} onClick={()=>void upgrade()}>{busy==="upgrade"?"در حال ساخت…":canUpgrade?`ساخت سطح ${target.level} ✨`:"XP، سکه و مصالح را کامل کن"}</button></section>:<section className="premiumPanel" style={{padding:18,textAlign:"center",marginTop:14}}><span className="eyebrow">MAX LEVEL</span><h2>🏰 قصر جهانی کامل شد</h2><p>هر ۱۰ مرحله Family House ساخته شده است.</p></section>}
 <section className={styles.sceneCard} style={{marginTop:14}}><div className={styles.sceneTitle}><div><p>دکور خانه</p><span>{fa(owned.size)} آیتم خریداری‌شده</span></div><Icon name="store"/></div><div className={styles.decorRail}>{houseItems.map(item=><button key={item.id} onClick={()=>setSelected(item)} aria-pressed={selected.id===item.id} style={selected.id===item.id?{outline:"2px solid rgba(172,132,255,.8)",transform:"translateY(-3px)"}:undefined}><SpriteAsset atlas="store" index={item.sprite} size={44}/><b>{owned.has(item.id)?"✓":"+"}</b></button>)}</div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,padding:"11px 4px 0",fontSize:11,color:"#bdb2d5"}}><span>انتخاب: <b style={{color:"#fff"}}>{selected.name}</b></span><button onClick={()=>void buyDecor()} disabled={owned.has(selected.id)} className="primaryCta">{owned.has(selected.id)?"خریداری شده":progress.founder?"دریافت رایگان · Founder":`خرید · ${fa(selected.price)} 🪙`}</button></div></section>
 <section className={styles.challenge}><div><span>🎯 چالش امروز</span><h2>یک کار خانوادگی رو کامل کن</h2><p>پاداش سکه و XP برای ساخت خانه</p></div><div className={styles.challengeArt}>✨</div><button className={styles.reward} onClick={()=>void claimReward()}>دریافت</button></section><section className={styles.dual}><article><header><h2>ماموریت‌ها و نشان‌ها</h2><span><Icon name="trophy"/></span></header><p>XP لازم برای باز شدن مراحل خانه از فعالیت واقعی خانواده می‌آید.</p><Link href="/section/achievements">مشاهده دستاوردها ←</Link></article><article><header><h2>فروشگاه خانه</h2><span><Icon name="store"/></span></header><div className={styles.shop}>{houseItems.slice(0,3).map(item=><div key={item.id}><SpriteAsset atlas="store" index={item.sprite} size={48}/><b>{fa(item.price)} 🪙</b></div>)}</div><Link href="/section/store?tab=house">همه آیتم‌ها ←</Link></article></section></main>}
