"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {Icon,IconOrb,Mascot} from "../../ui";

type Member={id:string;display_name?:string|null;first_name?:string|null};
type Challenge={id:string;title:string;description?:string|null;challenge_type:string;target_value:number;reward_coins:number;status:string};
type Participant={challenge_id:string;member_id:string;reward_claimed_at?:string|null};
type Place={id:string;name:string;category:string;address?:string|null;notes?:string|null;latitude?:number|null;longitude?:number|null};
type Duel={id:string;creator_member_id:string;opponent_member_id:string;winner_member_id?:string|null;status:string;reward_coins:number};
type Data={me:Member;members:Member[];challenges:Challenge[];participants:Participant[];places:Place[];duels:Duel[];canManage:boolean};
const empty:Data={me:{id:""},members:[],challenges:[],participants:[],places:[],duels:[],canManage:false};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n||0),choices=["سنگ","کاغذ","قیچی"];

function osmEmbed(lat:number,lng:number){const span=.02;const bbox=[lng-span,lat-span,lng+span,lat+span].join("%2C");return `https://www.openstreetmap.org/export/embed.html?bbox=${bbox}&layer=mapnik&marker=${lat}%2C${lng}`}

export default function CommunityPage(){
  const[d,setD]=useState<Data>(empty),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[selectedPlace,setSelectedPlace]=useState<Place|null>(null),[lat,setLat]=useState(""),[lng,setLng]=useState("");
  const load=useCallback(()=>{const s=sessionStorage.getItem("familybot.session");if(!s)return;fetch("/api/family/community",{headers:{authorization:`Bearer ${s}`},cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.ok){setD(x.data);setSelectedPlace(p=>p||x.data.places?.find((v:Place)=>v.latitude!=null&&v.longitude!=null)||null)}}).catch(()=>undefined)},[]);
  useEffect(()=>load(),[load]);
  async function act(action:string,payload:Record<string,unknown>){const s=sessionStorage.getItem("familybot.session");if(!s)return setMsg("Mini App را از داخل بله باز کن.");setBusy(true);setMsg("");try{const r=await fetch("/api/family/community",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${s}`},body:JSON.stringify({action,payload})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||"action_failed");setMsg("انجام شد ✨");load()}catch(e){setMsg(e instanceof Error?e.message:"عملیات انجام نشد")}finally{setBusy(false)}}
  const names=useMemo(()=>new Map(d.members.map(m=>[m.id,m.display_name||m.first_name||"عضو خانواده"])),[d.members]);
  const mine=new Map(d.participants.filter(p=>p.member_id===d.me.id).map(p=>[p.challenge_id,p]));
  const mapPlace=selectedPlace&&selectedPlace.latitude!=null&&selectedPlace.longitude!=null?selectedPlace:null;
  function useCurrentLocation(){if(!navigator.geolocation){setMsg("GPS روی این دستگاه در دسترس نیست.");return}setMsg("در حال گرفتن موقعیت...");navigator.geolocation.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLng(String(p.coords.longitude));setMsg("موقعیت فعلی آماده شد 📍")},()=>setMsg("اجازه دسترسی به موقعیت داده نشد."),{enableHighAccuracy:true,timeout:10000})}
  return <main className="appShell"><header className="appHeader"><a className="roundButton" href="/">←</a><div className="wordmark"><b>Family Community</b><span>چالش، سفر و رقابت</span></div><span className="profileAvatar"><Icon name="family"/></span></header>
    <section className="homeHero premiumPanel" style={{minHeight:210}}><div className="homeHeroCopy"><span className="eyebrow"><Icon name="spark" size={15}/> زندگی مشترک</span><h1>با هم انجامش بدیم</h1><p>چالش، مکان‌های محبوب و دوئل خانوادگی در یکجا.</p></div><Mascot small mood="celebrate"/></section>{msg&&<div className="adminNotice">{msg}</div>}

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>چالش‌های خانواده</h2>{d.canManage&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("challenge.create",{title:f.get("title"),description:f.get("description"),type:f.get("type"),target:Number(f.get("target")||1),reward:Number(f.get("reward")||0),endsAt:f.get("endsAt")||null});e.currentTarget.reset()}} style={{display:"grid",gap:8}}><input name="title" required placeholder="مثلاً ۷ روز پیاده‌روی"/><textarea name="description" rows={2} placeholder="توضیح"/><select name="type"><option value="custom">دلخواه</option><option value="walk">پیاده‌روی</option><option value="read">مطالعه</option><option value="exercise">ورزش</option><option value="photo">عکس قدیمی</option><option value="cooking">آشپزی</option></select><input name="target" type="number" min="1" defaultValue="1"/><input name="reward" type="number" min="0" max="10000" placeholder="پاداش Family Coin"/><input name="endsAt" type="datetime-local"/><button className="adminSave" disabled={busy}>ساخت Challenge</button></form>}<div style={{display:"grid",gap:8,marginTop:10}}>{d.challenges.map(c=>{const p=mine.get(c.id);return <article className="dashboardCard" key={c.id}><IconOrb name="trophy" tone="gold"/><div><h2>{c.title}</h2><p>{c.description||c.challenge_type} · هدف {fa(c.target_value)} · {fa(c.reward_coins)} 🪙</p></div>{!p?<button disabled={busy||c.status!=="open"} onClick={()=>void act("challenge.join",{challengeId:c.id})}>پیوستن</button>:p.reward_claimed_at?<span className="levelPill">✓ کامل</span>:<button disabled={busy} onClick={()=>void act("challenge.complete",{challengeId:c.id})}>تکمیل</button>}</article>})}</div></section>

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>مکان‌های محبوب و سفر</h2><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act("place.add",{name:f.get("name"),category:f.get("category"),address:f.get("address"),lat:lat||null,lng:lng||null,notes:f.get("notes")});e.currentTarget.reset();setLat("");setLng("")}} style={{display:"grid",gap:8}}><input name="name" required placeholder="نام مکان"/><select name="category"><option value="restaurant">رستوران</option><option value="park">پارک</option><option value="villa">ویلا</option><option value="trip">مقصد سفر</option><option value="other">سایر</option></select><input name="address" placeholder="آدرس"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input value={lat} onChange={e=>setLat(e.target.value)} placeholder="Latitude" inputMode="decimal"/><input value={lng} onChange={e=>setLng(e.target.value)} placeholder="Longitude" inputMode="decimal"/></div><button type="button" onClick={useCurrentLocation}>📍 استفاده از موقعیت فعلی</button><textarea name="notes" rows={2} placeholder="یادداشت"/><button className="adminSave" disabled={busy}>ذخیره مکان</button></form>
      {mapPlace&&<div style={{marginTop:12,overflow:"hidden",borderRadius:18,border:"1px solid #ffffff16"}}><iframe title={`نقشه ${mapPlace.name}`} src={osmEmbed(Number(mapPlace.latitude),Number(mapPlace.longitude))} loading="lazy" style={{width:"100%",height:260,border:0,display:"block"}}/><div style={{padding:10,fontSize:11}}>📍 {mapPlace.name}{mapPlace.address?` · ${mapPlace.address}`:""}</div></div>}
      <div style={{display:"grid",gap:8,marginTop:10}}>{d.places.map(p=><button className="dashboardCard" key={p.id} style={{width:"100%",textAlign:"right"}} onClick={()=>setSelectedPlace(p)}><IconOrb name="home" tone="cyan"/><div><h2>{p.name}</h2><p>{p.category}{p.address?` · ${p.address}`:""}{p.latitude!=null&&p.longitude!=null?" · دارای نقشه":""}</p></div></button>)}</div>
    </section>

    <section className="adminPanel premiumPanel" style={{marginTop:14}}><h2>دوئل دو نفره</h2><div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><select id="duelOpponent" defaultValue=""><option value="">انتخاب حریف</option>{d.members.filter(m=>m.id!==d.me.id).map(m=><option key={m.id} value={m.id}>{m.display_name||m.first_name||"عضو"}</option>)}</select><button className="adminSave" disabled={busy} onClick={()=>{const el=document.getElementById("duelOpponent") as HTMLSelectElement|null;if(el?.value)void act("duel.create",{opponentMemberId:el.value})}}>دعوت</button></div>{d.duels.filter(x=>x.creator_member_id===d.me.id||x.opponent_member_id===d.me.id).map(x=><article className="dashboardCard" key={x.id}><IconOrb name="games" tone="violet"/><div><h2>{names.get(x.creator_member_id)} × {names.get(x.opponent_member_id)}</h2><p>{x.status==="finished"?(x.winner_member_id?`برنده: ${names.get(x.winner_member_id)}`:"مساوی"):"در انتظار هر دو نفر"} · {fa(x.reward_coins)} 🪙</p></div>{x.status==="active"&&<div>{choices.map((c,i)=><button key={c} disabled={busy} onClick={()=>void act("duel.play",{duelId:x.id,choice:i})}>{c}</button>)}</div>}</article>)}</section>
  </main>}
